### ISSUE TITLE
On hover show all shortest path

### ISSUE THREAD

**Issue by SpaceOgre** [EmmittJ/PoESkillTree#103]
There are times when you hover on a node and there are more than one shortest path to it. It would be great if we could show all shortest paths and cycle through them to let the user deiced which to use.

To achieve this we would need a new version of GetShortestPathTo, eg GetShortestPathsTo, that returns a list with shortest paths.

Any ideas/suggestions for this is welcome since it is not all that straight forward.

**Comment by MLanghof** [comment]
There can be a _lot_ of shortest paths, especially with far away nodes. What would be reasonable would be doing the same thing as the skill tree tool on pathofexile.com: Highlight all nodes that lie on shortest paths. It really shouldn't be hard to extract that from the pathfinding algorithm.

The question of which path to actually use when skilling a node is avoided by the web app, but I don't think there's any solution that is easier than the user "pathing" through the route he actually wants.
I guess you could ask him interactively ("_This_ node or _this_ node?"), but that sounds like a huge effort to properly implement a UI for (I'd guess markers on the nodes that can be clicked to decide the path decision by decision... Which is exactly what you do right now, minus the markers that help guide you to wherever you were trying to go).

**Comment by SpaceOgre** [comment]
True, it is possible that there will be lots of shortest paths. The biggest problem would be all paths that only diff by one node or so and that would clutter the UI really fast. So I have to agree with you that this would be more problem than help.

I'm not following you on what the skill tree tool on pathofexile.com does, all I can see is that it highlights all outgoing paths from picked nodes.

**Comment by MLanghof** [comment]
This is what I mean:
![Multiple highlighted paths](http://i.imgur.com/FKTwk38.png)

**Comment by SpaceOgre** [comment]
I have never seen that before, do I need to hold some key down or something? Or is it a browser thing?

**Comment by EmmittJ** [comment]
Checkbox called show path or something like that.

**Comment by MLanghof** [comment]
You need to select the "highlight shortest path" at the bottom to have that in the web app. Would be very weird if this was browser specific.

**Comment by SpaceOgre** [comment]
Yeah, it works fine now. Never even knew about that function :)
