### ISSUE TITLE
Act 4

### ISSUE THREAD

**Issue by EmmittJ** [EmmittJ/PoESkillTree#108]
Chris gave me a bit of heads up that there may need to be some changes in the 2.0 Skilltree. These are more than likely going to be functional changes to the tree and not just accommodation of new nodes. Just thought I would give you guys the heads up. He said we would see why tomorrow when the embargo lifts.

**Comment by SpaceOgre** [comment]
I get the feeling that the build URLs and the JSON tree data will change in a way so that we need to make changes in our code. The problem I feel is not that we will not fix it, because I think we will, but the timing issue. These changes might take a while to fix and since this is a project done on off hours for all of us, it might take a while.

**Comment by nyashaint** [comment]
I think this is what Chris was talking about: 
![yp41fn2 1](https://cloud.githubusercontent.com/assets/1394349/7086754/4156e80e-df8d-11e4-81be-19b645cfe481.jpg)

It looks like a gem from D2 :) If that's the case and this gem only contains stats - it's not a big deal. But what if you can select a couple of them across the tree and make a "runeword" out of them? Oh boy :)

**Comment by SpaceOgre** [comment]
Not a big deal for the internal stuff but if the official tree planer adds support for this then the URL and data will change, and we need to be able to handle that.

**Comment by EmmittJ** [comment]
That is what I am more worried about. I don't really want to mess with the
parser to get all the stats and save them. It isn't very hard but still an
annoying process.

**Comment by SpaceOgre** [comment]
Well shit: https://www.pathofexile.com/theawakening
The once with radius might be pretty hard, unless the radius data is in the JSON from the website.

**Comment by EmmittJ** [comment]
Well, this is going to take some time to figure out. We are also probably going to have to develop a system to craft gems.

**Comment by EmmittJ** [comment]
Ok, so for now we can actually start preparing for the tree. We know that we will need to be able to collect information from surrounding nodes, change stats of surrounding nodes, and be able to skill nodes in an area. We can actually work on implementations before the tree comes out.

**Comment by l0g0sys** [comment]
Is there any description of whole mechanic?

**Comment by SpaceOgre** [comment]
If we can figure out how to map the radius correctly then finding nodes
will not be a problem.

**Comment by EmmittJ** [comment]
There are sockets in the tree. These sockets can have jewels placed within them. Some of these sockets affect surrounding nodes, others just apply stats as if it were any other node. These jewels that have a radius affect so far can alter what bonus a node gives, the source the bonus goes to and how selection works.

I don't think there is a full detailed description of all the jewels yet.

**Comment by EmmittJ** [comment]
Radius isn't difficult. It would probably be in the json.

**Comment by EmmittJ** [comment]
It is as easy as sqrt((x'-x)^2+(y'-y)^2) and just checking if that falls within a value. Drawing a circle on the tree also shouldn't be too difficult ;)

**Comment by l0g0sys** [comment]
Not jewels, where did you get all these informations from? Mechanic 
description, not item description, i'm interested in.

**Comment by EmmittJ** [comment]
Jewels are the new mechanic. Look at https://www.pathofexile.com/theawakening  

Watch some of the videos about the passive tree.

**Comment by l0g0sys** [comment]
Can't find it, only some Combat Preview.

**Comment by EmmittJ** [comment]
http://www.pathofexile.com/forum/view-thread/1242809

**Comment by MLanghof** [comment]
Things will definitely get interesting.
I'm mainly curious if you want to let people craft gems within the app (and if it will know about all the unique ones). One more thing to be excited about with Act 4 :)

**Comment by l0g0sys** [comment]
Think crafting won't be needed, there will be limited set of jewels with 
fixed mods you can pick from and socket it. So they will be most likely 
in ItemDB.
More interesting will be UI for it :)

**Comment by SpaceOgre** [comment]
Not so sure, looking at the teased jewels there are magical, rare and unique. If so then there can be a lot of combinations. But we won't know for sure until we can test :)

**Comment by MLanghof** [comment]
The question is: Can you vaal them? :D

**Comment by EmmittJ** [comment]
You can vaal them.

**Comment by l0g0sys** [comment]
Yep, all we can do is speculate. It isn't clear yet, where actually will 
be storage for applied jewels. They can be part of inventory JSON or 
tree URL. But even if they were part of inventory, i'd skip crafting 
phase. UI doesn't have to be simple select-box. All I want is to avoid 
of having multiple UI actions to socket jewel (e.g. craft jewel into 
some virtual storage, then click on socket and pick jewel from virtual 
storage). That's what i mean by not crafting jewels.

**Comment by EmmittJ** [comment]
I was thinking clicking on a slot would allow you to craft a gem, then we
could go from there. A nice simple ui for it

**Comment by l0g0sys** [comment]
Yep, that's what i mean. Tho, by crafting, i mean an act of item 
instantiation with all item properties used in inventory JSON. So, once 
you do real crafting, pretty much you can layout base for crafting of 
any item as those jewels might follow rules of an regular item (maybe 
with diferent mod counts per rarity).

**Comment by EmmittJ** [comment]
Yeah, they have 2 mods for magic and 4 mods for rare. I don't think we can get away with not being able to craft these jewels. It doesn't matter if the data is in the JSON or not, we still will need to provide a way for the user to pick the stats they want.

**Comment by l0g0sys** [comment]
All i saw in video was 1 mod on unique ones.

**Comment by MLanghof** [comment]
Then go to http://www.pathofexile.com/theawakening and hover over the ones presented there. Magic, rare, unique...

**Comment by nyashaint** [comment]
This seems to be the most complete list of unique jewels so far
http://cb.poedb.tw/us/unique.php?c=theawakening

**Comment by EmmittJ** [comment]
Yep, but I can't do anything until the json is released. I have beta
access, but the data can't be accessed yet.

**Comment by l0g0sys** [comment]
You have beta access already? Looks like it will take some time till i get one :)

**Comment by Ttxman** [comment]
Ok. So we will need to integrate an item editor and item database...
I am thinking of basing it on Procurement. I had used it as library before (without many changes), so it shouldn't be a big problem to use its UI classes and some affix list to generate items. 
I have already paired affixes with item bases, it is not 100% correct, but it should be enough for some initial version.
I can try to put some demo together in next few days and create pull request.

**Comment by l0g0sys** [comment]
Procurement is pure stash/forum management tool. There is no crafting and no mod data at all. Not sure it would help us in any way. The only views which could be integrated would be maybe Inventory and some ItemHover?

**Comment by Ttxman** [comment]
I have Mod analyser with mod data datamined from shop forums (i can generate all mod combinations (with tiers) that can be on given item...) and I can probably reuse it for item generation. :P

Actually procurement have lot of features that will be needed (probably):
- Data structure for items with serialization and deserialization
- UI parts: Item visualization, Item Hover, item search UI, highlighting ...
- offline storage (database) of items (we have that, but without UI bindings)
- pairing items to gear slots (you need working base type identification for this... and there were some errors even in procurement (reported & fixed now), its not entirely trivial)
- complete base type list
- download and filter out needed items (jewels) from player stash.

And there are other people maintaining the net code, item data and fixing bugs... which should save us some work :)

**Comment by l0g0sys** [comment]
All mods for each item type can be pretty much found at http://www.poemods.com/ (current ones ofc).
Regarding Procurement features you mentioned:

**Data structure for items with serialization and deserialization**
We have pretty much model for items with deserialization. Serialization shouldn't be much of issue.
And i don't think it's wise to start with new model while we already have deep dependencies all over project with our current one. Imho, waste of time.

**UI parts: Item visualization, Item Hover, item search UI, highlighting ...**
This... i don't care much about :p I'm UI noob.

**offline storage (database) of items (we have that, but without UI bindings)**
We will go along with idea of community self-maintained item database (i.e. primary by datamining of Wiki). So we won't have to care about items at all. Only minimum of necessary data will be kept maintained within application.

**pairing items to gear slots (you need working base type identification for this... and there were some errors even in procurement (reported & fixed now), its not entirely trivial)**
At first glance, can't see really problem here at all :) But who knows.

**complete base type list**
Will be datamined.

**download and filter out needed items (jewels) from player stash.**
This is not really priority. Once you can create own jewel, you don't need stash at all.
This is planning application, so you want to plan with stuff you probably don't have yet :)

So, i'd not jump onto Procurement so fast :) It might create more mess than good.

**Comment by Ttxman** [comment]
**UI stuff**
For now I'll look into the UI code to find out how much work will be reimplementing procurement features with current Item model.
(we can probably just take some of their code, there shouldn't be problem with licenses)

There could be lot of annoying stuff with item images (unique items have different images...) Store them with application or download them on demand? ...

**Pairing items to gear slots** - its a mess in corner cases like blue items with 1 affix, some base types are substring of others or mods (map in MAPle shield ...). JSON data for item can differ pretty significantly for different cases. You can easily miss something.

**Poemods** - I didn't know its back online.
There are too few categories for full featured item editor :)
For example: spellshields can roll different subset of shield mods than normal shields, same problem with armor/ES/evasion/hybrid armors.
Some Critical strike mods were incorrect, but there are two sets listed on official site so who knows :)

**complete base type list**
No need for datamining we can ask and borrow data.xml from procurement :)

**download and filter out needed items (jewels) from player stash.**
I kind of like feature to to show change in DPS with items from my stash :)
But it can probably be done with ctrl+c ingame and paste and parse item in PoESkillTree instead of loading entire stash

**Comment by lawl** [comment]
I would just like to propose the simple solution of people copy pasting items from their game client into the skill tree? Ctrl+C on an item exports it as text to the clipboard. That should be fairly easy to parse and is definitly still faster than waiting procurement style for 100 stash tabs to load.

Maybe I'm missing something here though, not really involved in the project, but I think jumping onto procurement is a bad idea.

**Comment by Ttxman** [comment]
I never meant to use procurement as whole application, just to borrow some features (and code)
Normal user probably would not notice that there are some procurement libraries.

**Comment by lawl** [comment]
You still have a dependency on procurement at that point, that in my opinion isn't really necessary. Plus it's another app that has your login data. As a said, just my POV, as a non dev in this project.

**Comment by EmmittJ** [comment]
I would like to add that currently we don't store login data

**Comment by ccbrown** [comment]
This may be a silly question, but... has no effort been made to obtain the tree from the game files?

There are readily available libraries for working with Path's .ggpk and .dat files (e.g. https://github.com/MuxaJIbI4/libggpk).

The passive skill information such as the name, icon, stat id, stat coefficients, type, flavor text, etc. can be trivially exported from Data/PassiveSkills.dat. The stat information can likewise be exported from Data/Stats.dat. And the tree structure can be found in Metadata/PassiveSkillGraph.psg.

As far as I can tell, the only significant work that would be involved would be parsing and laying out the graph. Everything else is a 1:1 translation to what's currently in the JSON.

Is it just a matter of prioritizing other things over getting skill trees out early?

**Comment by EmmittJ** [comment]
Not able to view it right now, but could you tell me if it is in a JSON
format? Also, I don't exactlt want to hurt our relationship with GGG by
releasing something that isn't intended to be released

**Comment by ccbrown** [comment]
It's not. Using the tools in libggpk, the passive skill data exports as CSV:

```
Rows,Id,Icon,Stats,Stat1,Stat2,Stat3,Stat4,Unknown8,Name,Data1,IsKeystone,IsNotable,FlavourText,IsJustIcon,Unknown13
0,lava_lash1,Art/2DArt/SkillIcons/passives/lavalash.dds,[408],30,1,1,1,30439,Lava Lash,[],False,True,,False,355
1,two_handed_weapon_damage_and_stun_duration4,Art/2DArt/SkillIcons/passives/stun2h.dds,"[339, 340]",8,8,1,1,22233,Two Handed Melee Damage and Stun Duration,[],False,False,,False,-1
```

The stat data is a similar format.

The passive skill graph is a binary format that defines the tree and would take a bit of reverse engineering. I've only taken the time to decipher bits and pieces of it, and I'm not sure if anyone else has published anything on it, so this would be where majority of the engineering effort would be.

The relationship with GGG is important, and I don't know where their stance on this would lie. But I definitely think it would be feasible for someone with beta access to generate a JSON file that would work with the skill tree planner as-is (minus jewel functionality).

**Comment by l0g0sys** [comment]
Well, I know where their stance on data mining is. It's nowhere. There were numerous questions asked on forums about the issue and there was never official answer. That's the reason why i choosed to use Wiki as source of data for gems instead of reading game files directly. So, we don't have to deal with this issue at all.

I think releasing the skill tree before official release would be last nail to this status quo :)
They don't want to release it because:
 1 They don't have JavaScript libs working with new type of nodes and new funcitonality.
 2 Or, simply the tree is subject to change. So why to release something that will be change maybe few times before actual release.

**Comment by ccbrown** [comment]
Oh hey... supporter packs include beta keys... and the format of all these files are exactly the same except for the addition of an "isSocket" boolean in PassiveSkills.dat.

Well, I'm gonna generate myself a JSON file for personal use... If you guys decide to put it out there, let me know and I'll share what I come up with.

**Comment by ccbrown** [comment]
Well that actually ended up being a much easier project than I expected. Wrote up a 100 or so line Python script to parse those files and generate some JSON that works in the current skill tree planner and other than some cosmetic things (icons / text) will probably be identical to the JSON that GGG eventually publishes.

![Screenshot](http://i.imgur.com/BSdAsnW.jpg)

With the surge of people getting in the beta via supporter packs now, and the complete availability of all this information already, I can't see any real problem with publishing this. Maybe it'll even encourage more thoughtful feedback.

I dunno. I'm going to sleep, so I'll at least give it some thought, and if you guys want to make a case against it, by all means do.

**Comment by EmmittJ** [comment]
Honestly, we don't have to make a case. No is no.

**Comment by l0g0sys** [comment]
Yep, there is no point breaking our application for rest of players 
still playing only official leagues in game by adopting this beta skill 
tree.
Not to mention, there is still some stuff to be done before even 
thinking about new tree (at least i have few things on TODO list), for 
which official tree is pretty much neccesary.

So, I'd suggest you to make a thread on forums with link to your 
datamined skill tree file and simple instructions on how to replace it 
in app.

**Comment by ccbrown** [comment]
Okay you guys misunderstood me. I would never suggest making an update to the app that only sorta works with the closed beta. What I had in mind was in fact simply a reddit thread or something along those lines. 

I wanted to give you guys a chance to speak up if you thought the mere existence of it would be harmful to the community.

It sounds like we're actually in complete agreement.

**Comment by EmmittJ** [comment]
It wouldn't be harmful to the community, but all of the Devs of the
community. If you release data before it is ready then you force GGG to
correct this by pushing out data that isn't even done. It would also being
a lot of pressure on us and poebuilder to update our tools to handle such
data.

**Comment by vmrob** [comment]
Just another onlooker chiming in:

@ccbrown, I think you should release the data. It's obviously already packaged into the client, it _would_ be helpful to devs that want to make use of it, and there's no NDA on the closed beta. Historically, GGG has been very supportive of the community with respect to these kinds of things.

@EmmittJ, could you elaborate what you mean by forcing GGG "to correct this by pushing out data that isn't even done."? I might be having trouble parsing that sentence. Worst case scenario, GGG decides they didn't want info to be datamined and they take steps to correct it via encryption. Even if that does happen, I don't think it would be a problem at all--it just means you only get access to complete data.

For what it's worth, more pressure to update tools is also a _good_ thing. It means said tools are being used and the impatient ones might even do the work for you via pull requests. More information and more contributors are wins across the board.

**Comment by EmmittJ** [comment]
Sure, what I mean is that the data presented here isn't correctly done.
Sockets, images, and stats aren't complete so releasing this data means
that GGG will have to update the images, complete sockets and finish their
own JavaScript.

Honestly, I don't care what individuals do. I just do not want to deal with
the 'bugs' with data that isn't official.

**Comment by vmrob** [comment]
@EmmittJ, that makes sense, but I don't think GGG is going to prioritize development differently based on what the community has and doesn't have. Unless they start seeding the client with unofficial data, you could say we have the most official data available: exactly what the client sees. That's about as official as you can get. If the client contains a bug on the other hand.. that's outside our control and something GGG will have to correct anyways.

**Comment by Kaezin** [comment]
I agree with Emmitt.  IIRC GGG has not finished their balance pass yet, and
for all we know that could very well include skill tree updates.  By
pushing out the data before GGG is finished, we're potentially creating a
lot of noise for GGG to deal with.  We need to respect the fact that this
is a beta.  GGG was hesitant to release the skill tree JSON too early with
the last update; why would now be any different?

**Comment by ccbrown** [comment]
@Kaezin The most glaring difference is that the data is already widely available. Last time it was not. People can already look at images and data dumps of the tree. There's no further harm in letting them click to highlight nodes and do math for then. There's also a huge difference in GGG releasing / endorsing something and an independent doing so.

**Comment by benjaminjackman** [comment]
Just an FYI Chris gave the go ahead in email: http://imgur.com/dNWq6P5

All the additional reasons you listed for not updating it also sound very reasonable, just wanted to let you know that Chris is OK with it if you guys give it a shot.

**Comment by SpaceOgre** [comment]
@EmmittJ Any news on the new json data? Even if they are still tweaking the numbers atm they might have decided on the object names, if so we can start working on updating our parser.

**Comment by EmmittJ** [comment]
I haven't received any news, but if official release date is July 10th we
are probably close to receiving the data.
