### ISSUE TITLE
Problem with RegExp

### ISSUE THREAD

**Issue by SpaceOgre** [EmmittJ/PoESkillTree#111]
There is a bug with the latest release.

It involves using RegExp. I can turn it on and try to type "(" and I get an alert that the program crashed, but it actually doesn't. I close it anyway and reopen.

**Comment by EmmittJ** [comment]
Pretty sure this happens with most [ and { as well. I think it is a pretty
easy debug though.

**Comment by l0g0sys** [comment]
Isn't it in try/catch ? It should, as it's pretty obvious while typing 
you have invalid regular expression.

**Comment by EmmittJ** [comment]
I thought it was in a try catch, but from what it sounds like it isn't.

**Comment by EmmittJ** [comment]
In the regex catch there is a Debugger.Break() command......

**Comment by SpaceOgre** [comment]
This was reported on reddit, nice with a fast fix!
