### ISSUE TITLE
Light Theme

### ISSUE THREAD

**Issue by Scol91** [EmmittJ/PoESkillTree#112]
When switching to Light theme some elements stay dark - menu bar (the one with File, Edit etc.) and buttons (Reset, Load Build and POEURL IT!). Font color changes to black but backgrounds stay dark gray making it unreadable.

**Comment by EmmittJ** [comment]
I can't reproduce your error. Can you please state your SkillTree version, this can be found by Help>About. 

Thank you

**Comment by Scol91** [comment]
Saved Build list and related buttons are also affected.

Also, when changing Accent some elements don't update until I press Reset.

Version 2.1.3 (just downloaded)

**Comment by EmmittJ** [comment]
Have you tried restarting the program?

**Comment by Scol91** [comment]
Yes, running it with admin rights doesn't help either

**Comment by Scol91** [comment]
Also, I'm on almost fresh windows installation, had no issue with it before (might been older version thou), Is it possible I'm missing some required framework/redistributable?

**Comment by EmmittJ** [comment]
Should just need the .NET 4 framework.

**Comment by Scol91** [comment]
Reinstalled .NET 4, didn't helped. Here's screenshot for reference: http://imgur.com/tf1tdkx

**Comment by EmmittJ** [comment]
Make sure PersistentData.xml has both read permissions. 

What OS?

**Comment by Scol91** [comment]
Windows 7, PersistentData.xml has both read permissions. Installing all Windows Updates now, maybe it'll fix it.

**Comment by EmmittJ** [comment]
Hmm, yeah. Let me load up a win 7 machine and see if I can replicate it there

**Comment by EmmittJ** [comment]
Still works on that machine.

**Comment by Scol91** [comment]
Windows Update will probably take some time, I'll probably let you know if it helped tomorrow (in like 11-13 hours).

**Comment by Scol91** [comment]
Windows Update didn't helped. Tried downgrading to 2.1.2, dind't work either.

**Comment by SpaceOgre** [comment]
I knew that I had seen this reported before so I did a check, but sadly the problem was not solved that time as far as I know.

It is hard to debug since we have not been able to recreate it.
