### ISSUE TITLE
can't load a tree when the URL is fullscreen

### ISSUE THREAD

**Issue by srouquette** [EmmittJ/PoESkillTree#116]
[example](https://www.pathofexile.com/fullscreen-passive-skill-tree/AAAAAgEBAdwEBwUtBg4I9An2C2EMXxBYES0UIBkuHKcfAicvJ9Un7Sj6Ko0snC0fNZI22DpYPC09_EGHQ8hFnUd-SRtMs0z_T69TUlOlVcZYY1ugXz9hIWe9aPJqQ2sXdO14DXloeu98DnyDgh6Cm4LHg9uD94TZhO-HZZBVlSCa4KIAp1WpbqyYrY2vbLXytz64k7zqvTa-isBUwQTB88RYxLjE9sauxtjN-s9-1HzV-Ni92WHbC-Fz4urr7uw47FXtIO8O8B_xbPTp9kj56P4K)

Maybe GGG changed the way fullscreen URLs are formatted, but PoESkillTree warns the build is invalid because there's a "fullscreen-" added before passive-skill-tree in the URL.

**Comment by EmmittJ** [comment]
Fixed.
