### ISSUE TITLE
Get Item Data

### ISSUE THREAD

**Issue by EmmittJ** [EmmittJ/PoESkillTree#118]
Getting items has been changed. It looks like we now need an account name to also get item data.

New URL: 
https://www.pathofexile.com/character-window/get-items?character=YourCharacterName&accountName=YourAccountName

Just thought I would throw this out there in case someone is around before I can get to a computer later.

**Comment by l0g0sys** [comment]
Lol. Are they planning on having different characters same names? :) Otherwise, i can't see why would they add this.

**Comment by EmmittJ** [comment]
You literally have to in order to get the item data...

**Comment by l0g0sys** [comment]
Heh, i found new item property "lockedToCharacter":false.
Anyway, we should update it in Download items dialog too.

**Comment by EmmittJ** [comment]
That was what I was getting at :)

**Comment by EmmittJ** [comment]
I am just fixing this up, but I don't think we want to actually store peoples account names in the Persistent Data huh?

**Comment by l0g0sys** [comment]
Well, i don't mind storing account name in persistent data if it is neccesary. In the end, you can find them on official web pages :)

**Comment by EmmittJ** [comment]
True, so should I pull it? Just wanted to make sure it was the correct fix

**Comment by l0g0sys** [comment]
You allowed user to enter account name to open correct URL to get-item 
page. So looks good to me.

**Comment by EmmittJ** [comment]
Done then.
