### ISSUE TITLE
Redownload Tree Assets ends with error

### ISSUE THREAD

**Issue by l0g0sys** [EmmittJ/PoESkillTree#122]
Exception "An item with the same key has already been added." is thrown in SkillTree ctor on
```c#
_rootNodeClassDictionary.Add(nd.dn.ToString().ToUpper(), nd.id);
```
during
```c#
SkillTree.CreateSkillTree();//create new skilltree to reinitialize cache
```

**Comment by EmmittJ** [comment]
Is the node dictionary not being cleared on redownload?

**Comment by l0g0sys** [comment]
No idea. Just looking at code makes me wonder, how it can actualy work :p

**Comment by EmmittJ** [comment]
I just looked through it as well...I have no idea why that is the only
dictionary to through that error.

It is an easy fix, just clearing the dictionary, but I am not sure that is
the proper fix.

**Comment by l0g0sys** [comment]
Me neither, all that Skill tree stuff is voo-doo to me. Maybe Max could 
take look into it, he fought good battle with Skill tree class :)

**Comment by EmmittJ** [comment]
If you look a couple lines below I fixed an error there at some point, but
I didn't apply that fix to the one causing the error >.>

**Comment by EmmittJ** [comment]
Just looking at that code and around that line (don't know the exact line
because I am on my phone) but there is a very redundant loop. That actually
doesn't do anything at all.

I can fix that up when I get home :)

**Comment by EmmittJ** [comment]
Oh, no they aren't redundant I just remembered why that line is there. The
root nodes aren't always linked to the starting 2, or 6 with scion, nodes.
Same for the reverse, start nodes aren't walkways linked back to the root
nodes.

I had a big problem with that, so I will just add a line of it doesn't
contain then add.

**Comment by EmmittJ** [comment]
Ok, so I actually found the source of the error. It is on line 535 in SkillTree-Drawing.cs for some reason it is trying to add the face backgrounds more than once.

**Comment by EmmittJ** [comment]
Commit 03860274c259f8c1f52e7304daf73bab8ad98b60 fixed this. I belive.

**Comment by l0g0sys** [comment]
Yep, fixed.
