### ISSUE TITLE
LoadingWindow doesn't show progress during download of tree assets

### ISSUE THREAD

**Issue by l0g0sys** [EmmittJ/PoESkillTree#124]
Reproduce:
1) Close application
2) Delete Data folder
3) Start application

**Comment by SpaceOgre** [comment]
Did a fast check:
2.1.2: Work
2.1.3: Does not work

So some where between these two releases we made it broke ;)

**Comment by EmmittJ** [comment]
Ok, so the only thing I can see, that may have caused it, is that SkillTree now has an owner and that is the MainWindow. I am not sure if that would do it or not.

**Comment by SpaceOgre** [comment]
Not sure, it could I guess but I just added that as a property for the skill highlighted nodes window for correct alt tab behavior. So it would be weird if that's the problem. We should start and test if the progress functions are called as they should.

**Comment by EmmittJ** [comment]
I was looking into that too, and it looks like the update function may not
be called correctly. It should be checking if it can access the loading
window, and if it can't then it need to invoke the actions that we want.
