### ISSUE TITLE
Menu Theme/Accent cannot be localized

### ISSUE THREAD

**Issue by l0g0sys** [EmmittJ/PoESkillTree#127]
Menu Theme/Accent cannot be localized due to use of MenuItem.Content directly. The C# backend should not use actual displayed name of theme colors and dark/light option when they are going to be translated.

**Comment by EmmittJ** [comment]
Basically all the problems with localization is that we are accessing the
content and not a value, correct?

**Comment by l0g0sys** [comment]
Yep, don't remember where exactly it was crashing.
Think it was here:
private void mnuSetTheme_Click(object sender, RoutedEventArgs e)
{
     ...
     SetTheme(menuItem.Header as string);
}
Header property can contain translated string. So it shouldn't be used 
to determine which theme was choosen.
