### ISSUE TITLE
Level/Used top-middle bar doesn't have enough space for localization

### ISSUE THREAD

**Issue by l0g0sys** [EmmittJ/PoESkillTree#129]
Some automatic layout should be implemented (something like @Ttxman suggested in #113).

Or... other way of displaying information could be considered. Maybe use of icons, where on hover over icon, tooltip could be even more comprehensive as simple "Level", "Used" labels.
Also label for Class combobox is missing, while Help document is referring to it.

Same problem is with bottom bar having labeled textbox'es. Which I temporally fixed by moving “PoEURL It!” button to Tools menu, but still it can cause problem for other languages in future.

Don't remember the exact numbers, but best practice for making localizable UI labels, is to add 50% or 75% of space to UI element. So, when you fit some English label into 100px, it should have width at least 150px or 175px to allow some space for translated label.

**Comment by SpaceOgre** [comment]
I like icons for some things as they take up less space and can make the UI look better, but in this case I'm not sure we can come up with good icons for "Level" and "Used". Not without confusing a lot of users at least.

The best route would be to go for the automatic layout, but that is also the most amount of work.

**Comment by l0g0sys** [comment]
Hmm.. something like this for level? :)) http://www.vectorstock.com/royalty-free-vector/level-icon-vector-741047

**Comment by l0g0sys** [comment]
And points used something like this:
https://www.google.com/search?q=icon+points+used&tbm=isch&imgil=HKHSNG4WXUP8wM%253A%253BP5akRPSJHghwUM%253Bhttp%25253A%25252F%25252Fplanetside.wikia.com%25252Fwiki%25252FCertification_Points&source=iu&pf=m&fir=HKHSNG4WXUP8wM%253A%252CP5akRPSJHghwUM%252C_&biw=1680&bih=913&usg=__n3rvVtAgTpJfnBu9SD9LuYdiWCs%3D&ved=0CCsQyjc&ei=JMWLVa6ADYKksAH9lKr4Bg#imgrc=HKHSNG4WXUP8wM%253A%3BP5akRPSJHghwUM%3Bhttp%253A%252F%252Fvignette3.wikia.nocookie.net%252Fplanetside2%252Fimages%252F0%252F0b%252FIcon_resource_certpoints_128.png%252Frevision%252Flatest%253Fcb%253D20121030221606%3Bhttp%253A%252F%252Fplanetside.wikia.com%252Fwiki%252FCertification_Points%3B128%3B128&usg=__n3rvVtAgTpJfnBu9SD9LuYdiWCs%3D

circle with inward arrow

**Comment by Ttxman** [comment]
I'm not sure icons are right way to do it. If we really want the touch screen support, then hover and tooltips are out of question. And there are no widely used icons for "level" nad "used" that everyone knows.

**Comment by EmmittJ** [comment]
A plus sign or up arrow are pretty good indicators of level up. Most games
us some version of those symbols. Used points however is a bit harder. We
could just rearrange the top bar there and see where that goes.

**Comment by EmmittJ** [comment]
This has been solved by simply removing the text and adding it to a hover display
