### ISSUE TITLE
Attributes tab localization

### ISSUE THREAD

**Issue by l0g0sys** [EmmittJ/PoESkillTree#130]
Attributes tab localization with Passive, Items, Total lists.
Custom groups.txt should be taken into account (no localization occurs when used).
Default static groups should be localized and some terminology consistency put in place.
  - "BaseStat" doesn't make much sense, while https://www.pathofexile.com/game refers to them as "core attributes"
  - "Crit" should be renamed to something like "Critical Strike"
  - "OFFHAND", "HELM" etc. should use correct case like "Off-Hand", "Helm", etc.
  - and maybe more...

**Comment by SpaceOgre** [comment]
Have dome some work on this: 40b7d9c5f31a976156f324cb539be6db7e234af8
