### ISSUE TITLE
Open Source Lincense Type

### ISSUE THREAD

**Issue by EmmittJ** [EmmittJ/PoESkillTree#135]
We should probably pick a license type. We don't have one which makes it hard to enforce completely open sourcing the code for anyone wanting to make chsnges.

This is more for user protection to keep the tool open sourced as much as possible. 

I guess I am asking which license type you guys would like? I think @MLanghof used MIT when designing his portion of the tree, but what do the rest of your think? @l0g0sys @SpaceOgre

**Comment by l0g0sys** [comment]
MIT is the least restrictive, so i vote for MIT.

**Comment by EmmittJ** [comment]
That is my vote as well.

**Comment by MLanghof** [comment]
To be clear, I used code from someone else and that code is under MIT license.
But yeah, MIT sounds good.

**Comment by EmmittJ** [comment]
Ah ok! I remember you had mentioned something about it but didn't remember
the exact scenario

**Comment by SpaceOgre** [comment]
Yeah, MIT sounds good. The less restrictive we are the better in this case
I think.

**Comment by Ttxman** [comment]
one more vote for MIT
