### ISSUE TITLE
Progression support for builds

### ISSUE THREAD

**Issue by SpaceOgre** [EmmittJ/PoESkillTree#14]
Many build guides use a level progression, so I think it would be nice if we could some how add this to a build. Something like this:

**Saved Builds**
* Build1
  - lvl1-20
  - lvl21-40
* Build2

Just a fast concept :)

**Comment by l0g0sys** [comment]
This could be done by adding TextBox named "Build Group" to Build Information dialog, where you can just type whatever you want. The Saved Builds list would somehow just group all builds with same "Build Group" text. So click one build type "Group A", copy/paste it do second build and now you have 2 builds grouped :) But no idea which component could be used to render those groups to be expandable/collapsible.

**Comment by SpaceOgre** [comment]
I think we can make use of the build filter for this. If we add a group parameter then we can just search there as well or add another box for it. But the question is if we need this now that we have the filter? You can just name your build something like this: AwsomeFailBuild - Part1, AwsomeFailBuild - Part2 etc and then just enter AwsomeFailBuild in the filter box and you are done.
