### ISSUE TITLE
Make Skill tree optimizer to ignore (not select) certain highlighted nodes

### ISSUE THREAD

**Issue by l0g0sys** [EmmittJ/PoESkillTree#145]
Interesting idea at forums :)

https://www.pathofexile.com/forum/view-thread/996805/page/22#p10858775
>Do you think it would be possible to add the option to ignore selected nodes (maybe with middle mouse button) , so if i never want the automatic planner to pick certain nodes then it would try to find another way or if there is no way then it would give an error message?

Something like tri-state node highlightning? Non-highlighted, highlighted to be selected, highlighted to not be selected (different outline color/shape?).
And optimizer would be forced to not pick "don't select" nodes.

**Comment by brather1ng** [comment]
Sounds like it could be useful. 
It might even be pretty easy to implement on the optimizer side (if just changing the scoring function to give bad scores when ignored nodes are included is enough for acceptable results).

For the node highlighting, I have absolutely no idea what is possible, but something like in the screenshot should look intuitive enough.
![crossed](https://cloud.githubusercontent.com/assets/7596346/8376193/9034026e-1c04-11e5-89d4-d267bee844ef.png)

**Comment by brather1ng** [comment]
I have implementend this now locally. Both the optimizer and the GetShortestPath-thing don't select nodes you have middle-clicked. 
Should I make a new branch for it or is it ok to add it to my existing pull request?
![implementation](https://cloud.githubusercontent.com/assets/7596346/8392083/ceb2a50c-1cdd-11e5-8773-124c99d6c241.png)

**Comment by MLanghof** [comment]
Well, this definitely puts more emphasis on handling unconnected graphs correctly. We need appropriate error messages since this couldn't happen before (although I did make a unit test that would check for it).

**Comment by brather1ng** [comment]
Yeah, I somewhat handled that in my code.
Pushed my implementation as a branch to my fork now, see c40e9d623cde03534dae87a57e0aa4c1020db397
Going to open a pull request for it now hoping it doesn't conflict too much with my other pull request :)

**Comment by MLanghof** [comment]
Makes me realize again that the Surface has no good way to MMB, so can't try it out right now.

Just out of curiosity, where in Germany are you from?

**Comment by brather1ng** [comment]
Didn't think about MMB being accesible or not, kinda just copied the suggestion. If there at some point will be proper touch support for this program the key for this should probably be changed.

To your curiosity: I'm from Bremerhaven, going to university in Bremen.

**Comment by MLanghof** [comment]
Yeah, using MMB is fine, there's lots of things that rely on it. It's just a shortcoming of most touch interfaces, but we would need extra support for that anyway (#79).

**Comment by EmmittJ** [comment]
The MMB is probably not the best key to use. A modifier to the right click
key would be a little better. I am not a fan of the MMB as a key.

**Comment by brather1ng** [comment]
Does shift+right click sound better?

**Comment by EmmittJ** [comment]
Honestly I would like that better. It also fits with the button choice a
lot better since it already highlights

**Comment by brather1ng** [comment]
Changed it.
Also what do you think about removing the right-click-highlight from a node when shift+right-click-highlighting that node and vice-versa? It doesn't break anything having both highlights on one node but it doesn't make much sense either.

**Comment by EmmittJ** [comment]
I really like that idea. No reason to have them both on the node and it
makes sense that one would remove the other :)

**Comment by MLanghof** [comment]
Note that this actually makes a lot of sense for the *other* ways of highlighting nodes: Search and attribute highlight ("Yes, I want crit, but not this cluster"). I'd say you should still draw both highlights (as opposed to how it's handled now, cross should be over the circle), but that's up for debate.

In my eyes it's unproblematic to keep the current bitflagging system (which technically has a state for highlight from rightclick + disallow), no need for a tri-state. It should just be prevented from actually letting the user produce the nonsensical situation.

**Comment by brather1ng** [comment]
Yes, I only meant it specially for the RMB-highlighting of nodes.
I don't know what you mean. My code atm draws all thats set in HighlightState with the cross on top (it just doesn't draw a circle if *only* Crossed is in HighlightState).

I added Crossed as another flag in HighlightState. As you said all combinations make sense, except FromNode together with Crossed. I also just pushed a change to not allow this combination, but that happens in SkillTree and doesn't use a tri-state.

**Comment by MLanghof** [comment]
Oh right, my bad. I glanced over and didn't realize how inequality works in that case.

**Comment by l0g0sys** [comment]
Internal highlight state handling doesn't matter, but if we want at some point support touch events, i think tri-state or just visual simulation of tri-state will be better, e.g. not hightlighted --(right-click/long tap)--> hightlighted for seletion --(right-click/long tap)--> hightlighted for exclusion --(right-click/long tap)--> not hightlighted, etc. Ofc. shift+right-click can stay, as shortcut for directly highlighting for exclusion, but same state should be accessable using regular right-click.

I've noticed some debugging code as well, don't have to comment it out. Just use #if DEBUG/#end if prepocessor directives to compile code only in Debug release.

**Comment by brather1ng** [comment]
I've changed that, also shift+RMB cycles through the tri-state the other way around now. So shift+RMB is the counterpart to RMB, feels the most intuitive I think. This way you can go from each state of the simulated tri-state to each of the other two with one click (on non-touch at least).

With the debugging code you probably mean my other pull request. I added debug preprocessor directives for any debugging code now, definitely sounds useful.
However the commented out stuff I think you thought of, is commented out because it spams the console and is a significant slowdown.

**Comment by l0g0sys** [comment]
Tested. Works. Done.
