### ISSUE TITLE
Jewel Highlighting

### ISSUE THREAD

**Issue by EmmittJ** [EmmittJ/PoESkillTree#151]
What do you guys think of something like this: 
![Image of Highlight] (http://i.imgur.com/VFJsbRr.png)

@SpaceOgre @l0g0sys @MLanghof @Ttxman @brather1ng

**Comment by MLanghof** [comment]
Looks good, I guess?

**Comment by EmmittJ** [comment]
Well should they be different colors or the same? Etc.

**Comment by brather1ng** [comment]
Looks good imo.

I don't think different colors would be of much use. When showing all three circles it is obvious which is which range.
If it will be possible to socket jewels at some point, the one circle that is shown is obvious from the jewel description.

Maybe a bit wider like the highlighting ring width if that is not too much.

**Comment by EmmittJ** [comment]
I can show you what is looks like, but I am not much of a fan. Also, we have to be careful how thick we make it because the rings do matter if they are within nodes. I just did it with half the width of highlighting which is double the current. 
![Image] (http://i.imgur.com/rqIWKDQ.png)

**Comment by brather1ng** [comment]
Hm, I guess the first one is alright then if it doesn't break by zooming out.

**Comment by EmmittJ** [comment]
I like it a bit thicker, but you do have to hover over the node in order to keep it highlighted. Should that be changed?

**Comment by SpaceOgre** [comment]
Looks good. I think the current thickness is good, and if it is a bit to wide for show the edge correct I think it could be offset by using a smaller radius/diameter. So instead of 800 for small then 798 or something, but I'm not completely sure how the line thickness is drawn but I would guess half on each side. 

Took a look at the code on the branch and it looks very good to.

**Comment by SpaceOgre** [comment]
An with current I meant the second screenshoots :)

**Comment by brather1ng** [comment]
I think it is ok to only highlight if you keep hovering the node.
Else one would need to think of a proper way to cancel the highlight and the way http://poedb.tw/us/passive-skill-tree/ does it for example is annoying in my opinion.

**Comment by EmmittJ** [comment]
Alright sweet. I will go ahead and merge with master.

**Comment by SpaceOgre** [comment]
Did a small fix to account for pen thickness when drawing the circles.

**Comment by EmmittJ** [comment]
Sweet

**Comment by EmmittJ** [comment]
Sweet! Just made a new bug report for jewels btw
