### ISSUE TITLE
Jewel Socket hover Skill tree moves

### ISSUE THREAD

**Issue by EmmittJ** [EmmittJ/PoESkillTree#158]
When hovering over sockets near the edge of the skill tree background (near Resolute Technique or bottom right socket over in ranger tree) the entire tree shifts right/up respectively. 

This might be because we are adding extra height/width to the background so it has to adjust

**Comment by SpaceOgre** [comment]
I have pushed a fix: bd6a7637f4

Not sure this is the best way, as it might break with a new tree, but it should work for now. Would be good if someone checked before next release so I didn't break anything with this.

**Comment by EmmittJ** [comment]
I think that could work. I had just thought about cutting off the jewels
highlight range by excluding the extra space from the eclipse, but I am on
my phone currently.

**Comment by SpaceOgre** [comment]
Yeah I though about that too but I did not find a good way to do it. I'm sure there is one I just could not find it :)

**Comment by EmmittJ** [comment]
This solution seems to work correctly. We may have to change the padding in the future but for now this can be closed :)
