### ISSUE TITLE
Portable Version PersistantData.xml in wrong location

### ISSUE THREAD

**Issue by Kabushiki** [EmmittJ/PoESkillTree#161]
It's saved to AppData (Roaming) instead of the portable folder.

**Comment by l0g0sys** [comment]
Cannot reproduced it.

Make sure you are launching application from its portable folder and that there is also Portable.ini file.

**Comment by EmmittJ** [comment]
It might be the .zip that is causing the problem

**Comment by EmmittJ** [comment]
Yep, the .zip file isn't portable as it wants to write to the AppData path

**Comment by l0g0sys** [comment]
I think it would be better to remove .zip from release assets. The whole point of making installer was to avoid security issues caused by extracting from blocked .zip.

**Comment by EmmittJ** [comment]
Alright will do
