### ISSUE TITLE
How to merge upstream with submodules

### ISSUE THREAD

**Issue by l0g0sys** [EmmittJ/PoESkillTree#164]
So how do i merge upstream with those submodules into my repo?
All i had to do before was git fetch upstream and git merge upstream/master (upstream is remote repo).

**Comment by SpaceOgre** [comment]
I believe you can do as before, as the submodules have their own git config. But I'm not 100% sure though.

**Comment by l0g0sys** [comment]
Nah, i did it that way and submodules were not fetched or merged.
VS barks that those projects are unavailable.

**Comment by EmmittJ** [comment]
`git submodule update --recursive`

That should work

**Comment by EmmittJ** [comment]
You may have to `git submodules init --recursive` , but I think the first
is correct

**Comment by l0g0sys** [comment]
That update did nothing. Guess you have to initialize them first.

**Comment by EmmittJ** [comment]
Sorry I fixed the command, which you probably didn't see

`git submodules update --init --recursive`

**Comment by l0g0sys** [comment]
Ok, looks like it's solved now. Exact steps are:
```
repo-root> git submodule init
repo-root> git submodule update
```

**Comment by EmmittJ** [comment]
Oh I was adding an s >.> sorry about that

**Comment by l0g0sys** [comment]
Now what with this error? Cannot build solution.
```
Error	1	Metadata file 'E:\GitRepos\PoESkillTree\RangeTree\RangeTree\bin\Debug\RangeTree.dll' could not be found	E:\GitRepos\PoESkillTree\WPFSKillTree\CSC	WPFSKillTree
```
How the hack did you that release?! :))

**Comment by EmmittJ** [comment]
Unload all the project and load & build:
Range tree
Wpf range tree controls
Skilltree
Unit tests
And the last one lol I forgot

Also there seems to bed problem with the range tree stuff that it doesn't
like to be built on debug x86 so I had to modify the project file to
release

(Sub modules are a pain in the ass)

**Comment by l0g0sys** [comment]
Yeah, now i see it in configuration manager. Those 2 projects have wrong platform configuration mapping.

**Comment by EmmittJ** [comment]
Yep so I changed it on my end.

**Comment by l0g0sys** [comment]
I'm gonna just fix RangeTree not being built at all in Debug/Release configurations.
The platform configuration fix requires changes in submodules and i'm not gonna deal with that.
Even couldn't Undo changes in those submodules in VS (it doesn't like that concept as well :), had to use git CLI to do hard git reset.

**Comment by EmmittJ** [comment]
Alright, sounds good. While you are here is there a way to make it so persistent data isn't overwritten? This is one of the only files I don't think should be copied over.

**Comment by EmmittJ** [comment]
Alright, sounds good. While you are here is there a way to make it so persistent data isn't overwritten? This is one of the only files I don't think should be copied over.

**Comment by l0g0sys** [comment]
Yes there is and it's already setup that way.
```
From release.iss:
...
Source: "{#BuildOutputDir}\PersistentData.xml"; DestDir: "{app}"; Check: CheckPortableMode; AfterInstall: SetLanguage; Flags: ignoreversion onlyifdoesntexist uninsneveruninstall
```
**onlyifdoesntexist** flag means that file is created only if it doesn't exist yet.

**Comment by EmmittJ** [comment]
Ah, alright sweet. There were some people saying it was overwriting, but I
don't think they understood that the builds went somewhere else.
