### ISSUE TITLE
Generated skill tree link is not working

### ISSUE THREAD

**Issue by tastychicken** [EmmittJ/PoESkillTree#168]
I noticed this issue when I downloaded the application a day ago. The generated skill tree links are not valid, you get the error message "The build you are trying to load is using an old version of the passive tree and will not work".

I also noticed ZiggyD having the issue live on his stream.

Could it be related to the small balance patches of 2.0.0?

Example link for a build I'm working on:
http://www.pathofexile.com/passive-skill-tree/AAAAAgIAm40ILu2DGY4AXtN-fXXvev667g7nCrvj_MVW-gqbxKINjd1GfyuXBtwVW6-HdmOnMHwZigX5p9ROKiF2kArjnxGBjX3I3MM6oaT-yEz_hs5KfSP2wUkki5u14dtDMcEzTZL-HQ-rX7CExY1-2sEWv8pKt7Z07QMeJpVvnnXLBS0fQWHinKSDCfGz6mK-pwYjVUuHE0tXZU21SIw2dwfA47028-pHfioLcFKJ03DVKjhtbDY9napsjGKsr-tRTKxHfVsqTUfiIuKkObCrxIKK8OlGZ6CbJjIBshnPenrvqvioosHY

**Comment by brather1ng** [comment]
This should be already fixed as it is the same as #159. Don't know when the next release will be though.

They changed the class code part of the skill tree.
To fix it manually as long as it isn't in a release, replace the `AAAAAgIA` with `AAAAAwIA` in the link (same for other classes, change the `g` to a `w`).
For your example it would become
http://www.pathofexile.com/passive-skill-tree/AAAAAwIAm40ILu2DGY4AXtN-fXXvev667g7nCrvj_MVW-gqbxKINjd1GfyuXBtwVW6-HdmOnMHwZigX5p9ROKiF2kArjnxGBjX3I3MM6oaT-yEz_hs5KfSP2wUkki5u14dtDMcEzTZL-HQ-rX7CExY1-2sEWv8pKt7Z07QMeJpVvnnXLBS0fQWHinKSDCfGz6mK-pwYjVUuHE0tXZU21SIw2dwfA47028-pHfioLcFKJ03DVKjhtbDY9napsjGKsr-tRTKxHfVsqTUfiIuKkObCrxIKK8OlGZ6CbJjIBshnPenrvqvioosHY

**Comment by tastychicken** [comment]
I totally missed that issue, sorry for reporting something that's been fixed!

Hopefully the next release will be soon.

Thank you for the advice, I'll keep that in mind!

**Comment by MLanghof** [comment]
Is there any problem with releasing again to fix this? It's a major nuisance for sharing the tree, and GGG actually correctly changed the version number of their product to 2.0 when changing the API :P

**Comment by SpaceOgre** [comment]
Don't see why not, we have a bunch of big fixes in place so a new release is not a bad idea.

**Comment by EmmittJ** [comment]
Yep I was thinking of deploying today if that is OK with everyone?

**Comment by EmmittJ** [comment]
Fixed, closing :)
