### ISSUE TITLE
URL Shortner Gone

### ISSUE THREAD

**Issue by CalebKester** [EmmittJ/PoESkillTree#169]
I noticed that the new version removed poeurl.com.  I hope this is just temporary as you wait for the skill trees to get in sync with all of the sites.

I use this feature all of the time when sharing my builds with my guild in google hangouts. If you're dropping poeurl.com are there alternative shortner sites you could implement?

Keep up the amazing tool!

**Comment by l0g0sys** [comment]
It was not removed, just moved from main window to Tools menu.
