### ISSUE TITLE
Link representation of character class should be centralized to one place

### ISSUE THREAD

**Issue by SpaceOgre** [EmmittJ/PoESkillTree#170]
In MainWindow.xml.cs we have a method to swap between classes, the problem is that it is using hard coded strings for the start of the build link. Instead we should create a method that calculates that part and use it both there and in SaveToUrl. So move part of the SaveToUrl method to a new one and use that in MainWindow.xml.cs when changing class.

**Comment by SpaceOgre** [comment]
This should also be applied to the default tree for the build class

**Comment by EmmittJ** [comment]
Actually you could modify the saveToUrl function to accept a class you want
a url for. You can't really remove the class calculation from that function
since it has to be converted to base64 all at once.

**Comment by SpaceOgre** [comment]
Yeah it is only the last line in SaveToUrl that won't be moved :)

**Comment by EmmittJ** [comment]
Oh, I see what you are saying :) I like the idea! Makes it simple for the
future

**Comment by SpaceOgre** [comment]
This is done.
