### ISSUE TITLE
Should we warn when loading an old build? 

### ISSUE THREAD

**Issue by SpaceOgre** [EmmittJ/PoESkillTree#171]
Just like pathofexile.com does. We can still try and load it but a warning might be good.

**Comment by EmmittJ** [comment]
Probably a good idea :) although might get annoying if you are flipping through builds in your saved list

**Comment by SpaceOgre** [comment]
True, we could add a checkbox in the popup with the text: don't warn me about old trees. This could also be added to the menu. Talking about the menu, it is getting more and more functions now so I need to go over it and add some submenus and dividers.

**Comment by EmmittJ** [comment]
I was just thinking about that. We also might want to look into a proper
settings menu. It is getting very crowded in the tools tab

**Comment by SpaceOgre** [comment]
How does the Localization work here? Can I just add a new ```<l:Catalog Message="_Path of Exile Website" />``` and then build and it will be added to messages.pot or do I need to add it manually?

**Comment by EmmittJ** [comment]
All messages should be automatically added, although I haven't done any UI
work, but I do see the messages getting auto changed when I rebuild the
project for releases

**Comment by l0g0sys** [comment]
Don't think we need "Don't warn me about old trees" option.

Either we won't load old trees at all and show error message on attempt to load one, or we try to load ANY tree and validate it for continuity with an error message on failure.
