### ISSUE TITLE
Highlighting by attribute also highlights other attributes containing the same string

### ISSUE THREAD

**Issue by brather1ng** [EmmittJ/PoESkillTree#173]
If you highlight the nodes for an attribute by right-clicking it, other attributes also get highlighted if they contain the same wording (try #% increased cast speed for example: minion cast speed, cast speed for curses and cast speed by totems get highlighted too).

Not really a big issue, but might be confusing if you are looking for an overview.

~~Adding `^` and `$` around the regex might already be enough to fix it.~~
Edit: nope, not enough

**Comment by EmmittJ** [comment]
Maybe try it out? I am not able to look into it for a bit

**Comment by brather1ng** [comment]
Just tried it, it is not enough.
Can't look into it more now, might have time tomorrow.

**Comment by EmmittJ** [comment]
Alright, I will look into later tonight as well
