### ISSUE TITLE
Remember window position and size (and fullscreen state)

### ISSUE THREAD

**Issue by Tvangeste** [EmmittJ/PoESkillTree#174]
It would be nice for the PoESkillTree planner to remember its latest window size and position, as well as fullscreen state.

Otherwise, user have to rearrange the window every time he/she starts the planner, over and over again.

Me, I would be happy if the tool could at least remember the fullscreen state. :)

**Comment by SpaceOgre** [comment]
Yes this would be nice.

Implementation tips: http://stackoverflow.com/questions/847752/net-wpf-remember-window-size-between-sessions
