### ISSUE TITLE
Import item data from clipboard

### ISSUE THREAD

**Issue by EnderWiggin** [EmmittJ/PoESkillTree#180]
Currently to import item data for character you need to save file and then select it in program. Can you make it so program will take data from clipboard? Or add a field where you can paste this data and import from there. This will significantly simplify item import process.

**Comment by EmmittJ** [comment]
If you right click a build expand character info there should be a spot,
unless it has moved.

**Comment by SpaceOgre** [comment]
Right click a build -> In the popup expand "Character Information" and then paste the item data in the input with the appropriate name "Items Data".

**Comment by brather1ng** [comment]
But you can't import items from that input field, or am I missing something?
For me that input field simply gets ignored.

**Comment by l0g0sys** [comment]
Well, it's not really an import. You just edit data in saved build. Then 
you have to load it, to get data updated in current build.

**Comment by brather1ng** [comment]
So you need to first import items through a file and then you can edit it through that (updated after reloading the build)?
I think what @EnderWiggin meant was that you don't have to go through the import from file step first.

**Comment by l0g0sys** [comment]
No. You just save build, then paste item data into that saved build and 
load it.

**Comment by SpaceOgre** [comment]
This^
I guess we should load/reload the items straight away if that is changed, not just after build load.

**Comment by brather1ng** [comment]
Lol, sry. I only tried restarting the program, which is not enough, and not reloading the build.
But yes, loading the items straight away is probably the best way. If you hadn't told me, I would've thought it doesn't work at all.

**Comment by l0g0sys** [comment]
To be honest, i was thinking about complete refactoring of build API and maybe their backend storage. Current state is a mess.

You don't know which build you are editing and thus risking that you will overwrite something you didn't want to. If you use "Skill tree comparison" option, it gets even more messy.

Not to mention that small error in PersistentData.xml can cause loss of all builds.

**Comment by SpaceOgre** [comment]
Yeah, a refactoring is a good idea since more and more stuff have been added it is not ideal to keep it all in PersistentData.xml.

**Comment by EmmittJ** [comment]
I am pretty sure there is a lot of refactoring that is needed. Honestly for builds, I think doing a 'file' system would be very nice. This way if one build is messed up the entire lot of them isn't. This would also allow for build folders meaning we could do something like #14

**Comment by l0g0sys** [comment]
Yeah, i thought at first too, that it would be best way to do it in "per-build file" way.
But then, there would be other issues using this system:

1. Naming: Build name would have to be separate information from file name. Unless build name would be more strict about allowed characters to make 1:1 build name to file name mapping. And question is what role subfolders would be playing in build naming.
2. Sorting: There wouldn't be any manual sorting, maybe just automatic sorting based on name or creation/modification time. Using some toggle buttons.
3. Filtering/Searching: This would require to traverse folder structures and parse each build file to filter based on character class or search in notes. Unless whole structure of build files would be read on launch and kept in memory during runtime.

**Comment by EmmittJ** [comment]
Maybe we start a new issue on this? As this is for importing clipboard data
lol

**Comment by l0g0sys** [comment]
Guess so :)

**Comment by SpaceOgre** [comment]
Wait for #192 before doing this.
