### ISSUE TITLE
Highlight similar skill nodes feature

### ISSUE THREAD

**Issue by brather1ng** [EmmittJ/PoESkillTree#183]
Would work basically the same way as the feature of the official skill tree (https://www.pathofexile.com/passive-skill-tree/, checkbox in the bottom left): all nodes having (or containing) the same set of attributes as the hovered node get highlighted.
Maybe not as a checkbox, but on key press. For example shift + hover over a skill node highlights similar skill nodes.

Do you guys think this would be useful?

**Comment by SpaceOgre** [comment]
Yeah it might be useful, but the way it is implemented in the official tree is to strict. If I hover on 10% increased fire damage then Fire Walker will not be highlighted.

**Comment by brather1ng** [comment]
The official tree only highlights other nodes with the same name, so yeah, that is to strict.
The question is, do we want to highlight other nodes that have *all* the attributes (or more) the hovered node has or nodes that have at least *one* of the attributes.

**Comment by EmmittJ** [comment]
I don't mean to be that guy but isn't that was the search bar is for?

**Comment by brather1ng** [comment]
Yes, this is basically just a (for the user much faster) alternative to the search bar.
That is why I asked for opinions :)

**Comment by EmmittJ** [comment]
It might be good, but what do you do for double+ stat nodes? Do you
highlight everything that contains all of the stats of nodes that contain
at least one?

**Comment by brather1ng** [comment]
Do you mean the same thing I wrote above?
>The question is, do we want to highlight other nodes that have all the attributes (or more) the hovered node has or nodes that have at least one of the attributes.

If yes, well, I don't know. We could test both and take what feels better.

**Comment by EmmittJ** [comment]
Dammit, yes. I missed that email lol like you said we can try it out and go
from there
