### ISSUE TITLE
Portable version crashes behind a proxy.

### ISSUE THREAD

**Issue by Calabrel** [EmmittJ/PoESkillTree#187]
I have tried downloading https://github.com/EmmittJ/PoESkillTree/releases/download/2.2.1/PoESkillTree-TheAwakening-2.2.1.exe and running that to get the portable version.  I also tried downloading https://github.com/EmmittJ/PoESkillTree/archive/2.2.1.zip to run the portable version, both have produced the error log posted below.

Installing the full installation is not an option on this PC.

Here are the files I have on the system: http://i.imgur.com/sk9hgwx.jpg

When I run PoESkillTree.exe is as far as it gets: http://i.imgur.com/QsFOkcF.jpg

Here is the debug.txt:
The error time: 7/15/2015 8:07 AM Exception: System.Net.WebException: The remote server returned an error: (403) Forbidden. at System.Net.HttpWebRequest.GetResponse() at POESKillTree.SkillTreeFiles.SkillTree.CreateSkillTree(StartLoadingWindow start, UpdateLoadingWindow update, CloseLoadingWindow finish) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:line 609 at POESKillTree.Views.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 156 at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs) at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e) at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent) at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root) at MS.Internal.LoadedOrUnloadedOperation.DoWork() at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks() at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks() at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget) at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget) at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget) at System.Windows.Interop.HwndTarget.OnResize() at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam) at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by EmmittJ** [comment]
https://github.com/EmmittJ/PoESkillTree/archive/2.2.1.zip
Is the source code for the project, so unless you are building it, which
would cause problems because you need internet, then this wouldn't produce
anything.

As for the portable release in the .exe, please uninstall any old version
of the tree and delete any portable files you may have. Then rerun the
installer and select portable install, select your location and see if that
helps.

Both versions do not require an internet connection though.

**Comment by Calabrel** [comment]
I didn't have a previous version, only discovered this after the current version came out.  I can't run the .exe on this sytem, because it requires admin privileges to even be able to select the portable version.

I have, however, on a different PC, ran the .exe, and selected the portable version.  I then ran the program from that directory, on that PC, and it worked.  I, then, copied the directory to a CD-R and brought the files to the problematic PC, copied the files to the hard drive and attempted to run PoESkillTree.exe (in the image I linked) and then it crashed.  I'll try again by selecting location, but in the meantime, what is meant by the crash image I linked when it says: "Downloading Skill tree assets"?  As that's where things seem to go wrong.

**Comment by Calabrel** [comment]
Okay, so, I think I may have figured how what's going on and I'm sorry to admit, I'm a bit of a moron.

I was running the executable from a roaming profile, and something was being stopped while it was trying to go to my local system.  I copied it to the local system and it ran.

Closing the issue.  Thanks for your help.
