### ISSUE TITLE
Crashes- tried on multiple pc s same result

### ISSUE THREAD

**Issue by tolgaist** [EmmittJ/PoESkillTree#189]
The error time: 21.07.2015 23:12
Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at POESKillTree.SkillTreeFiles.SkillTree.<set_Chartype>b__16(KeyValuePair`2 nd) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:line 484

**Comment by brather1ng** [comment]
Did you try the newest release? https://github.com/EmmittJ/PoESkillTree/releases/tag/2.2.2
Most likely is the same as #182 and #188.

**Comment by tolgaist** [comment]
https://drive.google.com/file/d/0B2BWKeD5Id_gbE9SWURLVzFqRzQ/view?usp=sharing

this version worked for me. but i selected the newest release on website already. interesting . ty anyway

**Comment by brather1ng** [comment]
So the newest release does not work?
If it doesn't work, could you post your full debug.txt output?

**Comment by EmmittJ** [comment]
The build in the google drive link is the exact same build as the one in the 2.2.2 pre-release. They both should work exactly the same.

**Comment by SpaceOgre** [comment]
No more input so I will close this.
