### ISSUE TITLE
Build Filtering - Builds list not returning

### ISSUE THREAD

**Issue by EmmittJ** [EmmittJ/PoESkillTree#191]
In all versions past 2.1.3 when a build is filtered the builds will not reappear after removing the filter. 

This was reported on the official forums. 

It might have something to do with the build list not pulling from the correct persistent data file? I am on my phone so can't look into this

**Comment by l0g0sys** [comment]
Nope, something with filtering itself.
```
private void SavedBuildFilterChanged()
{
...
    var className = selectedItem.Name.ToString();
...(loop)
        item.Visible = (className.Equals("All") || item.Class.Equals(className)) && ...
```
className is always empty string so following loop will never set Visible to true.

Guess that ComboBox should be populated dynamically same way *cbCharType* is.
Also locale-sensitive case operations are used instead of culture invariant versions.
