### ISSUE TITLE
Update progressbar says "Downloading skill tree assets"

### ISSUE THREAD

**Issue by brather1ng** [EmmittJ/PoESkillTree#194]
If you update the program with "Check for updates", the progress bar says "Downloading skill tree assets".

**Comment by EmmittJ** [comment]
Same for if you re-download item assests ;)

We use the same loading window for all download processes

**Comment by Ttxman** [comment]
shouldn't we change it into "Downloading POE skill tree assets" ?

**Comment by l0g0sys** [comment]
Nah, DownloadItemsWindow.xaml should be refactored to DownloadWindow with some property, where you can set text to display. That way it can be used to download anything. And when used with Updater, just set property to "Downloading installation package" or something, while when being used with SkillTree, property will be set to it's current text "Downloading skill tree assets".
