### ISSUE TITLE
Save Equipment

### ISSUE THREAD

**Issue by SpaceOgre** [EmmittJ/PoESkillTree#199]
Atm we only save items added to a character from "Download & Import Items", any item changes done from the Equipment tab is not save to the character.

As I see it we have two options:
1. Save the equipment instead of item json string, as a list of serialized items.
2. Convert the equipment to json string when saving

**Comment by brather1ng** [comment]
I'd say the optimal way would be to have crafting/changing items in the equipment tab and importing them through the website completely interchangeable. So they would be stored in the same format and place as ItemData (which might need to be changed then, I don't know if that json format makes sense to be generated by us).

**Comment by Ttxman** [comment]
Crafted items have same json format as items imported from web. And each item have original JSON string and parsed JSON data  are accessible as property.

Equipment slot is just a json field, there shouldn't be problem to add it while while saving.
