### ISSUE TITLE
Affix List needs updated

### ISSUE THREAD

**Issue by EmmittJ** [EmmittJ/PoESkillTree#200]
@Ttxman I was wondering if you could either share your scraping script or run it and update affixlist.xml for the new mods.

**Comment by Ttxman** [comment]
I'll try to look into it today or tomorrow. I really don't have any spare time lately :/ (I played awakening for less than 12 hours since launch).

**Comment by EmmittJ** [comment]
A no worries. I can write a parser for it (I think) it should be pretty
straight forward

**Comment by Ttxman** [comment]
I can share my code. Problem is that it is not as straightforward as it seems (and the format itself is messy). Some affxes have different names on items and web, some 1h and 2h Affixes are not cleanly marked. And signature master mods have to be added manually

To test the affix file I scrape trade forums for items and iteratively fix problems.

**Comment by EmmittJ** [comment]
Hmm, interesting. I thought about using poedb.tw/us/mod.php to generate
them. It is pretty straight forward and already classifies them properly

**Comment by Ttxman** [comment]
That should probably work, at least there are better categories and master mods are included .. I was parsing it from official website

**Comment by Ttxman** [comment]
I looked into new affixes and i will wrote parser for poedb.tw/us/mod.php. Format is much better than pathofexile.com and without 1h and 2h crit chance conflicts and it include quivers :). I should have free weekend so i try to add downloader for affix list into poeSkillTree.
