### ISSUE TITLE
Changing Theme/Accent not working

### ISSUE THREAD

**Issue by brather1ng** [EmmittJ/PoESkillTree#201]
Changing Theme or Accent does nothing, not while the program is running and not after restarting.
Might be Windows 10 related since I just upgraded.

**Comment by EmmittJ** [comment]
Everything is working except applying the theme to the current window,
which is nice. We just have to figure out why it won't apply the theme

**Comment by brather1ng** [comment]
Hm, for me it isn't applying any theme or accent at all.
If it's working for you and not for me, it's probably related to my setup.

**Comment by EmmittJ** [comment]
No, it doesn't apply the theme, but it does save the theme settings is what
I was trying to say.

**Comment by brather1ng** [comment]
Ah ok, misunderstood you then.
So the saving works, but the applying does not.

**Comment by EmmittJ** [comment]
Correct. I will take a look into it. Are you on the current build as well?
Or 2.2.1

**Comment by brather1ng** [comment]
I'm on the latest release, which should be identical to the current build.

**Comment by EmmittJ** [comment]
Alright, I will look into it

**Comment by EmmittJ** [comment]
I might be wrong here, but it looks like the ThemeManager for MahApps isn't actually doing its job. Maybe someone else can look into it and back me up on this. @SpaceOgre @l0g0sys

**Comment by SpaceOgre** [comment]
The MahApps version was changed recently, it could have something to do
with that. Either there is a problem with that version or the way a theme
is changed have changed. Might get some time to check it tomorrow.

**Comment by EmmittJ** [comment]
Alright, I can't tell exactly what is going on, but if you call change
theme then get the current theme it doesn't actually change the theme.
Also, for some reason mahapps doesn't throw any errors.

**Comment by EmmittJ** [comment]
Oh >.> it was force loading that theme. That makes sense

**Comment by SpaceOgre** [comment]
Yeah, seems like it. But it worked before, so I guess they changed how it worked. But it kinda makes sense as it is now.

**Comment by EmmittJ** [comment]
Yep, makes a lot of sense. Thanks for fixing that :)
