### ISSUE TITLE
Simple item filter editor

### ISSUE THREAD

**Issue by l0g0sys** [EmmittJ/PoESkillTree#202]
Some time ago i wanted to dig into XAML/UI stuff and ended up working on simple item filter editor.
Idea is to make it as simple as it can be, so people doesn't have to know anything about their syntax.
There is nice app Filteration on github, but when i showed it to my brother, he just laught at me. And tbh. i can't be bothered with it either, when i want to change just few visuals or hide some stuff.

Feel free to evaluate from my repo:
https://github.com/l0g0sys/PoESkillTree/releases/download/2.2.2/PoESkillTree-ItemFilter.zip
Made it portable so it won't overwrite anything, except item filters. Be careful, to not overwrite your existing ones using same name.

Filter management window (atm in View / Item Filter Editor, maybe it should be in Tools?):
![itemfiltermain](https://cloud.githubusercontent.com/assets/8587407/9410003/1d1fa5b2-481e-11e5-8a12-4fcdfcd19b2b.jpg)
Window where you create/edit/delete filters. They are stored in AppData.Folder("Filters") and generated into My Games\Path of Exile game folder once saved.

Filter editing window:
![itemfilteredit](https://cloud.githubusercontent.com/assets/8587407/9410157/f1e9d0e2-481e-11e5-89ad-4075dc436d6d.png)
This is simple. Keep checked what you want to see, uncheck what you don't. Disabled rules cannot be hidden due to either "security" reasons (to not make people hide high value stuff by mistake), or there is no meaning in hiding it atm. (Or it could produce wrong file once unchecked :-p)
Rules are grouped to some logical groups like Currency, Recipes (to highlight stuff which can be handed as recipe to verndor), Flask (nonunique), Gems, and few others i found useful atm.
Rules are hardcoded so they can be localized. Specially descriptions, where should be mentioned which items are controled by rule, pretty much copy & paste from Wiki of recipe description.

Color editing window:
![itemeditorcolors](https://cloud.githubusercontent.com/assets/8587407/9410417/5c3366ec-4820-11e5-838a-b3868e1ec528.png)
Set background, text and border color for rule, or whole group of rules. If you want to keep in-game color just leave color at Default.

Still some processing of data before filter file generation is needed.
And think some way to allow hiding of "white trash" and "blue trash", maybe even rares if there are people hiding those? So, you can hide white trash but still show whites for armourer scrap/whetstone recipes, etc.

**Comment by EmmittJ** [comment]
This is pretty damn cool! Seriously, super simple. I always edit mine in
notepad++ with an intellisense thing running
