### ISSUE TITLE
Life isn't calculated correctly

### ISSUE THREAD

**Issue by ukkoclap** [EmmittJ/PoESkillTree#205]
Life for my character is roughly 300 off. I tried resetting the tree and doing the tree from scratch and importing my gear, but it's not calculating it correctly.

http://imgur.com/lzmF1Wi,wF0cU5Q

**Comment by EmmittJ** [comment]
Probably the Oak Quest reward?

**Comment by ukkoclap** [comment]
I don't think that the +40 maximum life from oak result in a 300ish life difference? I tried adding 40 life to gear in the import file, but only gave me about 100ish more life than before.

**Comment by EmmittJ** [comment]
Well that would be a portion of the HP difference. Is there a jewel or two
in your tree giving you a bit more % HP?

I don't think that the +40 maximum life from oak result in a 300ish life
difference? I tried adding 40 life to gear in the import file, but only
gave me about 100ish more life than before.

—
Reply to this email directly or view it on GitHub
<https://github.com/EmmittJ/PoESkillTree/issues/205#issuecomment-137326913>.
