### ISSUE TITLE
How to See Builds Saved in Previous Version?

### ISSUE THREAD

**Issue by dsnvwlmnt** [EmmittJ/PoESkillTree#207]
I installed a newer version of PoESkillTree (2.2.2), but i can't figure out how to bring over all my saved builds from the previous version i was using (2.1.3).

I tried the most obvious thing, copying over PersistentData.xml into the install folder, but that didn't do anything.

There's no documentation anywhere for this program (all the "wiki" shows is a changelog), which makes it difficult to figure out simple things like this.

**Comment by EmmittJ** [comment]
In your AppData (Roaming) folder there should be a folder called
PoESkillTree - The Awakening copy the file into there :)

**Comment by l0g0sys** [comment]
But be prepared, that application might crash and not work properly.
Builds from 1.x game patch are not compatible with 2.0 game patch, same 
goes for our application.
