### ISSUE TITLE
Better comparison / Safer build save

### ISSUE THREAD

**Issue by restinpieces** [EmmittJ/PoESkillTree#209]
This happened to even before the skill comparison. But it got much worse with the comparison feature. I always override the wrong build.

When you compare  a build the one highlighted is not the one you change and when you click save it overrides the build you compare your changed build too.

My Suggestion would be to make checkboxes or radiobuttons to mark the compared builds and always highlight the build that is currently changed and would be saved.

A "Would you like to override %buildname% [Yes]" would also greatly reduce the likelihood of that failure.

**Comment by BlueManiac** [comment]
I agree, this could definitely be made better. Radiobuttons or a rightclick-menu with a compare option would probably be best.
The compared build could have a yellow highlighted border around itself to differ itself more compared to the selected build.

**Comment by l0g0sys** [comment]
This whole build management is lame and it should be rewritten to more standard model. See #192 .
If you have many builds you even don't have to use tree comparison feature to mess things up.
Standard document-like model should be made, where you have in File menu "New Build", "Save Build", "Save Build As" commands and they should work like in 99% of any editor-like application.

If you choose "New Build" it should simply create new build and you don't have to click all those Clear this, Clear that menu options.

If you choose "Save Build" it must save build to exatcly the one you loaded, regardless of some selection in list.

If you choose "Save Build As" and you type name of existing build, then you get asked if you want to overwrite existing one. If you type unique name, it gets just saved.

There must be always visible indicator of currently loaded/being edited build, for example in Window title bar. If you have 2 or more apps launched at same time, it must be easy to see which one has which build loaded.

There must be "dirty" status for new or loaded build. If you try to load or do anything which should replace current dirty build. It must warn you that there are unsaved changes and give you options to "Save Build" if it was loaded build or "Save Build As" if it was new - not yet saved build.

**Comment by EmmittJ** [comment]
This has been done by @SpaceOgre in the most recent version of the planner.
