### ISSUE TITLE
Updating from pre release to release via updater not possible

### ISSUE THREAD

**Issue by brather1ng** [EmmittJ/PoESkillTree#212]
If you have a pre release installed (e.g. latest 2.2.2 pre-release) and the release version is published (e.g. 2.2.2 release), the in-app-updater can't update to that because the installed version (pre-release) has the same version number as the new version.

This is not a big problem because you can just download and run the installer which doesn't even take a minute, but it's still an issue.

**Comment by l0g0sys** [comment]
It's not a problem at all. Because you cannot create 2 releases with 
same version number.
Pre-release is just flag on release, it doesn't play any role in 
versioning and you cannot even make 2 same tags in git.

**Comment by EmmittJ** [comment]
The problem is when you change it to release from pre-release and people
have already installed it

**Comment by l0g0sys** [comment]
If they have it already installed than there is no problem. There is no 
point doing update when nothing changes just flag was changed.

**Comment by EmmittJ** [comment]
Except new features can be added to a pre-release basically a current
working build of the source

**Comment by l0g0sys** [comment]
See? If you add new features, you cannot make it same version. You have 
to increase version number.

**Comment by l0g0sys** [comment]
There is even check in release script, which won't allow you to make 2 
releases with same version number/git tag.

**Comment by EmmittJ** [comment]
This is my bad. I should have incremented the version number instead of keeping it the same pre-release

**Comment by l0g0sys** [comment]
Yeah, you should be always able to track any release (regardless it 
being pre or regular) using git tag as unique identifier. Pre-release is 
just flag in githug release entity. I'm affraid that i cannot make it 
part of version comparison on any level (assembly version, app version).
