### ISSUE TITLE
 [Auto Tree Gen] Unarmed taking weapon nodes

### ISSUE THREAD

**Issue by EmmittJ** [EmmittJ/PoESkillTree#220]
if in settings you set your weapon as "unarmed" and tag with "attack" and say you want some pseudo fire damage, the program will put skills into things like "increased weapon elemental damage" and "increased fire damage with weapons", but "weapon" modifiers don't work for unarmed.

This was sent to me via reddit. I am just putting it up here.

**Comment by brather1ng** [comment]
At least for weapoe elemental damage it should work since `<Not><WeaponClass>Unarmed</WeaponClass></Not>` is included there. I'll hopefully get to test and fix it once I'm home.

**Comment by EmmittJ** [comment]
Yeah, I am not home to test this. There were a couple more about dual wield
crit and staff crit, but I thought the unarmed might actually be a bug. I
can't really look into it much though; I have finals >.>

**Comment by brather1ng** [comment]
You could throw all those "maybe bug" reports into a Gist or something. I don't have that much time atm, but I should be able to look into it in the next few days.

**Comment by EmmittJ** [comment]
http://pastebin.com/p3XNwxWs
