### ISSUE TITLE
Donations and you

### ISSUE THREAD

**Issue by EmmittJ** [EmmittJ/PoESkillTree#222]
Alright, I have had numerous requests to accept donations, and I would like everyone that has contributed to be able to take part in this. I am not exactly sure the best way of going about this, and I would like to hear your opinions on whether or not we should accept donations.
@SpaceOgre @Ttxman @l0g0sys @brather1ng @MLanghof

**Comment by SpaceOgre** [comment]
Donations are tricky, on one hand it can give people who can't/don't have time to contribute in code a chance to feel like they are. But on the other hand it can lead to people feeling they have to right to start demanding different features, faster releases etc. At least for my part it would feel better not to start accepting donations for this very reason.

**Comment by EmmittJ** [comment]
I actually hadn't really thought about that part. I was thinking more along the lines of splitting donations if we were to accept them. I can see how people would feel like they deserved a bit more if they were to give money though.

**Comment by SpaceOgre** [comment]
Well that is even trickier since it can lead to arguments and disputes among the code contributors if someone feels like they don't get enough, or that "why is he getting more than me?"

**Comment by EmmittJ** [comment]
Yeah, my first thought would be an equal share, but the time invested by everyone is very, very different and then it really wouldn't be fair.

**Comment by l0g0sys** [comment]
Think, i'm with @SpaceOgre on this issue.

Another issue is, that because this project is open source, it means 
anyone can contribute with any amount of work. It would be too much 
hassle to manage, who is going to get share and when? After 10 lines 
fix, or after 15 commits?

**Comment by EmmittJ** [comment]
I had these feelings as well, but I figured I would get some more opinions
on the matter. I have been pretty against donations from the beginning of
the take over, but I figured made others would like to at least get some
say

**Comment by SpaceOgre** [comment]
Definitely, it does not hurt to bring it up and discuss it since I know people ask for this and it is good to have an understanding about what the group think.

**Comment by brather1ng** [comment]
I'm on the same side as @SpaceOgre and @l0g0sys. Imo it's pretty much impossible to share the donations in a way that is fair for everyone in an open source project like this without offending contributors.

**Comment by EmmittJ** [comment]
Seems like we are all on the same page then :) I will continue to deny donations :)

**Comment by svnhddbst** [comment]
one option that you could consider, put up a list of "who's done what" and
if a person wants to donate to a specific person for what they've done,
then they would be able to, and there's no confusion of why they would want
to do so since it would be listed in plain text.
<https://www.avast.com/?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MLanghof** [comment]
Agreed with the statements so far. I think a good reply to donation requests would be to ask people to donate to a charity (or similar) of their choice instead. There's plenty of support needed everywhere, while we do seem to have the resources we need to work on these leisure projects.
