### ISSUE TITLE
Confirmation on "Untag all nodes"

### ISSUE THREAD

**Issue by teuneboon** [EmmittJ/PoESkillTree#223]
Pretty simple request, but I'd love it if "Untag all nodes" could have a "are you sure?" confirmation box. It's not like it happens every time, but I've missclicked it before and lost a tree to it. Don't make this your number one priority or something, but I was submitting another issue so I though I might as well submit this one too :D

**Comment by SpaceOgre** [comment]
Just a small thing I noticed: it would be good to use the Locale files and not hard code the text.

**Comment by EmmittJ** [comment]
I had forgotten to do so. It should be fixed

**Comment by teuneboon** [comment]
Well, that was quick, thanks

**Comment by EmmittJ** [comment]
Was easy and asked for a lot lol
