### ISSUE TITLE
Linux/others feature request

### ISSUE THREAD

**Issue by ccomly** [EmmittJ/PoESkillTree#226]
Would it be out of the question to compile this for linux/mac/others ?

couldn't get it running with Wine https://www.winehq.org/ , so either run it on windows through virtualbox or similar, or via team viewer to the host windows box (i play poe with steam in-home streaming to my linux laptop) 

i just figured since its open source, i dont know what kind of framework or libs ur using so i guess that could be an issue, or lack of demand.  Would be really nice to have it running natively on linux or atleast functional with wine.

Just a feature request :)

**Comment by EmmittJ** [comment]
Well, this is written in C# using the .net library, so native operation
using our current technologies isn't possible.

**Comment by ccomly** [comment]
all right thanks for the reply! ill keep trying with wine. I remember MONO was some kind of replacement for  .NET no? idk how compatible they are.

**Comment by EmmittJ** [comment]
> The easiest way to describe what Mono currently supports is:
Everything in .NET 4.5 except WPF, WWF, and with limited WCF and limited ASP.NET 4.5 async stack.

http://www.mono-project.com/docs/about-mono/compatibility/

This is kind of a problem since this is exactly what we use in the skill tree. This would require an entire re-write of the current project. I surely don't want to do that

**Comment by EmmittJ** [comment]
@brather1ng Is there any reason we updated to .net 4.5 other than async/await keywords? There is a library:  https://www.nuget.org/packages/Microsoft.Bcl.Async/ that adds these to .net 4.0

**Comment by brather1ng** [comment]
I think async/await is the only thing we use from .net 4.5. If that package you linked also supports Visual Studio 2015, I would not mind going back to 4.0.

Else we could hack together a not really maintained 4.0 version by just removing the features that use async/await.

@ccomly Have you tried Wines .net 4.5 support? https://appdb.winehq.org/objectManager.php?sClass=version&iId=25478

**Comment by ccomly** [comment]
i haven't tried that specific version with 4.5 will try it now.

**Comment by EmmittJ** [comment]
If that wine package doesn't work then I would like to go back to .net 4.0
since I have had many people message about Linux and 'work' support lol

**Comment by ccomly** [comment]
I tried a few versions, tried via regular wine / winetricks, crossover , playonlinux, after installing .net 4.5 i get the crashings

**Comment by ccomly** [comment]
Not a developer/coder but i always fancy open source. Some times i can even fix stuff myself!

**Comment by EmmittJ** [comment]
I am going to try and get this ready for release in an hour, but I don't
know if I will make it haha

**Comment by EmmittJ** [comment]
Could you please try this build? This hopefully will work in .net 4.0 
[PoESkillTree-Talisman.zip](https://github.com/EmmittJ/PoESkillTree/files/60370/PoESkillTree-Talisman.zip)

**Comment by ccomly** [comment]
i tried with wine-1.8-rc3
installed .net 4.0 with winetricks got alot further than before, i even saw a glimpse of the window before it crashed. attaching debug.log, if u want me to try it in mono i think i need a non .exe version.
[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/60580/debug.txt)

**Comment by EmmittJ** [comment]
>Make sure your .NET framework is patched. Microsoft released patches to .NET to allow Portable Class Libraries to properly find the appropriate runtime (KB2468871). If you are seeing the above exception (or something like it), it means you're missing the latest .NET framework patches.

http://stackoverflow.com/questions/23903657/could-not-load-file-or-assembly-system-version-2-0-5-0-in-net-4-mvc-4-applicat

It looks like the package you are using for .net 4.0 isn't updated

**Comment by EmmittJ** [comment]
Let me see if I can include a local copy into the application.

**Comment by EmmittJ** [comment]
[PoESkillTree-Talisman.zip](https://github.com/EmmittJ/PoESkillTree/files/60683/PoESkillTree-Talisman.zip)
This should solve that issue.

**Comment by htj** [comment]
FWIW: I tried building this on linux with mono and xbuild. Unfortunately mono does not have PresentationCore and PresentationFramework, so it doesn't build. Looking at 
http://www.go-mono.com/status/status.aspx?reference=4.0&profile=4.5&assembly=PresentationCore
It seems most of the stuff is actually there, with just a few bits missing (IOCommand in particular), but the planner doesn't seem to use those. It might be possible to trick the build system somehow, but my C#/Mono/MSBuild-foo is weak.

**Comment by EmmittJ** [comment]
Honestly, I would prefer to not change compilers. There is too many things that the .net framework has that mono doesn't. There is already 2 libraries as you pointed out. 

I would like to get it running on Linux while using the .net 4.0 framework, which is possible as we have done it before.

**Comment by htj** [comment]
Tried the tarball, but crashed. I Installed dotnet40 in 32 bit with winetricks first, and had to install windbind as well.

[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/61635/debug.txt)

**Comment by htj** [comment]
Oh, I tried installing dotnet20 (as the debug output compains about missing system.core 2.0.5.0), but get the same error before and after.

**Comment by EmmittJ** [comment]
Is this with the updated zip?

**Comment by htj** [comment]
Yes. It haven't patched the system though as described above. Currently poking at it.

**Comment by EmmittJ** [comment]
Alright!

**Comment by htj** [comment]
I've tried both tarballs, and the 2.2.3 release, but cannot get any of them to work.

The dotnet45 installation in winetricks seem broken, so the 2.2.3 version fails very fast.

Both tarballs seem to get quite far in startup, but AFAICT produces the same error (System.Core, version 2.0.5.0 assembly missing). I also tried with dotnet20sp2, but it gives the same error.

**Comment by EmmittJ** [comment]
Hmm, not a computer to try and help resolve this issue, but it looks like
for some reason it isn't closing and parsing XML incorrectly

**Comment by EmmittJ** [comment]
I am not sure this is the correct solution, but I have added local copies of all the dll's. This should mean that all dependencies are within the application folder. Let's hope this will work. 
[PoESkillTree-Talisman-2.2.4.zip](https://github.com/EmmittJ/PoESkillTree/files/71320/PoESkillTree-Talisman-2.2.4.zip)

**Comment by htj** [comment]
Hi. Thanks for the attempt. I get the same error though:

The error time: 12/24/2015 12:58 AM
Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
File name: 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'
   at POESKillTree.Views.MainWindow.LoadBuildFromUrl()
   at POESKillTree.Views.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 225
...

This might be related to a bug in wine (30707) where it doesn't build the assemblies. The 2.0.5.0 seems to be the portable classes target.

I spend 2-3 hours recently trying three different wine versions, and different PoESkillTree builds (and .NET 4.0/4.5), but I get crashes no matter what.

**Comment by EmmittJ** [comment]
Wine shouldn't have to build any assemblies at all. They are all included within the build. 

Anyway I have looked into this error a lot and there is literally one solution. That solution is to install one of the update packages for .net 4 like I posted above. I will see if there is the same update for wine

**Comment by htj** [comment]
Running the 2.2.4 tarball in a clean wine (installed corefonts with winetricks). I get this on start:

fixme:mscoree:ConfigFileHandler_startElement Unknown element L"configSections" in state 1
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"runtime" in state 1
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"loadFromRemoteSources" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"assemblyBinding" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"dependentAssembly" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"assemblyIdentity" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"bindingRedirect" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"dependentAssembly" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"assemblyIdentity" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"bindingRedirect" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"dependentAssembly" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"assemblyIdentity" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"bindingRedirect" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"dependentAssembly" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"assemblyIdentity" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"bindingRedirect" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"dependentAssembly" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"assemblyIdentity" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"bindingRedirect" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"system.net" in state 1
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"defaultProxy" in state 3
fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.0" not implemented
fixme:mscoree:CLRMetaHost_GetRuntime Unrecognized version L"v4.0"

Unhandled Exception:
System.TypeInitializationException: An exception was thrown by the type initializer for POESKillTree.Views.App ---> System.TypeInitializationException: An exception was thrown by the type initializer for POESKillTree.SkillTreeFiles.SkillTree ---> System.InvalidProgramException: Invalid IL code in System.Windows.Media.Colors:get_RoyalBlue (): method body is empty.

  at POESKillTree.SkillTreeFiles.SkillTree..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at POESKillTree.Views.App..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at POESKillTree.SkillTreeFiles.Bootstrap.Run () [0x00000] in <filename unknown>:0 
  at POESKillTree.SkillTreeFiles.Bootstrap.Main (System.String[] arguments) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: An exception was thrown by the type initializer for POESKillTree.Views.App ---> System.TypeInitializationException: An exception was thrown by the type initializer for POESKillTree.SkillTreeFiles.SkillTree ---> System.InvalidProgramException: Invalid IL code in System.Windows.Media.Colors:get_RoyalBlue (): method body is empty.

  at POESKillTree.SkillTreeFiles.SkillTree..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at POESKillTree.Views.App..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at POESKillTree.SkillTreeFiles.Bootstrap.Run () [0x00000] in <filename unknown>:0 
  at POESKillTree.SkillTreeFiles.Bootstrap.Main (System.String[] arguments) [0x00000] in <filename unknown>:0 

No debug.txt

With respect to the update package for .net 4, I've tried to install that as well (after installing .net runtime), but it refuses to install with the error message: This update does not apply (and nothing else).

**Comment by EmmittJ** [comment]
I have no idea why it wouldn't be able to get colors >.>

**Comment by EmmittJ** [comment]
For some reason it doesn't look like WINE is able to parse through the app.config file.

**Comment by htj** [comment]
Same result with new tarball.

Is the dll with windows media included?

poeoffline@ativ:~/.wine32/drive_c/Program Files/PoESkillTree$ ls -1 System.Windows.*
System.Windows.Forms.dll
System.Windows.Interactivity.dll

**Comment by htj** [comment]
Also, there is no app.config file. Should there be?

**Comment by EmmittJ** [comment]
POESkillTree.exe.config should be what it compiles to.

**Comment by EmmittJ** [comment]
So, from the debug files, it looks like it cannot load the async library I am trying to use. LoadBuild is the first time the async keyword is used. I am really not sure why wine won't run since there isn't anything special about this system.

**Comment by imhid** [comment]
Been working on trying to get this to work in Linux for a while now and came across this. Just wanted to jump in and say I would be so incredibly grateful if you took the time to make this amazing too usable for us Linux users! Keep up the great job Emmitt! :)

**Comment by SpaceOgre** [comment]
I have hopes for .net 5: http://www.hanselman.com/blog/AnnouncingNET2015NETAsOpenSourceNETOnMacAndLinuxAndVisualStudioCommunity.aspx

The plan is for it to support Windows, Mac and Linux if that is the case I think that would be the best option going forward.

**Comment by EmmittJ** [comment]
Has anyone tried the new version of WINE? I have been told that the support for 4.5.2 has become much better.

**Comment by Eluinhost** [comment]
Just tried 'PoESkillTree-Ascendancy-2.2.9.exe' on wine 1.9.8 via PlayOnLinux.

Couldn't install dotnet45 on 64 bit so loaded it in my LoL drive instead, had to also install msvc100. Had to install winbind in the OS too. That made it 'start' at least with a black screen and this error: http://hastebin.com/iteqenuqef.avrasm

**Comment by kalktresor** [comment]
PoESkillTree-Ascendancy-2.2.10 runs just fine with wine-1.9.11 32bit (msvc100, mono28, dotnet45 installed)

**Comment by EmmittJ** [comment]
Thanks for the report!

**Comment by Eluinhost** [comment]
Can confirm wine 1.9.11-staging 32 bit drive with POL. Installed msxml via POL then ran `winetricks dotnet45` and then installed msvc100 and it works. Now to hoping POE works after this next patch! :D

**Comment by EmmittJ** [comment]
I will go ahead and close this then it looks like the tree is running fine :)

**Comment by LouisKottmann** [comment]
Would you guys mind giving more details on how you got it to work?

With the latest *PlayOnLinux* and *Wine 1.9.22*, on a fresh 32bit prefix, installing `msxml6`, then `PoESkillTree`, then `dotnet45` then `msvc100` I get:

```
Can't find custom attr constructor image: /home/baboon/.PlayOnLinux/wineprefix/poeskilltree/drive_c/PoESkillTree - Atlas of Worlds/PoESkillTree.exe mtoken: 0x0a000014
Unhandled loader error: 8, (null) PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (null)
* Assertion: should not be reached at loader.c:298

Stacktrace:


Native stacktrace:

	/usr/bin/cli() [0x49ff2f]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x11670) [0x7fbbf1354670]
	/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x9f) [0x7fbbf0fb17ef]
	/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fbbf0fb33ea]
	/usr/bin/cli() [0x630409]
	/usr/bin/cli() [0x63069c]
	/usr/bin/cli() [0x630833]
	/usr/bin/cli() [0x54357a]
	/usr/bin/cli(mono_class_from_typeref_checked+0x223) [0x524c63]
	/usr/bin/cli() [0x5234ad]
	/usr/bin/cli(mono_metadata_parse_mh_full+0x497) [0x5620b7]
	/usr/bin/cli() [0x433fd6]
	/usr/bin/cli() [0x500b39]
	/usr/bin/cli() [0x501fbd]
	/usr/bin/cli() [0x425db6]
	/usr/bin/cli() [0x426749]
	/usr/bin/cli(mono_runtime_invoke+0x3d) [0x5ac68d]
	/usr/bin/cli(mono_runtime_exec_main+0xbc) [0x5ae9cc]
	/usr/bin/cli(mono_main+0x1177) [0x476967]
	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7fbbf0f9c3f1]
	/usr/bin/cli(_start+0x29) [0x422e79]
```

```
Exception: System.Windows.Markup.XamlParseException: Set property 'System.Windows.UIElement.Visibility' threw an exception. ---> System.Runtime.InteropServices.COMException: Unknown authentication service.
```

**Comment by LouisKottmann** [comment]
I just got it to work by using the option "Emulate a virtual desktop" in POL --> Wine config
