### ISSUE TITLE
Skill tree application locks cursor 

### ISSUE THREAD

**Issue by FrankTheTank26** [EmmittJ/PoESkillTree#227]
Every major skill tree patch this program has the same issue. I download the program, unzip the whole thing, and try to run the application, but when I do the program opens with a locked mouse cursor. I have to ALT F4 the program and CTRL ALT Delete and cancel to use my mouse again.

For awakening, the skill tree worked about a week or so into the patch, but by that time it was too late for my reset characters. 

I use windows 7 professional. 
Thanks I hope I provided enough information. Just lmk if I need to add more. 
Thanks, 
Frank

**Comment by EmmittJ** [comment]
Do you have any anti-virus programs running?

**Comment by FrankTheTank26** [comment]
Yes, Comodo, and I checked to see if its blocking it. It does not appear to be blocked.

**Comment by EmmittJ** [comment]
Could you disable it, download the .zip,  unzip and run?

**Comment by FrankTheTank26** [comment]
It appears do have not made a difference, hmm.

**Comment by EmmittJ** [comment]
Is there a debug.txt file where the executable is located? Also, could you
take a screen shot of what is happening?

**Comment by FrankTheTank26** [comment]
Ok, I had to manually disable everything. I found one check I did not disable on Comodo. Now it works.. is there a way to get it to work with comodo?

**Comment by EmmittJ** [comment]
You will have to add it to whatever exception list is blocking the
application. I am not sure how exactly to do it, but googling how to add
something to an exception list should turn up some good results

**Comment by FrankTheTank26** [comment]
Thank you so much! I love this application so much! You have no idea how much I love this program. You're the best!

**Comment by EmmittJ** [comment]
Not a problem!

**Comment by l0g0sys** [comment]
One thing you should try, and maybe you won't have to configure any 
exception for PoESkillTree.
Before un-zipping archive, display file properties of zip archive and 
press Unblock at bottom. After that, unzip content of archive.
If you unzip blocked archive, all its content will become blocked as 
well and that might be reason why Comodo doesn't want to run it.

There is no way to make something work with anti-(virus/malware/X) 
software. Purpose of anti-X software is to block suspicious activity, 
and if there was way for application to tell anti-X program that stuff 
it's doing is not suspicious, then there would be no point in anti-X 
software at all. First thing "infection" would just have to do, would be 
telling anti-X software that everything it does is OK :)
