### ISSUE TITLE
Tree is off-center 

### ISSUE THREAD

**Issue by SpaceOgre** [EmmittJ/PoESkillTree#231]
The tree is more to the right and up than it should be, or the background is to big. I have done work with it before but I won't have access to my computer for a while.

![image](https://cloud.githubusercontent.com/assets/381657/11717946/c699436e-9f53-11e5-800b-2a18be8bacc8.png)

**Comment by EmmittJ** [comment]
I believe this party has to deal with the space added for jewels when we
draw the overlay. Should be an easy fix

**Comment by EmmittJ** [comment]
>    "max_x": 9373, 
    "max_y": 8346, 
    "min_x": -10604, 
    "min_y": -7855, 

This is actually a product of height and width from the skilltree data itself. Although, we should be drawing the tree in the center, but the problem is we don't exactly control where nodes are drawn.

**Comment by SpaceOgre** [comment]
True, might be best to wait for the official tree to be updated since these values could change. Otherwise we could maybe add some kind of offset.

**Comment by EmmittJ** [comment]
I was thinking we could just square up the tree always, but then we would be in the same situation where one side would be bigger.

**Comment by MLanghof** [comment]
...just center on the Scion?

**Comment by EmmittJ** [comment]
The scion is always the center of the tree meaning you could end up with elements off the background.

**Comment by MLanghof** [comment]
I mean "extend the background equally in all directions from the Scion".

**Comment by EmmittJ** [comment]
Yes, equal distances could make it look lopsided

**Comment by SpaceOgre** [comment]
Closing this. The space is used by the ascendancy trees.
