### ISSUE TITLE
Tree is ... Very weird

### ISSUE THREAD

**Issue by harpools** [EmmittJ/PoESkillTree#233]
So, I tried to update the tree by deleting the data folder and re-opening the program. This happened.

![skill_tree_weird](https://cloud.githubusercontent.com/assets/9124033/11760909/dd0c048c-a062-11e5-9ac0-2461d7a183de.png)

**Comment by EmmittJ** [comment]
Yes, you need to download the latest update. This fixes that issue. GGG
changed the way the tree is generated.
