### ISSUE TITLE
Error when trying to start PoESkillTree.exe

### ISSUE THREAD

**Issue by Ramic92** [EmmittJ/PoESkillTree#235]
The error time: 12/13/2015 11:35 PM
Exception: System.NullReferenceException: Objektreferensen har inte angetts till en instans av ett objekt.
   vid POESKillTree.SkillTreeFiles.SkillTree..ctor(String treestring, Boolean displayProgress, UpdateLoadingWindow update) i c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:rad 240
   vid POESKillTree.SkillTreeFiles.SkillTree.CreateSkillTree(StartLoadingWindow start, UpdateLoadingWindow update, CloseLoadingWindow finish) i c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:rad 629
   vid POESKillTree.Views.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) i c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:rad 209
   vid System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   vid System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   vid System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   vid System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   vid System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   vid System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   vid MS.Internal.LoadedOrUnloadedOperation.DoWork()
   vid System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   vid System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   vid System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   vid System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   vid System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   vid System.Windows.Interop.HwndTarget.OnResize()
   vid System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   vid System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   vid MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   vid MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   vid System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   vid MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
The error time: 12/13/2015 11:35 PM
Exception: System.NullReferenceException: Objektreferensen har inte angetts till en instans av ett objekt.
   vid POESKillTree.Views.MainWindow.GetLevelAsString() i c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:rad 751
   vid POESKillTree.Views.MainWindow.Window_Closing(Object sender, CancelEventArgs e) i c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:rad 321
   vid System.ComponentModel.CancelEventHandler.Invoke(Object sender, CancelEventArgs e)
   vid System.Windows.Window.OnClosing(CancelEventArgs e)
   vid System.Windows.Window.WmClose()
   vid System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   vid System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   vid MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   vid MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   vid System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   vid MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by EmmittJ** [comment]
This is the program not being able to pull data (i.e. bad internet connection to pathofexile.com). This isn't something that can be fixed on our end as we ship the tool with the data.
