### ISSUE TITLE
New user. Unable to load items?

### ISSUE THREAD

**Issue by Dronixx** [EmmittJ/PoESkillTree#238]
I am trying to load in items and I get this. Please help? This is what I get.
https://www.dropbox.com/s/iskv73fbf3gj2au/Untitled.jpg?dl=0

**Comment by EmmittJ** [comment]
You haven't provided information on what you get.

**Comment by Dronixx** [comment]
Sorry, Kids running all over distracting the crap out of me lol.

**Comment by EmmittJ** [comment]
Could you provide the data that you are trying to load, please?

**Comment by Dronixx** [comment]
I'm a total noob. I don't even know what you mean. I am trying to load my item data from ggg into the poe character builder. I follow the instructions and I get that msg above.

**Comment by EmmittJ** [comment]
I am looking for the item data you copied (or saved).

**Comment by Dronixx** [comment]
Hmmm... https://www.dropbox.com/s/13t4hqg2o2a0d89/get-items.json?dl=0 I am now sure I am completely lost as this opens up as almost nothing. I have no experience with this stuff lol. I just followed the instructions >.<

**Comment by EmmittJ** [comment]
It looks like you didn't give a character name or account name. This is why 'false' is the only thing in the file.

**Comment by Dronixx** [comment]
Does the game and account need to be open and at the time you try to load the items?

**Comment by EmmittJ** [comment]
You need to be logged into your account on the forums, and you need to provide the proper account name and character name in the fields.

**Comment by Dronixx** [comment]
Stupid Question. Is acct name the same is your login information? If so, I am entering that info and it is doing nothing.

**Comment by EmmittJ** [comment]
When you log in your account name is in the top left corner

**Comment by Dronixx** [comment]
I Figured that. I am using that information and my character name. It still wont load. Could something be blocking the information xfer on my side?

**Comment by EmmittJ** [comment]
When you open the link there should be a lot of text. You are probably not entering your account name or character name correctly. They have to be exact including capitals and such.

**Comment by Dronixx** [comment]
Is it possible that having the account name and character name exactly the same could create an issue? They are in this case the same.

**Comment by EmmittJ** [comment]
They shouldn't cause an issue.

**Comment by Dronixx** [comment]
I give up. I clearly see my acct name and I logged and chatted to verify my character name. It will not load. Thanks a ton for the help though!!!

**Comment by EmmittJ** [comment]
Could you send me the link that it is giving you?

**Comment by Dronixx** [comment]
That what is giving me?

**Comment by Dronixx** [comment]
o i see

**Comment by Dronixx** [comment]
https://www.pathofexile.com/character-window/get-items?character=Dronixx&accountName=Dronixx

**Comment by EmmittJ** [comment]
I have no idea why it won't load anything. It looks like it is properly generated. It is something on GGG's side. It might be because your profile is set to private

**Comment by Dronixx** [comment]
Well it loaded my items in! I had to manually create the save file. the default one was not saving correctly. I dunno?

**Comment by EmmittJ** [comment]
Well that's all that matters lol

**Comment by EmmittJ** [comment]
So it is working now?

**Comment by Dronixx** [comment]
Yes, copied the link manually saved it from there and loaded it. The default one was not working for some reason.

**Comment by Dronixx** [comment]
Yay! Thanks again.
