### ISSUE TITLE
Mana per level gain incorrect?

### ISSUE THREAD

**Issue by MrD3xter** [EmmittJ/PoESkillTree#239]
With Talisman came the change that all characters now get 6 mana per level instead of 4, but this change doesn't seem to have been reflected in the program.

Example: A level 85 Duelist without any nodes taken.
Program tells me he has 383 maximum mana, which assumes 40 base mana plus 4 per level, and 7 from 14 base intelligence.
It should be 551, assuming 40 base mana plus 6 per level, and 7 from 14 base intelligence.

**Comment by EmmittJ** [comment]
It is incorrect in the current version, but I have this fixed in the code base.
