### ISSUE TITLE
Download & Import Items not working.

### ISSUE THREAD

**Issue by matthewgrzegorczyk** [EmmittJ/PoESkillTree#241]
Hi,

I am trying to import items from my character.
https://www.pathofexile.com/character-window/get-items?character=VaalWRyjAzPadnie&accountName=ShatanBlack the link that is generated, I saved the output to the file, but I am getting the error when trying to load it in.
Error message: http://screen.shatan.pl/2016-01-05_13-57-51.png
Given JSON response from PoE API: http://screen.shatan.pl/get-items-vaalwryjazpadnie
As I was trying to parse it in Chrome Developer Tools Console, JSON object was valid and parsed well.
Proof: http://screen.shatan.pl/2016-01-05_14-01-02.png

Could you help me anyhow to track what is the problem with importing the items?

Cheers,
Matthew

**Comment by EmmittJ** [comment]
Do you happen to have any items with the character 'ö'?

**Comment by matthewgrzegorczyk** [comment]
Well I don't think so.
I've just copied whole response into http://regexr.com/ and put this regex for a test `/([^A-z"',.:0-9%=&{}/?><\-+ ])/g` - that's the all the chars that are present within the response.

**Comment by EmmittJ** [comment]
Hmm, there there any strange characters in the path to the downloaded file?
There really shouldn't be a character problem though.

**Comment by matthewgrzegorczyk** [comment]
I'll check it out later as I need to go right now. 
I have attached whole response above so maybe you'll be able to track it down somehow. (just reminding http://screen.shatan.pl/get-items-vaalwryjazpadnie)

**Comment by EmmittJ** [comment]
Not a problem, I will check out the file later as well.

**Comment by l0g0sys** [comment]
"Invalid characters in path" means the file/path name you tried to open 
contained illegal characters, not that content of file contained them.
Save JSON file directly to drive (D:\ for example) and name it as simple 
as possible.

**Comment by matthewgrzegorczyk** [comment]
**System:** Windows 8.1 Pro 64 bit.
**File system:** NTFS
**File paths I have used:** 
* `D:\items.json`
* `D:\items`
* `D:\Download\Chrome\poe\get-items-vaalwryjazpadnie`

BTW it's not related to tue use with the file path, as the old file with the items data which I downloaded on 25/07/2015 is working properly and it's path is `D:\Download\Chrome\poe\get-items` and it's importing properly.
The old file content: http://screen.shatan.pl/get-items

ATM I am using version 2.2.2 of PoESkllTree if it's relevant.

**Comment by matthewgrzegorczyk** [comment]
I have some idea, maybe Talismans, and path to an icon is a problem as it is 
`"icon": "\/gen\/image\/YTozOntpOjI7YTozOntz\/OjE6ImYiO3M6Mjk6IkFy\/dC8yREl0ZW1zL0ZsYXNr\/cy9tYW5hZmxhc2s1Ijtz\/OjI6InNwIjtkOjAuNjA4\/NTE5MjY5Nzc2ODc2MzE0\/ODE0NzI4NjMwMTUzNjk1\/MTIxNDA3NTA4ODUwMDk3\/NjU2MjU7czo1OiJsZXZl\/bCI7aToxO31pOjE7aTo0\/O2k6MDtpOjk7fQ,,\/ac4404fa2b\/Item.png",` for example ;)

**Comment by l0g0sys** [comment]
Well, i don't have any issues loading your JSON file into PoESkillTree-Talisman-2.2.3 (downloaded from http://screen.shatan.pl/get-items-vaalwryjazpadnie). Tried to load it into freshly downloaded https://github.com/EmmittJ/PoESkillTree/releases/download/2.2.3/PoESkillTree-Talisman-2.2.3.zip

That error message, you've made screenshot of, is Exception message when .NET is trying to open file with path containing invalid characters. The only question is which layer is generating it.

But why i cannot reproduce it?

**Comment by matthewgrzegorczyk** [comment]
Well as I said above I was using the version 2.2.2, maybe that is the reason?

I've just downloaded the version 2.2.3 and it was importing correctly.

**Comment by l0g0sys** [comment]
Sorry, i misread your post, thought it didn't work in 2.2.3 and you 
downgraded to 2.2.2 to make it work.

Not sure what changes were made specially for game patch 2.1.0, but it 
looks possible that previous versions won't be handling post 2.1.0 patch 
data correctly.
