### ISSUE TITLE
Batch importing character and stash data

### ISSUE THREAD

**Issue by slikts** [EmmittJ/PoESkillTree#242]
I recently made [a thing](https://github.com/slikts/fetchpoeitems/blob/master/lib/fetch.js) for fetching the character data via a bookmarklet (bookmarked JavaScript link) and was wondering if there's interest in using a similar approach to have a one-step import of all data for PoESkillTree. The process would look  like this:

 1. Add a bookmarklet in the browser
 1. Go to pathofexile.com
 1. Click bookmarklet, get a prompt with the combined data for the charater and stash tabs, copy it
 1. Paste it into PoESkillTree

The improvement would be that it's much simpler than the current process of downloading separate files. I'd make the JS part if there's interest.

**Comment by EmmittJ** [comment]
This is cool, but it is really up to the user how they would want to get their stash tab data.

**Comment by slikts** [comment]
Sorry, I don't understand what you mean

**Comment by EmmittJ** [comment]
I mean that there isn't a handy way to implement this into the planner itself. It is sweet and as long as it out puts proper JSON the planner should load it.
