### ISSUE TITLE
Feature request: multiple searches

### ISSUE THREAD

**Issue by Evilwarnut** [EmmittJ/PoESkillTree#243]
While I can input a regex pattern like:
area skills|power charge|maximum life

I would get a lot of red highlighted nodes on the tree, unable to tell which is which without hovering over each of them. 

If I do three searches separately, I cannot easily tell which direction in the tree I should go in order to grab all the nodes I wanted.

If we can have multiple searches like this pseudo UI:
Search:
[Text Field: area skills] [Regex: checked] [Color picker: red] [Delete Search]
[Text Field: power charge] [Regex: checked] [Color picker: green] [Delete Search]
[Text Field: maximum life] [Regex: checked] [Color picker: blue] [Delete Search]
[Add New Search]

It would make planning a build much more convenient.

**Comment by MLanghof** [comment]
> If I do three searches separately, I cannot easily tell which direction in the tree I should go in order to grab all the nodes I wanted.

You can right click nodes to check-tag them, which will remind you of their position and also allows you to also use the "Skill tagged nodes" feature.

There are already two kinds of searches implemented: The alphabetic/regex search, as well as highlighting via right clicking an affix in your passives list.

Yes, it could be done, and having a tree with 5 different node colors sounds fun to look at, but I'm not sold on the usefulness.

**Comment by EmmittJ** [comment]
I also wouldn't want to create an entirely new search language/parser
