### ISSUE TITLE
crash when trying to create items(debug.txt inc)

### ISSUE THREAD

**Issue by wootlink** [EmmittJ/PoESkillTree#244]
Every time i try to add an item to the build it crashes with a debug.txt
[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/149214/debug.txt)

**Comment by brather1ng** [comment]
I played around a bit with the "Craft new item" dialog and couldn't get it to crash. Could you provide us with more detailed reproduction steps?

**Comment by EmmittJ** [comment]
I might have fixed this when I was doing bud fixes. I haven't had the
chance to push a release version

**Comment by wootlink** [comment]
https://www.facebook.com/LouisShutts/videos/10153274048167657/

**Comment by brather1ng** [comment]
A video is definetely good for reproduction. I'm missing a Facebook account, though, so I can't look into it.

**Comment by EmmittJ** [comment]
>Sorry, this content isn't available right now

**Comment by wootlink** [comment]
https://youtu.be/VQn3HQyVC-E sry uploaded to youtube

**Comment by EmmittJ** [comment]
Oh, yeah. This has been fixed

**Comment by EmmittJ** [comment]
Can you please download the newest version of the tree and make sure this is fixed?

**Comment by wootlink** [comment]
yep its fixed
