### ISSUE TITLE
Crash when trying to switch class

### ISSUE THREAD

**Issue by Crazy-KSK** [EmmittJ/PoESkillTree#250]
http://pastebin.com/GdK89sy1

**Comment by EmmittJ** [comment]
Any steps to reproduce this?

**Comment by Crazy-KSK** [comment]
I was playing around with the gear creator before switching class and getting that crash, trying to reproduce it by adding and creating some gear and then adding some skill points to the tree got me this different crash
http://pastebin.com/emJN0Fbw

**Comment by Crazy-KSK** [comment]
I was playing around with the gear creator before switching class and getting that crash, trying to reproduce it by adding and creating some gear and then adding some skill points to the tree got me this different crash have  the same root cause 
http://pastebin.com/emJN0Fbw

**Comment by Crazy-KSK** [comment]
I was playing around with the gear creator before switching class and getting that crash, trying to reproduce it by adding and creating some gear and then adding some skill points to the tree got me this different crash have  the same root cause 
http://pastebin.com/emJN0Fbw

**Comment by EmmittJ** [comment]
Yeah, your second issue has been fixed. I think as well as the first. I am not sure though.

**Comment by EmmittJ** [comment]
could you please download version 2.2.5 of the skilltree and see if you have the class switching problem?

[If can be found here](https://github.com/EmmittJ/PoESkillTree/releases/tag/2.2.5)

**Comment by Crazy-KSK** [comment]
This seems to be fixed, good job =)
