### ISSUE TITLE
"Skill tagged nodes" crash

### ISSUE THREAD

**Issue by Fasbi** [EmmittJ/PoESkillTree#251]
http://pastebin.com/Uw8NxQ0i

Even when selecting only one node in front of the starting point of the class - it crashes when I try to use "Skill tagged nodes".

**Comment by EmmittJ** [comment]
Error in MinimalSpanningTree.cs - Line: 68 - `nodes.UnionWith(path);`

**Comment by MLanghof** [comment]
Will look into it.

**Comment by brather1ng** [comment]
This was fixed and can be closed.
