### ISSUE TITLE
Error cant open

### ISSUE THREAD

**Issue by andreluizlpg** [EmmittJ/PoESkillTree#253]
[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/150351/debug.txt)

trying to open and getting error.

**Comment by EmmittJ** [comment]
Please unzip/install the tree to a clean folder.

**Comment by andreluizlpg** [comment]
same error :(
[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/151261/debug.txt)

**Comment by EmmittJ** [comment]
You are missing assets. Please check the data and then assets folder and
make sure there are images there

**Comment by EmmittJ** [comment]
Could you please download version 2.2.5 of the skilltree [here](https://github.com/EmmittJ/PoESkillTree/releases/tag/2.2.5) and see if you are still getting this error?

**Comment by EmmittJ** [comment]
No response, I will go ahead and close this
