### ISSUE TITLE
Power Charges not show in summary

### ISSUE THREAD

**Issue by BorkaMatti** [EmmittJ/PoESkillTree#257]
Picking power charges does not add up in the summary. Using tree below. Should have 6 power charges, showing only 3.

https://www.pathofexile.com/passive-skill-tree/AAAAAwMAR8rfirv8fPDpAhV-kQdLrkJ6GyV6cNlbbRmX9CL0EVBSU2wLNbmXlT1fkyenKx1PTLN_xlM1e9cgbq6zwcVQQlAwQZbsGIw2217Q9XC7Tm2P-onTEQ_ZE6XE6_XQ0HBSrJgvb5wyZJ1faioL99fyHV3yhEiboSsKXGsYao9GES_DbXgvpwgdFOtjfOXr7o5k-tK1SFgHHNz3pmaeFy9tbLiTtvoWQLcxZOcPq-d0KPqFfYx2VdYki9saV8mCx4CkwzoQew18-egZir46QYf7CZy-9toNHxqPPCiPGg==

Using version 2.2.4.

**Comment by EmmittJ** [comment]
They are showing in the 'charge' group. I hav already fixed the naming issue so they will sum together.
