### ISSUE TITLE
Levels

### ISSUE THREAD

**Issue by SpaceOgre** [EmmittJ/PoESkillTree#259]
Atm we are not using levels, other than as a pointless stat. I think it might be time to remove it. Or I guess we can keep it if we are looking to help users calculate how many points they have available. But if not it would be best to remove it since it only adds confusion and no benefits.

What do you say?

**Comment by MLanghof** [comment]
Ironically, levels are used in the tree generator to find the number of available points. But they can't be changed in that window, instead you have to change them in the main tree.

The problem with removing player level from the main tree is that your base life (and mana) depends on them.

**Comment by SpaceOgre** [comment]
Ah, very true! Totally forgot about that part. I will show my self out...
