### ISSUE TITLE
Weird looking ascendancy class nodes

### ISSUE THREAD

**Issue by brather1ng** [EmmittJ/PoESkillTree#262]
All of the ascendancy class nodes look like this
![class](http://i.imgur.com/4RgEKqs.png)
Starts occurring with commit 8df6db1

**Comment by EmmittJ** [comment]
You are using the wrong images. I think it is the 2ND copy oh each new
image. They gave us a lot of images so you have to get ones that match our
zoom level

**Comment by brather1ng** [comment]
Ah that makes sense, I just threw the ones in there that were in the last release.

Seems like 3 is the correct size for us (even if there is no "LargeAllocated (3)"). With 2 the root skull definitely is too small (the background node is visible).

**Comment by EmmittJ** [comment]
Yeah, I didn't remember which ones I ended up using. I am not at my PC
