### ISSUE TITLE
Infinite Redirect

### ISSUE THREAD

**Issue by Alexei-B** [EmmittJ/PoESkillTree#267]
Latest release ends up in a redirect loop if you use a url like the one below:
https://www.google.com/url?q=http://poeurl.com/xer&sa=D&ust=1456857460554000&usg=AFQjCNH6POtjRXIVzd_kSRbH7sOVYuZW7A

Once in this loop you can't fix it within the program, and if you click a node it will crash.
To fix the issue go to "%APPDATA%\PoESkillTree - Ascendancy\PersistentData.xml" and edit out the saved url.

**Comment by EmmittJ** [comment]
I don't think the tree is setup to handle a google search query...

You simply can't just put anything in there. This is something I could fix,
but can I ask what is the use case for this URL?
