### ISSUE TITLE
Crash after using "Skill tagged nodes"

### ISSUE THREAD

**Issue by samcbar** [EmmittJ/PoESkillTree#271]
[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/156091/debug.txt)

Replication steps:

Tag any node by right clicking 
Go to Tools > Nodes > Skill tagged Nodes
At this point the program crashes. I have uninstalled and then re-installed the program (at 7PM PST March 2 / 3 AM UTC March 3)

**Comment by EmmittJ** [comment]
This has been fixed, but it has not been released.
