### ISSUE TITLE
Craft Window - Missing Block-Dagger types

### ISSUE THREAD

**Issue by ShawnieBoy** [EmmittJ/PoESkillTree#272]
The Prong Dagger, Trisula and Sai are missing from the Dagger base types in Item Crafting

They may have been missed as they're weapons with block chance instead of shields. Or they're in there somewhere and I can't find them! (Hunted in both main and off-hand just in case, but the dagger lists skip them.)

**Comment by EmmittJ** [comment]
Re downloading the item assets should fix this.

**Comment by EmmittJ** [comment]
http://i.imgur.com/YbSUjCM.png

Tools > Program Assets > Redownload Item Assets will fix this problem.
