### ISSUE TITLE
Skill tree comparision: difference per attribute not shown

### ISSUE THREAD

**Issue by brather1ng** [EmmittJ/PoESkillTree#274]
The differences in attributes between two skill trees are not shown if compared via "Skill tree comparision" (works in the latest release).

**Comment by EmmittJ** [comment]
Hmm, I thought @sectoidfodder had fixed that

**Comment by Sectoidfodder** [comment]
Woops, just opened my own bug report for this w/o checking old ones.

I don't remember editing MainWindow.xaml myself, but it's being caused by missing a use of AttributeToTextBlockConverter.  Dunno when that happened.
