### ISSUE TITLE
Path Highlight Skipping First Connection

### ISSUE THREAD

**Issue by dgagliar** [EmmittJ/PoESkillTree#275]
When hovering over a node that isn't adjacent to an allocated node (i.e., requires at least 2 points to get to), the green highlight skips the connection from the nearest allocated node. See attached screenshot for an example.

Steps to reproduce:

* Allocate some nodes on a new skill tree.
* Hover over a node that would require at least 2 points to get to
* Expected: Full path between nearest allocated node and hovered node highlight
* Actual: [Starting at the first unallocated node, path to hovered node is highlighted](https://cloud.githubusercontent.com/assets/10118781/13516138/4a527e3c-e16c-11e5-901f-4009cc7cf10b.png)

**Comment by EmmittJ** [comment]
Yeah, I will be releasing a version tomorrow or the next day with this fix.
