### ISSUE TITLE
ERROR: Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by perennial-flux** [EmmittJ/PoESkillTree#279]
Full Error Report:

**"An error occurred while attempting to load Skill tree from URL.**

**Details:**
**Index was out of range. Must be non-negative and less than the size of the collection.**
**Parameter name: index"**

I'm running Windows 10 64-bit. I was able to load tree using older version URL's and the program worked great. All of a sudden, when I try to "Load Tree", it fails and gives me the error. I have uninstalled (completely) and re-installed the program 3 times. No fix.

_Picture of my error below:_

![tree_error](https://cloud.githubusercontent.com/assets/17673020/13547567/560487bc-e28d-11e5-8e42-56ceeedef761.png)

**Comment by EmmittJ** [comment]
Are you using version 2.2.5?

**Comment by EmmittJ** [comment]
https://github.com/EmmittJ/PoESkillTree/releases/tag/2.2.5
Can be found there.

**Comment by perennial-flux** [comment]
Yes. It is the version 2.2.5

**Comment by EmmittJ** [comment]
Can you give me the link that is giving you an error?

**Comment by perennial-flux** [comment]
Getting this error when re-installing:

An error occurred while attempting to load Skill tree from URL.
Details:
Invalid length for a Base-64 char array or string.

**Comment by EmmittJ** [comment]
You should be able to hit Ok and continue to load the planner. It will just fail to load the tree. Could you please provide me with the troublesome tree url?

**Comment by perennial-flux** [comment]
I re-installed using your link. Same issue. The link I was using for installing was:

https://github.com/EmmittJ/PoESkillTree/releases

**Comment by perennial-flux** [comment]
Yes, 1 moment.

**Comment by perennial-flux** [comment]
**I used this up to level 20 and it loaded fine: **http://poeplanner.com/AAAABAABX768guSQEYqvSsg7KAOWbj1gQ4MJbqq18nJsbEYyCXgNwBqpblivNuiGYDpSMn57bpchwXwh0ADBhFPv_RBi

**Loaded this around level 40 with no problems: **http://poeplanner.com/AAAABAABX768guSQEYqvSsg7KAOWbj1gQ4MJbqq18nJsbEYyCXgNwBqpblivNuiGYDpSMn4aVWEhhO-pJ3h6qZSHaoTZR369NmVNvqfawXTtBS1673tulyHBfCHQAMGEU-_9EGI=

**Comment by perennial-flux** [comment]
Sorry about the asterisk at the beginning. That's not included.

**Comment by perennial-flux** [comment]
Here is the website I'm using my builds from:

https://www.pathofexile.com/forum/view-thread/847200/page/1

**Comment by EmmittJ** [comment]
Erm, poeplanner does follow any of the parsing conventions that we use to load urls. 

If you were to put a `#` after `http://poeplanner.com/` like so http://poeplanner.com/#AAAABAABX768guSQEYqvSsg7KAOWbj1gQ4MJbqq18nJsbEYyCXgNwBqpblivNuiGYDpSMn4aVWEhhO-pJ3h6qZSHaoTZR369NmVNvqfawXTtBS1673tulyHBfCHQAMGEU-_9EGI= then it will load just fine.

**Comment by perennial-flux** [comment]
That worked! Much appreciated. Thanks for the fast response too!
