### ISSUE TITLE
Craft Item crashes

### ISSUE THREAD

**Issue by PhiPhiper** [EmmittJ/PoESkillTree#286]
NullPointerException in portable Version when trying to open the CraftItemView.

Steps to reproduce:
-Click on "Equipment"-Tab
-Click "Craft New Item"

[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/161897/debug.txt)

**Comment by EmmittJ** [comment]
Can you tell me what version of the tool you are using? This should be in
Help > About PoESkillTree

**Comment by PhiPhiper** [comment]
Sorry forgot that. Exe-Fileversion is 2.2.5.850 (Latest Release)

**Comment by EmmittJ** [comment]
Thanks, could you re-download the item assets in the Tools menu? Also, if
you could upload the debug.txt file that would be very handy

**Comment by PhiPhiper** [comment]
The debug is already uploaded. There seems to be even a more serious problem. I ll get back to you as soon as I can investigate further. 
After the app crashes my Windows stops being able to close Programs and I can't open the StartMenu.
My rig runs a fully updated Windows 10 64-bit Educational version.

PS: I tried to redownload but it tells me an error occured.
[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/161949/debug.txt)

**Comment by EmmittJ** [comment]
Sorry, I was using my email, so I didn't see the file. The app shouldn't be
causing windows to malfunction like that. I will be able to hopefully fix
this in a couple days. I have some class work I need to get finished up.

**Comment by EmmittJ** [comment]
I have fixed the second portion of the problem, but it has not gone live. You should copy you builds ([can learn how here](https://github.com/EmmittJ/PoESkillTree/wiki/How-To:-Copy-Builds)) place them somewhere safe, then delete the data folder and recopy your builds into the data folder. This should solve your problems.
