### ISSUE TITLE
skillplanner stopped working.

### ISSUE THREAD

**Issue by Drimli** [EmmittJ/PoESkillTree#287]
Here is the debug txt.

The error time: 3/8/2016 7:38 AM
Exception: System.Xml.XmlException: '.', den hexadecimale værdi 0x00 er et ugyldigt tegn. linje 1, position 1.
   ved System.Xml.XmlTextReaderImpl.Throw(Exception e)
   ved System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   ved System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   ved System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   ved System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   ved System.Xml.XmlTextReaderImpl.Read()
   ved System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   ved System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   ved POESKillTree.Utils.CustomSettingsProvider.LoadValuesFromFile() i c:\GitHub\PoESkillTree_Source\WPFSKillTree\Utils\CustomSettingsProvider.cs:linje 146
   ved POESKillTree.Utils.CustomSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection collection) i c:\GitHub\PoESkillTree_Source\WPFSKillTree\Utils\CustomSettingsProvider.cs:linje 81
   ved System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   ved System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   ved System.Configuration.SettingsBase.get_Item(String propertyName)
   ved System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   ved System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   ved MahApps.Metro.Controls.WindowApplicationSettings.get_Placement()
   ved MahApps.Metro.Controls.WindowSettings.LoadWindowState()
   ved MahApps.Metro.Controls.WindowSettings.WindowSourceInitialized(Object sender, EventArgs e)
   ved System.EventHandler.Invoke(Object sender, EventArgs e)
   ved System.Windows.Window.OnSourceInitialized(EventArgs e)
   ved System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   ved System.Windows.Window.CreateSourceWindowDuringShow()
   ved System.Windows.Window.SafeCreateWindowDuringShow()
   ved System.Windows.Window.ShowHelper(Object booleanBox)
   ved System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ved System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numA

**Comment by SpaceOgre** [comment]
Some more information would be good:
* What version are you running?
* When does it happen? During startup?
* Portal or Installed?

**Comment by EmmittJ** [comment]
I think this is the same error as #290, so I will go ahead and close this.
