### ISSUE TITLE
Planner crashes on start-up

### ISSUE THREAD

**Issue by Ehlol** [EmmittJ/PoESkillTree#288]
The planner crashed, not sure exactly what happened or what I did, but now I can't open the program anymore. It crashes straight from start-up and just links me to the debug.txt which looks like this:

The error time: 09-03-2016 03:08
Exception: System.FormatException: Inputtet er ikke en gyldig Base-64-streng, da det indeholder et tegn, som ikke er et base-64-tegn, mere end to udfyldningstegn eller et ugyldigt tegn blandt udfyldningstegnene. 
   ved System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   ved System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   ved System.Convert.FromBase64String(String s)
   ved POESKillTree.SkillTreeFiles.SkillTree.DecodeURL(String url, HashSet`1& skillednodes, Int32& chartype) i c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:linje 1110
   ved POESKillTree.Views.MainWindow.lvSavedBuilds_SelectionChanged(Object sender, SelectionChangedEventArgs e) i c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:linje 2276
   ved System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   ved System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   ved System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   ved System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   ved System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   ved System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   ved System.Windows.Controls.ListBox.OnSelectionChanged(SelectionChangedEventArgs e)
   ved System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   ved System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   ved System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   ved System.Windows.Controls.Primitives.Selector.OnSelectedIndexChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   ved System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   ved System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   ved System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   ved System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   ved System.Windows.DependencyObject.CoerceValue(DependencyProperty dp)
   ved System.Windows.Controls.Primitives.Selector.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   ved System.Windows.Controls.ListView.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   ved System.Windows.Controls.ItemsControl.OnItemCollectionChanged2(Object sender, NotifyCollectionChangedEventArgs e)
   ved System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   ved System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   ved System.Windows.Controls.ItemCollection.OnViewCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   ved System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   ved System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   ved System.Collections.Specialized.CollectionChangedEventManager.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   ved System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   ved MS.Internal.Controls.InnerItemCollectionView.Add(Object item)
   ved System.Windows.Controls.ItemCollection.Add(Object newItem)
   ved POESKillTree.Views.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) i c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:linje 450
   ved System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   ved System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   ved System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   ved System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   ved System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   ved System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   ved MS.Internal.LoadedOrUnloadedOperation.DoWork()
   ved System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   ved System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   ved System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   ved System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   ved System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   ved System.Windows.Interop.HwndTarget.OnResize()
   ved System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   ved System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ved MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ved MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   ved System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ved System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Ehlol** [comment]
And by the way, I tried to delete the program, incl clearing registry entries (with CCleaner) and make a reinstall because I thought it could fix the problem. It didn't. A real shame that the program now doesn't work at all, since there isn't really an alternative to it anywhere.

**Comment by EmmittJ** [comment]
What build URL did you try to load because it looks like you loaded something that isn't properly generates or handled by the program. 

View #282, after the 'closed' message should fix your problem. Please post the URL that was in currentbuild

**Comment by Ehlol** [comment]
I'm not 100% sure but I believe I wanted to compared two different builds, and I was not sure exactly how to do it, since I haven't used the program for that long. And I believe the two URL's were:

https://www.pathofexile.com/fullscreen-passive-skill-tree/AAAABAQDAQHcBLMFLQmWC2EMXxLhFCAUcRXsGjgcpyE0Jy8slC3SMZ40jjWSOQ464Ts7PAU8LT38QT9DMUd-TP9N41BHUeZTpVO7WGNZ81oaXz9iF2VNaGVo8mvZbztyqXTtdqx3U3fjeA15aHrve9R82YIHg1-ElITZhO-FUoY7h2qJcYrwj2CQVZBskc6Uh5d5my2exZ8-n9-iAKLqplepJ6luqZSsqq2Nr2ywq7QvtfK5HbvtvTa-p7_VwBrAZsEEwzPEWMSCxPbGrs9-1ljYvdlh2Xzawd-y5FHpRuoY6wnsXO8O73zwH_JF8932SPcy-Ov-Cv6P

and 

https://www.pathofexile.com/fullscreen-passive-skill-tree/AAAABAQDAQHcBLMFLQmWEuEUIBXsGjgaPiE0Jy8pLiyULdIuUzKJNI41kjkOOtg64TwFPfxBP0MxR35M_03jUEdR5lcNV-JYY1nzWhpfP2IXZU1oZWjya9lvO3KpdO12rHfjd-V4DXh6eWh673vUfLh82YIHgpuElITZhO-GO4dqiXGK8IzPj2CQVZHOlIeWbJd5nsWfPp_fogCi6qZXqSepbqmUrKqtja9stC-18rkdvTa-p8AawGbBBMMzxILKkM9-0iHTb9ZY2L3ZYdl82sHfsuFz5FHpRuoY7FztIO8O73zwH_Gs8kHyRfOb9kj3Mv4K_o8=

I don't remember exactly what I did, but I think I saved both of them and then tried to get the program to show them both.

**Comment by Ehlol** [comment]
Emmitt I don't think my comp-wizz skills allows me to understand what to do. I don't know how to continue after step one in your comment in topic #282 :

1) Find your PersistentData.xml file
2) Open PersistentData.xml in NotePade
3) Find <CurrentBuild>...</CurrentBuild>
4) Replace everything (in the current build) between <Url> and </Url> with nothing

How do I "do" 2) 3) and 4) ?

**Comment by EmmittJ** [comment]
Open the file with NotePad. Right Click > Open With ... then find notepad
on the list.

**Comment by Ehlol** [comment]
Ah - I didn't realize that the "run" had to be used in danish since my windows installation is in danish, sorry being stupid.

I think I deleted too much in the persistentdata file, because it didn't work as it should. So i deleted the whole folder instead, re-installed the program and now it works again. I'll make sure to pay attention to the details if the same error occurs again and let you know in here so it can be fixed.

Sorry for wasting your time.

**Comment by EmmittJ** [comment]
Ah, no worries. Glad you got something to work!
