### ISSUE TITLE
Saved Profiles lost when XML File became corrupted

### ISSUE THREAD

**Issue by iRonOfMan** [EmmittJ/PoESkillTree#289]
Running on Windows 10, the client was left running overnight and Windows 10 did it's "auto-update". When I started the program I got the error message that the **XML file was corrupted** and could not be opened "pop-up box". selecting the OK Button the client opened but all saved profiles are gone.

1) Is it possible to recover the data?
2) What safeguard should be used going forward to ensure the builds aren't lost?

**Comment by EmmittJ** [comment]
1) No

2) This isn't our fault. It is very important that you shut down applications appropriately. 

I am assuming you had a lot of builds? The skill tree when shut down correctly will save your builds, but when forced to stop can cut this process and in return corrupt any data we are saving.

**Comment by MLanghof** [comment]
Isn't it customary though to save everything in a separate file and only replace the actual saved data file with the temporary one if everything went well?

**Comment by EmmittJ** [comment]
That is what we do with the Data folder. I don't think it would be too hard
to do such a thing with the builds

**Comment by MLanghof** [comment]
Awesome!

**Comment by EmmittJ** [comment]
Oh, whoops. I will get this fixed, when I get back to a pc
