### ISSUE TITLE
Allow adding of pseude attributes to Passive/Total attributes list

### ISSUE THREAD

**Issue by EnderWiggin** [EmmittJ/PoESkillTree#291]
Pretty much what title says. Since we can now add custom attribute groups, allow us to add pseudo skills to be shown in them. This will simplify comparing two builds.

**Comment by Sectoidfodder** [comment]
Not really sure what you're looking for exactly.  Do you mean pseudo attributes like "+X% total elemental resistances" from poe.trade?  Custom attribute groups can already emulate that - a group named "+#% total elemental resistances" will sum up the individual attributes that you add inside it (replacing the '#' in the name) and allow you to compare the total across builds.

If you're looking for something different, let me know in more detail and I'll see what I can do to make it happen.

**Comment by EmmittJ** [comment]
I am also confused. Could you please clarify what you mean? Pseudo attributes can be adding via the custom grouping function like @Sectoidfodder states.

**Comment by EnderWiggin** [comment]
Oh, I didn't knew custom groups worked like that. Thought they just group attributes. This is good enough then.
What I meant is ability to select any attribute defined in psuedo attributes to be displayed among usual attributes. Still, pseudo attribuets are more flexible than custom groups, but custom groups can cover 99% of my needs.

**Comment by EmmittJ** [comment]
Hmm, I think groups define pseudo attributes much better since you can just minimize them. They also allow you to see what stats are adding up to the total you see.
