### ISSUE TITLE
Problem when loading a saved Scion - Ascendant build

### ISSUE THREAD

**Issue by lolbifrons** [EmmittJ/PoESkillTree#295]
When I load my Scion - Ascendant build, the center node for the Ascendant ascendancy class gets unallocated, even if I reallocate it, save again, and try to load.  This happens any time I double click the build or restart the program.

The consequences of this are strange.  Allocating more passives works fine, but because the build takes Path of the Shadow, if I forget to reallocate that Ascendant node before _unallocating any node_, the program also unallocates all of the Ascendency points in the Ascendant section, including Path of the Shadow, which in turn unallocates everything that begins from the shadow's starting point.

So every time I load my build, I can't make any significant changes to it without first remembering to hit the center node in the Ascendant class again, or else I have to redo half of my tree (or reload the save.)

**Comment by EmmittJ** [comment]
This has been fixed but not released yet, sorry.

**Comment by lolbifrons** [comment]
Ah sorry, I didn't think to check closed issues.  My mistake.
