### ISSUE TITLE
Class switching doesn't check spent ascendancy points

### ISSUE THREAD

**Issue by Sectoidfodder** [EmmittJ/PoESkillTree#298]
Switching base class and putting points in an ascendancy of the new class doesn't remove the skills in an ascendancy of the old class.

**Comment by EmmittJ** [comment]
I think I fixed this in a few commits last night. I will double check
though.

**Comment by Sectoidfodder** [comment]
I just updated my local copy with new changes an hour ago.  It's a narrow case where ex: you have points in trickster, then switch to witch and put points into elementalist, your old trickster points remain.

If you then put points into occultist, both the elementalist and old trickster points will be removed.

**Comment by Sectoidfodder** [comment]
Oh I see why.  It only happens if the new ascendancy you put points into matches the "default" ascendancy selected when you switch base classes.  When I switched to witch it selected "elementalist" by default so I can put points into elementalist w/o it checking for old points in other ascendancies.

**Comment by EmmittJ** [comment]
Oh, I see. Thanks.
