### ISSUE TITLE
Cannot generate skilltree

### ISSUE THREAD

**Issue by francoix** [EmmittJ/PoESkillTree#305]
Hello,

When I try to generate a skilltree I am gettin the "Could not open skill tree generator" error as seen in http://imgur.com/a/Kgn5D

This is happening with the setup version of the application

**Comment by francoix** [comment]
Fyi reverted to 2.2.5 and the issue disappears.

**Comment by brather1ng** [comment]
Thanks for reporting this. It already has been fixed but is not released yet.

@EmmittJ Imo, it would be a good idea to do bugfix releases if critical bugs from the latest release are fixed. As it is now, people have to wait for the next release to be able to use bugged things again.

**Comment by EmmittJ** [comment]
Yeah, I normally give some time for bug reports to come in, and it looks
like there isn't too many. I can get a release ready for later today

**Comment by doncatnip** [comment]
So, is it later today yet ? :)
