### ISSUE TITLE
"Check for updates" installs in wrong folder.

### ISSUE THREAD

**Issue by ntt** [EmmittJ/PoESkillTree#308]
I installed 2.2.4 on my G: drive. I used the program's "check for updates" feature to update it to 2.2.6.

The 2.2.6 installation ended up on my C: in the default install location.

**Comment by EmmittJ** [comment]
Hmm, did 2.2.4 happen to be the portable version?

**Comment by ntt** [comment]
Yes, it's was portable version as I like tools like this to stay in their own folder.
That shouldn't matter for update though? If I choose to use a program's update feature, it should update that install, not install a 2nd copy.

**Comment by brather1ng** [comment]
Iirc, the updater simply starts the installer with the default settings. You have to change the location to the one you want to update.

But yes, it should use the location of the installation that started the installer. However, that might not be easy to fix as the program and the installer are independent.

**Comment by EmmittJ** [comment]
Yeah, that is something I can look into, but @l0g0sys might have some
additional information on something like this before I am able to look into
it.

**Comment by l0g0sys** [comment]
Yep, it should install in same directory in this case.
I had brief look at installer build script and it looks like 
NextButtonClick function will always overwrite destination directory 
even if passed as /DIR argument.
So i think it might be possible to get PortabilityPage skipped when 
running in silent mode in ShouldSkipPage function, thus NextButtonClick 
not getting invoked for PortabilityPage at all.

**Comment by EmmittJ** [comment]
Alright, I think I have go something working. I have run it by hand after compiling a release and it installs to the correct directory.

**Comment by brather1ng** [comment]
@ntt Can you check if "check for updates" now updates the correct folder, please?

**Comment by ntt** [comment]
@brather1ng It does, cheers.

**Comment by EmmittJ** [comment]
Sweet, glad the fix worked!
