### ISSUE TITLE
2.2.6 doesn't start, no errors, no logs

### ISSUE THREAD

**Issue by teuneboon** [EmmittJ/PoESkillTree#309]
So, let me start by saying: 2.2.6 used to work, but since today it suddenly doesn't. I just double click the icon on my desktop to start it and nothing seems to happen. I tried installing again, I tried uninstalling then installing again, I tried renaming my AppData/Roaming/PoeSkillTree-Ascendancy folder thing, I tried running in compatibility mode, I tried running as Administrator, nothing seems to work.

If I rename the PoESkillTree AppData folder it just gets recreated when I try to start PoESkillTree, but PoESkillTree still doesn't start.

I'm running Windows 10, I don't care if I lose my builds, I just want to be able to make new ones at least :(.

**Comment by EmmittJ** [comment]
Does it give you an error message? Could you post your debug.txt folder
from the app data folder.

**Comment by teuneboon** [comment]
No error message, just nothing happens. My [debug.txt](https://github.com/EmmittJ/PoESkillTree/files/233039/debug.txt), note the dates, nothing recent. I know how hard this is to debug, I don't know wtf is going on either

**Comment by EmmittJ** [comment]
Back up the `PersistentData.xml` in the app data folder. Uninstall, delete
the app data folder if it is still there, and then reinstall.

**Comment by teuneboon** [comment]
Still doesn't help :(
Windows Event Viewer gave me this output earlier, doesn't look helpful, but it might be to you:

> Log Name:      Application
> Source:        Application Error
> Date:          23-4-2016 18:16:36
> Event ID:      1000
> Task Category: (100)
> Level:         Error
> Keywords:      Classic
> User:          N/A
> Computer:      DESKTOP-H2UJAQD
> Description:
> Faulting application name: PoESkillTree.exe, version: 2.2.6.910, time stamp: 0x570af9fc
> Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
> Exception code: 0xc0000005
> Fault offset: 0x00000014
> Faulting process id: 0xf70
> Faulting application start time: 0x01d19d7b8185b1b7
> Faulting application path: C:\Program Files (x86)\PoESkillTree - Ascendancy\PoESkillTree.exe
> Faulting module path: unknown
> Report Id: bde53e41-64b3-42a6-8a24-6f2bc6347598
> Faulting package full name: 
> Faulting package-relative application ID: 
> Event Xml:
> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
>   <System>
>     <Provider Name="Application Error" />
>     <EventID Qualifiers="0">1000</EventID>
>     <Level>2</Level>
>     <Task>100</Task>
>     <Keywords>0x80000000000000</Keywords>
>     <TimeCreated SystemTime="2016-04-23T16:16:36.120653600Z" />
>     <EventRecordID>6866</EventRecordID>
>     <Channel>Application</Channel>
>     <Computer>DESKTOP-H2UJAQD</Computer>
>     <Security />
>   </System>
>   <EventData>
>     <Data>PoESkillTree.exe</Data>
>     <Data>2.2.6.910</Data>
>     <Data>570af9fc</Data>
>     <Data>unknown</Data>
>     <Data>0.0.0.0</Data>
>     <Data>00000000</Data>
>     <Data>c0000005</Data>
>     <Data>00000014</Data>
>     <Data>f70</Data>
>     <Data>01d19d7b8185b1b7</Data>
>     <Data>C:\Program Files (x86)\PoESkillTree - Ascendancy\PoESkillTree.exe</Data>
>     <Data>unknown</Data>
>     <Data>bde53e41-64b3-42a6-8a24-6f2bc6347598</Data>
>     <Data>
>     </Data>
>     <Data>
>     </Data>
>   </EventData>
> </Event>

**Comment by EmmittJ** [comment]
I have no idea what that means, sorry. The only thing I can think of to-do
is what was said above with maybe restarting before the at step.

**Comment by teuneboon** [comment]
I'll try with a full pc restart, it's Windows after all, you never know, will edit this comment once I know if it works

**Comment by EmmittJ** [comment]
Yep >.>
