### ISSUE TITLE
Added Elemental Integer Damage Not Showing On Offense Tab

### ISSUE THREAD

**Issue by Gl0wyrm** [EmmittJ/PoESkillTree#310]
I have a piece of gear, a wand, that adds 8-17 Cold Damage To Spells. This does not show up on the Offense tab of the Character sheet but it does show up in the Attributes sheet. Due to this, my spells' total damage and DPS calculations are off compared to in-game. A bug?

Related side note, not sure if it's possible, but having things like "Herald of Ice" also add it's buff to the Attribute tab would be great (then have that shown on the Offense tab's other spells). I assume a check box near the name of the spell would be a good way to toggle it's effect on and off.

Also, I don't know if this warranted it's own bug report, but the Mind Over Matter keystone passive is kind of the same way, it is listed correctly on the Attributes sheet but the Offense tab of the Character sheet shows all spells as having 150% Crit Multiplier still when that keystone is supposed to remove Crit Multiplier (makes it 100%).  This is very minor since I don't believe the multiplier is taken into account in any calculations that are visually represented.

**Comment by MLanghof** [comment]
I'm not even sure if the damage calculation has been touched since added damage to spells was introduced...

> Mind Over Matter
You mean Elemental Overload, right?

**Comment by Gl0wyrm** [comment]
Yes, sorry, Elemental Overload, thank you for the info and correction.

**Comment by brather1ng** [comment]
Added damage to spells and Elemental Overload is fixed.

> Related side note, not sure if it's possible, but having things like "Herald of Ice" also add it's buff to the Attribute tab would be great (then have that shown on the Offense tab's other spells). I assume a check box near the name of the spell would be a good way to toggle it's effect on and off.

This is related to #100. Complete support for auras and heralds would be great, but that is a bit more work than the other stuff you reported :)
