### ISSUE TITLE
Request - bandit reward nodes

### ISSUE THREAD

**Issue by Sectoidfodder** [EmmittJ/PoESkillTree#311]
Would it be possible to add nodes floating somewhere corresponding to the nine bandit rewards?  It would be nice to have them counted in the attributes list.  It would also allow end-game level to be calculated directly from skill points spent ([points - 23] assuming all quests are done, with an exception made for the Ascendant's extra points).

**Comment by EmmittJ** [comment]
I don't think we should mess with adding nodes, but it should be easy to
add it somewhere. I just don't think it has been added because of where to
put it.

**Comment by brather1ng** [comment]
I have implemented it (as part of the UI, not as nodes). Looks like this atm:
![Bandit popup](https://cloud.githubusercontent.com/assets/7596346/14930118/c5aed086-0e61-11e6-97ba-206ff9c1843d.PNG)

There is a button to left of the level-box that shows a popup for bandit-selection on click. That popup disappears if you click anywhere else.

I am not sure if that is the best place for it. However, with how it's implemented, moving the button or the selection boxes that are currently part of the popup is trivial.

>  It would also allow end-game level to be calculated directly from skill points spent

I would do it the other way around. With bandits and the level the maximum number of points (which is currently a fixed 123) can be calculated.

**Comment by brather1ng** [comment]
I've changed "Total Passive Skill Points" to be based completely on level and bandits (plus 21 base nodes and possibly Scion ascendancy nodes). (not pushed yet)

I feel like that is a good idea but I want the opinion from someone else before I push that.

**Comment by EmmittJ** [comment]
It is better than anything I have come up with for it. I think it would be a nice addition

**Comment by brather1ng** [comment]
@Sectoidfodder I guess what I've done is close enough to what you imagined so I'll close this.
