### ISSUE TITLE
Opening a solution failed due to missing projects; RangeTree and WpfRangeControls

### ISSUE THREAD

**Issue by wongni** [EmmittJ/PoESkillTree#312]
I just downloaded the source code zip file but opening WPFSKillTree.sln in VS 2013 failed with the followig error. 

C:\workspace\personal\PoESkillTree-master\RangeTree\RangeTree\RangeTree.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\workspace\personal\PoESkillTree-master\RangeTree\RangeTree\RangeTree.csproj'.  C:\workspace\personal\PoESkillTree-master\RangeTree\RangeTree\RangeTree.csproj

C:\workspace\personal\PoESkillTree-master\WpfRangeControls\WpfRangeControls\WpfRangeControls.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\workspace\personal\PoESkillTree-master\WpfRangeControls\WpfRangeControls\WpfRangeControls.csproj'.  C:\workspace\personal\PoESkillTree-master\WpfRangeControls\WpfRangeControls\WpfRangeControls.csproj

**Comment by EmmittJ** [comment]
Yeah, you will need to `git clone --recursive git://github.com/EmmittJ/PoESkillTree.git` or 
`git clone git://github.com/EmmittJ/PoESkillTree.git`
`cd PoESkillTree`
`git submodule update --init --recursive`

**Comment by EmmittJ** [comment]
You can technically just run `git submodule update --init --recursive` if you downloaded the .zip

**Comment by wongni** [comment]
Thank you very much for the reply. I am pretty new on github and git so I didn't know about the 'submodule' things.
