### ISSUE TITLE
Skill gem "Deals #% of Base Attack Damage" is applied twice

### ISSUE THREAD

**Issue by brather1ng** [EmmittJ/PoESkillTree#314]
The wiki calls this mod "Deals #% of Base Damage". Because of that the original mod is not replaced and both are applied as multipliers in damage calculation.

The mod has to be renamed while extracting it from the wiki. I don't know anything about our wiki extraction things so I'll leave this to someone that knows more.

With that fixed the calculation stuff is working (almost) correctly again. At least for all gems and mods it supported before at some point.

**Comment by EmmittJ** [comment]
Hmm, I don't think we should rename what the mod is in-game, but remove mods that don't exist anymore. Looking through `WPFSkillTree\Items.xml` I only see `Deals #% of Base Damage`

**Comment by brather1ng** [comment]
`Deals #% of Base Damage` is *not* what the mod is called in-game, it called `Deals #% of Base Attack Damage` in-game. That is where the problem comes from.

**Comment by EmmittJ** [comment]
Oh, I see! I will fix this.

**Comment by EmmittJ** [comment]
Whoops, I will reopen until confirmed.

**Comment by brather1ng** [comment]
Works now, thanks!
