### ISSUE TITLE
Skilltree Graphic Crash

### ISSUE THREAD

**Issue by TreeRipper** [EmmittJ/PoESkillTree#315]
The Skill Tree Screen will turn Black when trying to drag and scroll inside the Skill Tree window at the same time. It seems like it zooms out by an indefinate amout.

**Comment by brather1ng** [comment]
You can right click the black anywhere and it will zoom and position the skill tree at the center again.

Because of that, I don't think this is worth fixing. Yes, it behaves weirdly when simultaneously draging and zooming but why would anyone want to do that and what would be the correct behaviour?

**Comment by EmmittJ** [comment]
I don't think there will ever be correct behavior, but I think we could
disable zooming while clicking? That is a lot more annoying though than
right clicking.

**Comment by brather1ng** [comment]
Yeah, true. I don't think there is any valid reason to zoom while clicking, so just disabling it should be an easy solution.

**Comment by TreeRipper** [comment]
I agree on a PC it's not common to click and drag. On a notebook (using the touchpad) on the other hand it will happen by accident which results in the program beeing hard to use. I understand that niche cases like this have a low priority of course. Just wanted to mention it.

**Comment by brather1ng** [comment]
Ah, I didn't think about notebooks and wondered how that can happen enough to be a problem.

Shouldn't be too difficult to not allow zooming while the left mouse button is down, assuming that doesn't interact with touchpads in some other way.

**Comment by TreeRipper** [comment]
Yeah to further explain the issue: on some notebooks the side of the touch pad acts as the mousewheel without beeing distinguishable in any haptic way so while you are click-dragging on the tree you will sometimes accidentally use that section of it resulting in some wierd flickering of the skilltree. Thats just from my experience so i can't vouch for how common that is for other users.
