### ISSUE TITLE
Crash when PoE game is running

### ISSUE THREAD

**Issue by doncatnip** [EmmittJ/PoESkillTree#316]
There is no debug.txt nor any error message. It simply "stops working". Mysteriously, this only happens after tabbing out of path of exile and subsequently clicking on a random node OR zooming. When the skill planner is started after poe, it does not crash as long as I don't tab into the game and back. Affects at least 2.2.5 and 2.2.6 on windoze 10.

**Comment by brather1ng** [comment]
This sounds like something that will either be hard to track down or not fixable by us at all.

In what mode are you playing PoE (Fullscreen, Windowed Fullscreen or Windowed)?
Is the planner fullscreen or windowed and is it on the same monitor as the game?

**Comment by doncatnip** [comment]
It appears this only happens when poe is fullscreen and runs in a different resolution than windoze. It's on the same monitor. Does not matter if the planner is maximized. Yea, I don't think this is an easy one. Might have something to do with the display drivers.

**Comment by brather1ng** [comment]
Hm, I can't reproduce it. It is probably related to your setup but I have no idea what may cause it.

**Comment by EmmittJ** [comment]
If there is no debug.txt file then the program isn't crashing itself, or it
doesn't know it is crashing.
