### ISSUE TITLE
Crash after resume from suspend

### ISSUE THREAD

**Issue by dyfrgi** [EmmittJ/PoESkillTree#318]
After I resume my system from suspend, PoESkillTree consistently crashes when I start to interact with it again. After starting it up again it's fine. This reproduces consistently.

I don't see logs stored anywhere which might help debug as to why it's crashing. Is there some way to generate debug logs or anything else I should do to help fix this?

OS: Windows 7, 64-bit.
Version: 2.2.5

**Comment by EmmittJ** [comment]
What OS is this on? I can try and debug this, but it is going to take some time...

**Comment by EmmittJ** [comment]
Honestly, it would be easier to just close the program before sleep mode, but I can see why someone may not.

**Comment by dyfrgi** [comment]
Edited the initial comment. Was on 2.2.5 at the time; upgraded to 2.2.6 now but still get the crash.

**Comment by Falconerd** [comment]
I also have this issue. Currently running Windows 10 Pro x64.

Although this is not an issue which prevents me from using the app, it's still a bug so I thought I'd report it.

**Comment by brather1ng** [comment]
Can't reproduce this (Win 10 Home x64). Is this still an issue with the current version?

**Comment by EmmittJ** [comment]
I think it was an issue of trying to load persistentdata, but I could never get it to a state where I could debug it.

**Comment by dyfrgi** [comment]
It hasn't reproduced the last couple times I suspended. @Falconerd is this still happening for you?

**Comment by Falconerd** [comment]
@dyfrgi Yeah, it is. Just came back from being out, clicked a node and it crashed.

**Comment by brather1ng** [comment]
Hm, without it reproducing for me and with the program crashing without a proper error message, there is no way for me to fix debug this, sry.
