### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by HendrikHaase** [EmmittJ/PoESkillTree#319]
The error time: 5/6/2016 12:59 PM
Exception: System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei POESKillTree.SkillTreeFiles.SkillTree.InitNodeSurround() in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree-Drawing.cs:Zeile 1241.
   bei POESKillTree.SkillTreeFiles.SkillTree.InitializeLayers() in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree-Drawing.cs:Zeile 1288.
   bei POESKillTree.SkillTreeFiles.SkillTree..ctor(String treestring, String opsstring, Boolean displayProgress, UpdateLoadingWindow update) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:Zeile 526.
   bei POESKillTree.SkillTreeFiles.SkillTree.CreateSkillTree(StartLoadingWindow start, UpdateLoadingWindow update, CloseLoadingWindow finish) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:Zeile 771.
   bei POESKillTree.Views.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:Zeile 424.
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   bei System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   bei System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   bei MS.Internal.LoadedOrUnloadedOperation.DoWork()
   bei System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   bei System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   bei System.Windows.Interop.HwndTarget.OnResize()
   bei System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
The error time: 5/6/2016 12:59 PM
Exception: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei POESKillTree.Views.MainWindow.GetLevelAsString() in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:Zeile 1084.
   bei POESKillTree.Views.MainWindow.Window_Closing(Object sender, CancelEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:Zeile 570.
   bei System.ComponentModel.CancelEventHandler.Invoke(Object sender, CancelEventArgs e)
   bei System.Windows.Window.OnClosing(CancelEventArgs e)
   bei System.Windows.Window.WmClose()
   bei System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Windows10 x64, 2.2.6 via Installer

**Comment by HendrikHaase** [comment]
c:\GitHub\PoESkillTree_Source ... doesn't exist locally at all. Whats wrong?

**Comment by MLanghof** [comment]
Try deleting the data folder and letting it redownload the tree.

**Comment by EmmittJ** [comment]
Nothing is wrong except what looks like the skill tree data is messed up.
That folder location is from compile time. It is where I compile the source
for releases.
