### ISSUE TITLE
Skill tree generator can't be opend

### ISSUE THREAD

**Issue by AntiDog** [EmmittJ/PoESkillTree#320]
The skill tree generator located at tools -> skill tree generator can not be opened. When you klick the menue option a messagebox pops up telling you "Error: Could not open Skill Tree Generator Details: Fehler beim Vergleichen von 2 Elementen im Array" (Error when comparing 2 array elements).
![error](https://cloud.githubusercontent.com/assets/13760683/15097809/38b27bdc-1529-11e6-9a81-5c0bd4920eaa.png)

**Comment by brather1ng** [comment]
This is fixed locally, see #305.

@EmmittJ Do you plan to do a release soon or are there any Issues left you would like to see fixed before?

**Comment by EmmittJ** [comment]
Yeah, sorry. I think we need to fix up #315 and #317 before the next release. I will do some work on these when I get back from class (about 6hrs)

**Comment by EmmittJ** [comment]
@brather1ng line 325 of `AdvancedSolver.cs` with have a null exception if you check tag any node
