### ISSUE TITLE
reset button doesn't reset bandits

### ISSUE THREAD

**Issue by magus424** [EmmittJ/PoESkillTree#324]
They will stay assigned to whatever you had before, i.e. from loading a saved skill tree.

**Comment by brather1ng** [comment]
I was actually not sure if that would be the correct behaviour. But it does make sense as bandit selection is closely related to the skill tree.

**Comment by EmmittJ** [comment]
Yeah, it should be a part of a 'build'

**Comment by brather1ng** [comment]
Still not entirely sure if they should be reset, but if people complain it's trivial to undo.

**Comment by l0g0sys** [comment]
It shouldn't. That button is tree reset. I want to be able to pick 
bandit rewards and play with tree afterwards, without need to set 
rewards back each time i reset tree.

There should be "New build" menu item which would reset everything 
including bandit rewards.

**Comment by magus424** [comment]
Bandits are part of a build - reset resets the build.

**Comment by l0g0sys** [comment]
No. That reset button on screen is there to reset what you see there. 
And all you see there is level and tree. That's all this button should 
reset.

I don't think, some single button in tree panel view should reset other 
build related things which are not displayed in that tree panel.

**Comment by l0g0sys** [comment]
I think you misunderstand what we call "build" in PoESkillTree. Build is 
tree + level + metadata(note) + items + bandit rewards + more future stuff.

It was mess in past, where only thing the app was able to do was set 
your level and change your tree. Back then, everyone called it a build.

But since then, we added more features and we had to make difference 
between level + tree and build as a whole.

So that reset button still does what it was doing year - two ago, resets 
tree and level.

**Comment by EmmittJ** [comment]
I would tend to agree. 'reset' doesn't reset items, notes, etc. It has always been for the tree/level. 

Switching a build/making a new build should be the only time that bandits are reset.

**Comment by brather1ng** [comment]
It doesn't even reset levels, only the tree. So it shouldn't reset bandits and should be renamed to 'reset tree' or something.

**Comment by EmmittJ** [comment]
Hmm, you are right, but there needs to be consistency across the board with the reset button. Either it resets everything, or just the skill tree.

**Comment by l0g0sys** [comment]
Just rename it to "Reset tree".

**Comment by EmmittJ** [comment]
Do we have space?

**Comment by l0g0sys** [comment]
Hm... yeah, that might be an issue. It's already packed there.

Well, then just write into Help file, that damn button just resets tree, 
like always did :)

**Comment by MLanghof** [comment]
Just for the record: I'm quite inconvenienced by "Reset" resetting the Ascendancy class points as well. I totally think that it makes sense, but my workflow for creating a build involves lots of iterations with the "skill tagged nodes" or the skill tree generator feature, whereby I constantly reset the tree.

You could argue that the Ascendancy choices are easy to remember and I can just ignore that part until I'm done, but then some of the small Ascendancy nodes actually matter (attack speed, flask effectiveness etc.) and make quite some difference overall.

**Comment by brather1ng** [comment]
I mean, it's not like we could just make it customizable ...
(what to reset on reset click, e.g. main tree, ascendancy choices, bandits, etc.)

I'll do that as part of my pull request since I rewrote the SettingsMenuWindow already.

**Comment by magus424** [comment]
An option would be a good compromise:

    Reset button resets:
    [x] Passive tree
    [x] Ascendancy tree
    [ ] Bandits
