### ISSUE TITLE
Window title has wrong name.

### ISSUE THREAD

**Issue by l0g0sys** [EmmittJ/PoESkillTree#326]
Didn't notice this window title change (was using my 2.2.x old version due to Item Filter Editor for looong time) and I had it written in my TODO too. So it's good that it was done by someone.

But, Path of Exile should be dropped from window title as it's registered trademark. We shouldn't use someone's else trademark.

Think title should be simple like this: {build name} - {app name}
Where {app name} is "PoESkillTree - Ascendancy".

**Comment by SpaceOgre** [comment]
I agree completely with this, everywhere else we brand it as PoESkillTree.
