### ISSUE TITLE
Request - Place to add Gem Links

### ISSUE THREAD

**Issue by Dyonovan** [EmmittJ/PoESkillTree#335]
I really love this program but there just seems to be this one thing missing to make it perfect for creating builds I would like to play.

I don't think it needs to calculate into the stats, but would it be possible to add a section to place gem links. 

Maybe 2 lines of 6 gem slots and 4 line of 4 gem slots. (I think that would cover it all)

I just hate having to swap out to notepad or something else to look up what gems I want to run.

Either way, thanks for your hard work!

**Comment by Dyonovan** [comment]
Someone just suggested to me maybe just a Notes area?

**Comment by brather1ng** [comment]
For now, the build note that is already there (right click build -> build note) is probably the best place.

Eventually, extending the inventory to include visual sockets and links for gems would be nice. But that most likely won't happen in the foreseeable future.

**Comment by brather1ng** [comment]
I've thought about this a bit and I think it can be done pretty easily with a rather simple (but functional) UI. 

Something like this (accessible via the item's context menu):

![editsocketedgems](https://cloud.githubusercontent.com/assets/7596346/23186598/02860540-f888-11e6-8cff-d3c7124c48b2.png)

**Comment by EmmittJ** [comment]
You would want an easy way to differentiate the  colors of the gems. I
would say text color, but we would have a problem for those with the white
background.

**Comment by brather1ng** [comment]
How about the gem icons?

![editsocketedgemswithicons](https://cloud.githubusercontent.com/assets/7596346/23187692/14f91a92-f88c-11e6-984d-cfdaff26e945.png)

**Comment by EmmittJ** [comment]
Looks solid! I wasn't sure if they would fit in well there. Also, would
that be a searchable drop down?

**Comment by brather1ng** [comment]
Yes, that would be a searchable drop down. I hope its performance is good enough for all gems, I don't think adding category drop downs like for item crafting would be a good idea here.

**Comment by EmmittJ** [comment]
How do you account for say a helm with 2 2-links? Is that the 'group'?

**Comment by brather1ng** [comment]
Yes, 'group' are gems linked together. Don't know if/how to force a limit on number of gems in an item yet. Maybe it doesn't matter much if it allows an arbitrary number of gems (maybe just with a global limit).

**Comment by EmmittJ** [comment]
I would put that on the user or add it into the item crafting section.

**Comment by brather1ng** [comment]
Actually, that should be easy. Just set it based on the class of edited item.

Still only a mockup, but I've started implementing this on a new branch.
