### ISSUE TITLE
Save / override / build selection / comparison is awefull

### ISSUE THREAD

**Issue by restinpieces** [EmmittJ/PoESkillTree#336]
Please fix the build save and select procedure. I can't count how often I overwrote a build despite having the correct build selected. There is some stupid differentiation between single and double click or I don't know. Its really really REALLY frustrating. Its so frustrating I make back ups of the save file every time I successfully changed and saved something, because I lost so many builds.

Make it so, that only one build can be selected and it is always highlighted and always saved to. So click, double click, triple click, and all the other clicks select one "totally awesome build" and highlight it. And if you click safe it asks you, do u want to override "totally awesome build"

Make the comparison work with a drop down menu where u select on of the saved build to not get confused by which build is actually selected. 

Other then that i have no complaints program works awesome!

**Comment by EmmittJ** [comment]
You double click to 'open' a build. The name of the build you have open is
in the top left corner (title bar). The build that is open also displays a
different character icon (grayed out). You can select other builds (single
click) to compare the two trees.

Why make a second list of all the builds when we can have a single one with
easy selection?

**Comment by restinpieces** [comment]
Because sometimes compact isn't intuitive nor user friendly? The whole double click  single click is not intuitive and the two selected builds almost look the same. You don't need a full blown list. just a drop down list for the comparison build selection. There would be zero likelihood of confusion. Or heck at least give one a green and the other one a red background.

**Comment by brather1ng** [comment]
Single click selecting and double click opening something is standard behavior for pretty much everything.
