### ISSUE TITLE
C# 6

### ISSUE THREAD

**Issue by brather1ng** [EmmittJ/PoESkillTree#337]
I would like to use the features of C# 6. The only downside being that it would require everyone to use Visual Studio 2015. So if someone hasn't yet upgraded and doesn't want to, this is out of the question.

Overview over new language features: https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6

**Comment by MLanghof** [comment]
Damn, so much syntactic sugar...

**Comment by brather1ng** [comment]
It's mostly about await in catch, as that is the only thing that's more than syntactic sugar. Though, I do like the other stuff, too.

Atm, it is ugly and a lot more tedious. Something like this is necessary:

```csharp
Exception catchedEx = null;
try
{
    // Do something
}
catch (Exception e)
{
    catchedEx = e;
}
if (catchedEx != null)
    await this.ShowErrorAsync("Error", catchedEx.Message);
```

Instead of just

```csharp
try
{
    // Do something
}
catch (Exception e)
{
    await this.ShowErrorAsync("Error", e.Message);
}
```

**Comment by EmmittJ** [comment]
I don't care much @l0g0sys @SpaceOgre you guys have VS2015?

**Comment by SpaceOgre** [comment]
Atm I'm using VS2013 but getting my hands on 2015 should not be to much of a problem.

**Comment by MLanghof** [comment]
There's even a [way](http://stackoverflow.com/questions/27093908/how-to-enable-c-sharp-6-0-feature-in-visual-studio-2013) to get an old implementation of the C#6 compiler in VS2013, albeit with wonky support (IntelliSense won't understand the new stuff).

I don't see the VS2015 requirement as a problem though, either. Feel free to upgrade.

**Comment by EmmittJ** [comment]
The community edition is free I believe, and it isn't gimped if iirc

**Comment by brather1ng** [comment]
Yep, the community edition is free, allowed to be used for open source projects and feature equal to the professional edition (or whatever that one is called).

**Comment by EmmittJ** [comment]
https://www.visualstudio.com/products/compare-visual-studio-2015-products-vs

Only difference is you don't get all the team colab tools that come with professional

**Comment by brather1ng** [comment]
Then I'll use C# 6 features the next time I do something if no one stops me until then.
