### ISSUE TITLE
Help/How to

### ISSUE THREAD

**Issue by l0g0sys** [EmmittJ/PoESkillTree#34]
Think we miss most important thing in Help menu. Actual help how to work with program :))
That was my first question from my brother "Why there isn't some help".
Something like:
1) Enter level of your character [here]
2) Import complete skill tree by pasting URL [here] or just click nodes to your heart's content.
3) Import build by using menu Tools -> Download/Import items:
3.1) Type your character name [here]
3.2) Press [button] to open browser with item data from official site (which may require to login first)
3.3) In browser use 'Save Page as...' and save page at some location
3.4) Press [button] and select previously saved page
Enjoy!

**Comment by HDANILO** [comment]
When I put my char name there, the page presents only the string "false" instead of the items: https://www.pathofexile.com/character-window/get-items?character=SeekerBR

**Comment by EmmittJ** [comment]
That has been fixed and will be in the next release.

You have to use this link:
https://www.pathofexile.com/character-window/get-items?character=YourCharacterName&accountName=YourAccountName
