### ISSUE TITLE
Request - A way to select nodes without connecting them

### ISSUE THREAD

**Issue by Xolzec** [EmmittJ/PoESkillTree#340]
I was thinking that it would be really helpful to be able to select clusters of nodes without connecting them to other nodes. A sort of "pre planning mode" if you will. This way you could first pick up nodes that you know you'll take no matter what and then figure out the best way to connect them together. 

Maybe you could even somehow "lock" your must have nodes so that you can't accidentally deselect them by removing a connecting node after you exit this pre planning mode or what ever it's called.

**Comment by l0g0sys** [comment]
Hmm... thought tags are for this. At least that's exactly what i use 
tags for.

I tag all important nodes and then either use Skill tagged nodes or 
connect them by hand.

**Comment by Xolzec** [comment]
Well damn, haven't noticed that before! That does seem to do pretty much what I wanted. Didn't realize that tags in this context meant flagging nodes that you want or don't want.

Thanks!

**Comment by MLanghof** [comment]
Just for the record, you can even combine the node tagging with an automated optimizer! For example, tag all the essential nodes you want, then tell the optimizer to grab as much life as it can with the remaining points.
