### ISSUE TITLE
Character Sheet stats not updating when using gear crafted inside the program

### ISSUE THREAD

**Issue by noremac13** [EmmittJ/PoESkillTree#343]
Whenever I try to "craft" an item inside the program and equip it the character stats don't change to reflect the stats on that item.  If I import a character from the site that gear is calculated in the stats, but for some reason the gear I create inside the program isn't.  Also if I close and reopen any created gear gets unequipped but still shows up in the inventory panel even if I save the build after equipping everything.

**Comment by brather1ng** [comment]
These bugs have been fixed but the fixes are not yet released.
