### ISSUE TITLE
Crafting Item - Need new tiers and item bases

### ISSUE THREAD

**Issue by timeless00** [EmmittJ/PoESkillTree#349]
The crafting menu needs a lot of new item bases, including new tier rolls. I think currently it's missing act 4 stuff.

However I might suggest waiting until after 2.4 PoE update, as there are going to be some 32 new item bases. Would be better to get it all out of the way once after the patch.

**Comment by brather1ng** [comment]
It's all updated except the 2.4 stuff, just not released yet.

The new 2.4 bases will be added when the wiki is updated.
