### ISSUE TITLE
Dialog animations

### ISSUE THREAD

**Issue by SpaceOgre** [EmmittJ/PoESkillTree#350]
I wanted to open a discussion about the MetroDialogs and the show/hide animations. For me the animation is to long and thus the programs feels sluggish. Did a fast test and it does not seem to be possible to control the animation speed but the animation can be disabled llike this:

```
await window.ShowMetroDialogAsync(view, new MetroDialogSettings() {AnimateShow = false});
await window.HideMetroDialogAsync(view, new MetroDialogSettings() { AnimateHide = false });
```

What do the rest of you think? I'm I just to impatient? ;)

**Comment by MLanghof** [comment]
Do you mean the "fade to/from" white? I agree, that feels somewhat sluggish, I'd support removing the animation time.

**Comment by brather1ng** [comment]
There are two types of show/hide animations, the fade to/from white and one that makes the dialog itself visible or invisible. I agree that the first one is too long and I don't see any easy way to shorten it, too. I don't feel like the fading is too annoying but I wouldn't mind it being disabled.

Your code snippet only disables the fading. The dialog opacity animations require the settings to be passed to the BaseMetroDialog constructor (which isn't possible atm with how I extended it). Without the fading it would be 200ms of animation, which is perfectly fine, imo.

**Comment by SpaceOgre** [comment]
Seems reasonable, when I tested it with fading disabled it felt snappier. I think that would be enough speed up.

**Comment by SpaceOgre** [comment]
Removed the fading animation. If it feels weird we can just turn it on again.
