### ISSUE TITLE
Request:  Allow the color of highlighted nodes to be changed.

### ISSUE THREAD

**Issue by Jackalope-Gaming** [EmmittJ/PoESkillTree#351]
I've noticed at least one colorblind streamer has had issues seeing the typical red highlight.  Could there be an option to allow for the highlight color to be changed so that people with color deficiencies can find a color they can see for highlights?

**Comment by SpaceOgre** [comment]
On my phone atm so I can't confirm it but if I remember correctly this is possible to do in the settings. 
Edit -> Settings

**Comment by SpaceOgre** [comment]
Had time to check now and it is already in place in settings.
