### ISSUE TITLE
Wiki start page as changelog of unreleased changes

### ISSUE THREAD

**Issue by brather1ng** [EmmittJ/PoESkillTree#353]
Shortly before our last release I have started adding changes from commits and merges to the wiki start page (https://github.com/EmmittJ/PoESkillTree/wiki).

I think it would be a good idea if from now on everyone that commits somethings or merges PRs can add the changes there. Mainly for two reasons:

1. There is less work when releasing as the changelog is already done.
2. The chance that changes are missing from the release notes is much lower.

**Comment by SpaceOgre** [comment]
Very true, always easier to do these things straight away than to try and remember what you did 3 months ago :)

**Comment by brather1ng** [comment]
Everyone should have had the chance to comment on this by now, so I'll close this.
