### ISSUE TITLE
Update from Ascendancy to Atlas overwrote files and lost builds

### ISSUE THREAD

**Issue by feyd** [EmmittJ/PoESkillTree#354]
I just did a check for updates and it found the new atlas update. It told me this would be installed side by side with the existing version. 

It instead installed into the ascendancy folder and overwrote everything there, resulting in me losing all my saved builds.

**Comment by Joas1988** [comment]
Well not exactly build are saved in Users\{YourUserName}\AppData\Roaming\PoESkillTree - Ascendancy\PersistentData.xml. So hopefully you can recover them.

**Comment by EmmittJ** [comment]
This actually shouldn't be possible. The persistent data isn't overwritten ever in between updates. It may have changed folder locations is that what you mean?

**Comment by l0g0sys** [comment]
It will install into folder of previous version atm.
Checked Properties\Version.resx and you forgot to change AppId to new GUID value to install to new folder and new Windows registry entry not overwriting previous version.

**Comment by brather1ng** [comment]
Hm, but that shouldn't overwrite PersistentData.xml, which must have somehow been overwritten if builds were lost.

**Comment by l0g0sys** [comment]
Well, Atlas of Worlds release have own new AppData which contains empty 
PersistentData.xml which looks like "overwritten". Tho, all previous 
version builds are still in AppData folder of previous version.

**Comment by brather1ng** [comment]
> It will install into folder of previous version atm.

That's what I referred to. That shouldn't overwrite PersistentData.xml, which is what happened according to @feyd.
