### ISSUE TITLE
Can't unselect attribute once one is selected

### ISSUE THREAD

**Issue by SpaceOgre** [EmmittJ/PoESkillTree#356]
If you click on a attribute in the attribute list will be selected/highlighted, which is correct. But once this is done you can not unselect again, and each time you change the tree the selection will change to the first attribute in the list.

I'm not entirely sure about what the correct behavior should be, so here are some suggestions:
* Remember the selected attribute between changes. If the attribute is no longer available unselect.
* When clicking outside of the list unselect.

What are your opinions about it?

**Comment by brather1ng** [comment]
Is there anything the selection matters for? If there is none, I don't think this is a bug worth fixing.

**Comment by SpaceOgre** [comment]
Nope, nothing that I know about anyway. I agree it is not important, I just noticed it and now I can't unsee :P
