### ISSUE TITLE
Problems opening the application

### ISSUE THREAD

**Issue by ColonelBlues** [EmmittJ/PoESkillTree#361]
![image](https://cloud.githubusercontent.com/assets/10412620/18229666/a93aaed2-7236-11e6-99d9-a33eb9ec19ed.png)
![image](https://cloud.githubusercontent.com/assets/10412620/18229668/aceb2778-7236-11e6-988d-b421bb80927e.png)

```
The error time: 9/2/2016 2:48 PM
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at POESKillTree.Views.App.App_Startup(Object sender, StartupEventArgs e) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Views\App.xaml.cs:line 80
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
----------------------------------------------------------------
I tried uninstalling completely and reinstalling it and restarting my computer. No idea what's going on with why it's not working. I'm on windows 10 64-bit.

**Comment by Snailic** [comment]
I was also having the same issue, The error in the first box appears to be somewhat misleading as PersistentData.xml is being used by the program itself rather than another program. Delete PersistentData.xml (or move it to another location) and you can start it fine after.

**Comment by brather1ng** [comment]
Yeah, that'll probably solve it. Can you please post your broken PersistentData.xml here so we can fix the bug?

**Comment by ColonelBlues** [comment]
PersistentData.xml:
`�E�<?xml version="1.0" encoding="utf-8"?>
<PersistentData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Options>
    <Language>en-US</Language>
    <Theme>Dark</Theme>
    <Accent>Steel</Accent>
    <AttributesBarOpened>false</AttributesBarOpened>
    <CharacterSheetBarOpened>false</CharacterSheetBarOpened>
    <BuildsBarOpened>false</BuildsBarOpened>
    <TreeComparisonEnabled>false</TreeComparisonEnabled>
    <SelectedBuildIndex>-1</SelectedBuildIndex>
    <ShowAllAscendancyClasses>true</ShowAllAscendancyClasses>
    <NodeSearchHighlightColor>Red</NodeSearchHighlightColor>
    <NodeAttrHighlightColor>LawnGreen</NodeAttrHighlightColor>
    <NodeHoverHighlightColor>DodgerBlue</NodeHoverHighlightColor>
    <DownloadMissingItemImages>false</DownloadMissingItemImages>
    <ResetPreferences>MainTree AscendancyTree</ResetPreferences>
  </Options>
  <CurrentBuild>
    <Name>New Build</Name>
    <Level>1</Level>
    <Url>https://www.pathofexile.com/passive-skill-tree/AAAABAMAAA==</Url>
    <LastUpdated>0001-01-01T00:00:00</LastUpdated>
    <CustomGroups />
    <CurrentlyOpen>false</CurrentlyOpen>
    <Bandits>
      <Normal>None</Normal>
      <Cruel>None</Cruel>
      <Merciless>None</Merciless>
    </Bandits>
  </CurrentBuild>
  <Builds />
  <XmlLeagueStashes />
</PersistentData>`

PersistentData_Bad.xml:
`�E�<?xml version="1.0" encoding="utf-8"?>
<PersistentData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Options>
    <Language>en-US</Language>
    <Theme>Dark</Theme>
    <Accent>Steel</Accent>
    <AttributesBarOpened>false</AttributesBarOpened>
    <CharacterSheetBarOpened>false</CharacterSheetBarOpened>
    <BuildsBarOpened>false</BuildsBarOpened>
    <TreeComparisonEnabled>false</TreeComparisonEnabled>
    <SelectedBuildIndex>-1</SelectedBuildIndex>
    <ShowAllAscendancyClasses>true</ShowAllAscendancyClasses>
    <NodeSearchHighlightColor>Red</NodeSearchHighlightColor>
    <NodeAttrHighlightColor>LawnGreen</NodeAttrHighlightColor>
    <NodeHoverHighlightColor>DodgerBlue</NodeHoverHighlightColor>
    <DownloadMissingItemImages>false</DownloadMissingItemImages>
    <ResetPreferences>MainTree AscendancyTree</ResetPreferences>
  </Options>
  <CurrentBuild>
    <Name>New Build</Name>
    <Level>1</Level>
    <Url>https://www.pathofexile.com/passive-skill-tree/AAAABAMAAA==</Url>
    <LastUpdated>0001-01-01T00:00:00</LastUpdated>
    <CustomGroups />
    <CurrentlyOpen>false</CurrentlyOpen>
    <Bandits>
      <Normal>None</Normal>
      <Cruel>None</Cruel>
      <Merciless>None</Merciless>
    </Bandits>
  </CurrentBuild>
  <Builds />
  <XmlLeagueStashes />
</PersistentData>`

**Comment by Snailic** [comment]
> E¿<?xml version="1.0" encoding="utf-8"?>
> <PersistentData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
>   <Options>
>     <Language>en-US</Language>
>     <Theme>Dark</Theme>
>     <Accent>Steel</Accent>
>     <AttributesBarOpened>false</AttributesBarOpened>
>     <CharacterSheetBarOpened>false</CharacterSheetBarOpened>
>     <BuildsBarOpened>false</BuildsBarOpened>
>     <TreeComparisonEnabled>false</TreeComparisonEnabled>
>     <SelectedBuildIndex>-1</SelectedBuildIndex>
>     <ShowAllAscendancyClasses>true</ShowAllAscendancyClasses>
>     <NodeSearchHighlightColor>Red</NodeSearchHighlightColor>
>     <NodeAttrHighlightColor>LawnGreen</NodeAttrHighlightColor>
>     <NodeHoverHighlightColor>DodgerBlue</NodeHoverHighlightColor>
>     <DownloadMissingItemImages>false</DownloadMissingItemImages>
>     <ResetPreferences>MainTree AscendancyTree</ResetPreferences>
>   </Options>
>   <CurrentBuild>
>     <Name>New Build</Name>
>     <Level>1</Level>
>     <Url>https://www.pathofexile.com/passive-skill-tree/AAAABAMAAA==</Url>
>     <LastUpdated>0001-01-01T00:00:00</LastUpdated>
>     <CustomGroups />
>     <CurrentlyOpen>false</CurrentlyOpen>
>     <Bandits>
>       <Normal>None</Normal>
>       <Cruel>None</Cruel>
>       <Merciless>None</Merciless>
>     </Bandits>
>   </CurrentBuild>
>   <Builds />
>   <XmlLeagueStashes />
> </PersistentData>

**Comment by brather1ng** [comment]
Thanks for the files. Can't reproduce the bug with them, though.

However, the whole PersistentData related code will be changed soon, so there's a good chance this particular bug will just go away.
