### ISSUE TITLE
RegEx Issue

### ISSUE THREAD

**Issue by GeminiEngine** [EmmittJ/PoESkillTree#364]
What regex parser is it using?

I am interested in seeing anything I might want related to my build by negating what I don't want selected, but cannot use a negative look-ahead assertion "(?!Wand).*" meaning select all that does not have "Wand" in it.

**Comment by SpaceOgre** [comment]
We are using the default .Net regex parser.
`var regex = new Regex(search, RegexOptions.IgnoreCase)`
Then we use that regex on each node.

**Comment by SpaceOgre** [comment]
Did some testing and this regex is more what you need:
`^(?!Wand)(.(?!Wand))*$`

This will not filter out all wand nodes though, since the search also  looks at node names. Meaning some notables will still be marked even though they have wand properties.

**Comment by EmmittJ** [comment]
`(?!Wand).* ` isn't valid RegEx. It doesn't match any character; therefore, it matches infinitely. You can use sites like http://regexr.com/ to help you out with figuring out valid RegEx. I am going to go ahead and close this since it isn't actionable by us. If you have any more questions you will still be able to reply though.

**Comment by GeminiEngine** [comment]
First, THANK YOU, both, for your time. I have been building my search string for the last 15 mins moving towards my goal.

Second, yes I am a noob with regex, I use it occasionally on logs. However, I gave up on using regexr and others to figure out how to search the skill tree, as there is a regex mechanic I obviously am not understanding. To demonstrate, using SpaceOgre's example, which works in PoESkillTree, as I understand should highlight all of the sample text because "Wand" is no where to be found, yet it highlights nothing.

**Comment by GeminiEngine** [comment]
Hmm, after removing the things I did not want the tree remains a lot more highlighted than I expected. 

Feature request to be able to select what we search, Node name and/or Node Effects?

Again, thank you, all of you. It is your group's work that allows all to theory craft!
