### ISSUE TITLE
Repeated CtD

### ISSUE THREAD

**Issue by King-of-Limbs** [EmmittJ/PoESkillTree#366]
I always get a crash after around two minutes of using it. Tested on two Win10 PCs which did not show that behaviour before 2.4. Logfile shows nothing but successful starting up to "[14] INFO  DataLoaderExecutor - Completed loading!"

I cannot nail it down to any actions or input to the programm it closes even when not being touched for a minute.

**Comment by EmmittJ** [comment]
Does the program say anything about it crashing? I am not sure we can do anything without a bit more information.

**Comment by King-of-Limbs** [comment]
Unfortunately not. It is just like I had hit the close-button.

**Comment by EmmittJ** [comment]
Are you running an anti-virus software?

**Comment by King-of-Limbs** [comment]
Just the implemented Win10 security.

**Comment by EmmittJ** [comment]
Is there a debug.txt file in either the appdata location or local folder
(if potable install)?

**Comment by arskatb** [comment]
I started to have same problem 2 days ago.

Source
PoESkillTree

Summary
Stopped working

Date
‎10.‎9.‎2016 12.04

Problem signature
Problem Event Name:	APPCRASH
Application Name:	PoESkillTree.exe
Application Version:	2.3.0.1052
Application Timestamp:	57c7990d
Fault Module Name:	ltc_game32-116096.dll
Fault Module Version:	1.0.0.1
Fault Module Timestamp:	57cf4e9b
Exception Code:	c00000fd
Exception Offset:	00002e70
OS Version:	10.0.14393.2.0.0.256.48
Locale ID:	1035
Additional Information 1:	e991
Additional Information 2:	e9914d83b8c1c612fa137735e40aca93
Additional Information 3:	a97e
Additional Information 4:	a97e58e24cf03b62995f64253cf6c289

Extra information about the problem
Bucket ID:	550fcc03453949f1c81f31aec0ddaa68 (108389742731)

**Comment by King-of-Limbs** [comment]
There is no debug.txt in my folder (portable ver). Is there a way I can create one?

And sorry for mixing up Version numbers, thought you stick with PoE versions, I am on SkillTree 2.3 too.

**Comment by brather1ng** [comment]
@arskatb Your problem seems to be a different one. @King-of-Limbs says it behaves as if it was closed. The dll that leads to the crash (ltc_game32-...dll) is not one used by our program. Do you by any chance have Raptr installed (https://community.skype.com/t5/Windows-archive/skype-crashes-when-i-start-it-win-7/td-p/3925435)?

@King-of-Limbs if there is no debug.txt, it is not crashing by throwing an exception in code handled by us. If you do some changes (without saving them), e.g. skilling a node, are they still there when you restart? If yes, it is actually properly closing. If no, it crashes because of something that's probably outside our control.

**Comment by arskatb** [comment]
@brather1ng behavior was similar, no warning or notification. But in this case it was playstv. Havent had any issue till now. Dunno why this started to happen (no recent playtv updates etc).

**Comment by brather1ng** [comment]
You got the error information, so that's at least some kind of notification. I have no idea why this happens either, but I don't think it is something we can fix.

**Comment by King-of-Limbs** [comment]
The changes I make are gone after restarting unfortunately.

**Comment by EmmittJ** [comment]
Try uninstalling the program, and deleting the folder in `%appdata%` then reinstall. I can't think of too much more to-do since it sounds like it might be being forced closed (the app can close and not save data). You sure you have no anti-virus/malware programs running?

**Comment by brather1ng** [comment]
For the off chance that your crash *is* related to the other one, do you have Raptr or PlaysTV installed (or a .dll-file starting with ltc_game32 on your computer)?

**Comment by King-of-Limbs** [comment]
Well, yes of course I had this silly AMD bloatware on my PC. I uninstalled Raptr and PlaysTV and SkillTree seems to run fine now. Must have come in with eiter your, or what I think ist more likely, one of their latest updates. Weird interaction though. Thanks guys for helping out.
