### ISSUE TITLE
Tree opens but I can't view the tree

### ISSUE THREAD

**Issue by Bren002** [EmmittJ/PoESkillTree#374]
I have a video of my issue I have tried uninstall it and reinstall https://www.youtube.com/watch?v=KvI3kJAMj6g

**Comment by EmmittJ** [comment]
https://github.com/EmmittJ/PoESkillTree/issues/366

Do you happen to have Raptr or PlayTV installed?

**Comment by Bren002** [comment]
no

**Comment by EmmittJ** [comment]
Do you have any sort of anti-virus? They sometimes like to kill programs without alerting you.

**Comment by Bren002** [comment]
Nothing on my computer has changed it started 3 days ago

**Comment by EmmittJ** [comment]
Alright, uninstall and delete the `PersistentData.xml` in `%appdata%` in a folder that should be named `PoESkilTree - Atlas of Worlds` or something similar then try reinstalling.

**Comment by Bren002** [comment]
awesome it worked thanks
