### ISSUE TITLE
Character sheet cut off

### ISSUE THREAD

**Issue by MLanghof** [EmmittJ/PoESkillTree#376]
[Image](http://image.prntscr.com/image/1daf3882ea7c4818b0140700582673c1.png)

Just noticed while doing random testing.

**Comment by SpaceOgre** [comment]
I'm not seeing this on my end.

**Comment by MLanghof** [comment]
Ok, bisection shows me that a4f0fc7bf7e89e45ef235d8598491469e09e16db is the first bad commit. I'll play around with those changes a bit and see where it takes me.

**Comment by MLanghof** [comment]
Well, by the looks of it the negative margin of the grid inside the expander isn't accounted for properly, but since it works for you it's probably a bug in my WPF version (no idea what part of my .NET/WPF environment/setup is responsible, any pointers appreciated).

**Comment by SpaceOgre** [comment]
Maybe try and restore the MahApps via NuGet. Since the commit you pointed to updated the MahApps version so you might not have it up to date locally.

**Comment by MLanghof** [comment]
Mine is at 1.2.4, allegedly the latest stable. Uninstalled it, reinstalled, same issue. Tried a few earlier versions, same problem, tried 1.3.0 pre-release, no fix. :(
Tried updating all other packages, nothing changed.

**Comment by EmmittJ** [comment]
I don't see this on my end either. What resolution are you at?

**Comment by MLanghof** [comment]
2160x1440, high DPI (Surface 3) on Windows 8.1 Pro. The resolution would be a weird reason though, given how in this the drawing is just restricted to the "normal" expander area, breaking negative margins for content items...

**Comment by EmmittJ** [comment]
Yeah, I don't know. It was just a thought

**Comment by EmmittJ** [comment]
Is there anyway you can reproduce this? Is it on startup or after a few clicks around? I have been messing around in the menus and can;t make this happen

**Comment by MLanghof** [comment]
It happens consistently every time I use the program (after a4f0fc7 was introduced). First thing I do is expand the character panel (or, if it was expanded when closing, I don't have to do anything). In fact, I haven't found a single way to *not* have this happen after that commit.

**Comment by EmmittJ** [comment]
Does this happen with the released version of the tree or just when you
build it?

**Comment by MLanghof** [comment]
Just tried with the released version (installed in portable mode) and the same issue happens.

**Comment by EmmittJ** [comment]
Is this still happening?

**Comment by MLanghof** [comment]
When I checked a week ago, it did still happen. I haven't put additional effort into solving it since my last comment here though.

**Comment by Zavake** [comment]
I have noticed the same issue after updating tree assets, also happens with the newest version.

**Comment by Whaffles** [comment]
Sorry this is a bit necro, but I suffer from this issue as well and I think I've found a way to reproduce it (and serve as workaround for others). Resizing the window (vertically only; horizontally has no effect), causes that portion of the character sheet to disappear and reappear.

**Comment by MLanghof** [comment]
Huh, interesting. Vertical resizing has no effect in my case.

However, I found out that resizing horizontally makes the character sheet appear in full iff it covers the entire width of the window. Additionally, there is some weirdness with the skill tree rendering, I'll just let this gif speak though:

http://imgur.com/IvCQrZz

**Comment by brather1ng** [comment]
I can't get it to happen with resizing. If someone doesn't mind debugging it, you could try reducing MainWindow to a minimal version that is still bugged and open an issue on that in the MahApps.Metro repo, if it seems to be caused by MahApps.

I can reproduce the tree rendering cutoff, but that seems to only happen for widths where the program is unusable anyway.

**Comment by MLanghof** [comment]
Yay, found the offender!

Removing [this one line](https://github.com/EmmittJ/PoESkillTree/blob/master/WPFSKillTree/Views/MainWindow.xaml#L48) fixes the issue for me.

**Comment by MLanghof** [comment]
Ok, before I open an issue in the MahApps.Metro repo, can somebody please check out https://github.com/MLanghof/ExpanderBugRedux and report on it?
Especially @Whaffles, can you tell me if you experience the same issue in that reduced test case? Can you add some information about your system etc. that I'll be able to add to the issue eventually?

**Comment by Whaffles** [comment]
Ah, @MLanghof , seeing as I'm just a user with a rather finite amount of applicable knowledge in this environment...could you please let me know how I can run your test environment so I can report on it for you? X_X

**Comment by MLanghof** [comment]
Ok, I wrestled my way through the release scripts we have. Can you two try out [this](https://github.com/MLanghof/ExpanderBugRedux/releases/tag/1.0)?

**Comment by brather1ng** [comment]
It's too late now, but I think you can just zip the bin/Debug or bin/Release folder and that should work for others.

**Comment by MLanghof** [comment]
Hm yeah. I was turned off by the few KB executable size, but didn't think of the fact that you can just have the dll files next to it under Windows. Meh, at least I have a better idea of how the build scripts work now. Plus ripping things apart is fun :D

**Comment by Whaffles** [comment]
Okay! I ran it with your beautifully hacky .exe, and I got...completely different results this time. Vertical resizing has no effect, and horizontal resizing has no effect UNTIL there is not enough horizontal space on the screen for the widget, at which point the whole widget (save for the missing pixel or two on the right) is visible.

Here's a gif that hopefully works long enough for you to see it:
https://gyazo.com/2545f2830f579d52d744d8ba11ec97e0

I also brought up the actual release version of POESkilltree and tried to replicate what I just described, and simply couldn't. >_<

Also, since I haven't put my system specs here yet, so I'm running Windows 7 Pro at 1920 x 1080, using skilltree version 2.5.

I also tried screwing about with my resolution and doing tests with this a few times, and saw no change.

**Comment by MLanghof** [comment]
> horizontal resizing has no effect UNTIL there is not enough horizontal space on the screen for the widget, at which point the whole widget (save for the missing pixel or two on the right) is visible.

Alright, that's consistent with me (which is good I guess).

**Comment by Whaffles** [comment]
Well, progress!

If there's anything else you want me to try to reproduce or catalogue, just ask and I'll hear it.
