### ISSUE TITLE
Missing text for talent

### ISSUE THREAD

**Issue by Hapseleg** [EmmittJ/PoESkillTree#377]
Hi, the elementlist talent "Shaper of Desolation" is missing text.

Keep up the good work :) love your application.

**Comment by brather1ng** [comment]
This was missing in the data GGG provided. You should be able to fix it by redownloading the skill tree data (Tools ->Program Assets -> Redownload Skill Tree Assets).

**Comment by Hapseleg** [comment]
Ah okay thanks :)
