### ISSUE TITLE
Putting your computer to sleep with skill tree up causes it to crash when you come out of sleep to use it.

### ISSUE THREAD

**Issue by mmacdermaid** [EmmittJ/PoESkillTree#379]
Put compute to sleep with skill tree up.

Un-sleep it.

I click drag then mousewheel zoom and it crashes 100% of the time.

**Comment by brather1ng** [comment]
As said in #318, we most likely can't fix this, I can't even reproduce it and others can't get it to a point that is debuggable. But I'll keep this one open to prevent duplicates.

**Comment by EmmittJ** [comment]
I still can't get this to happen. What operating system do you happen to be on?

**Comment by mmacdermaid** [comment]
Win7

**Comment by mmacdermaid** [comment]
This no longer happens in on https://github.com/EmmittJ/PoESkillTree/releases/tag/2.4.0

**Comment by brather1ng** [comment]
Thanks for the update!

Next try at closing this bug in the hopes its fixed for everyone.
