### ISSUE TITLE
Attack speed "more" qualifier calculated incorrectly

### ISSUE THREAD

**Issue by jrobinson3k1** [EmmittJ/PoESkillTree#380]
Currently, "more attack speed" quantities are being added together before being combined with "increased attack speed". "more" qualifiers should be multiplied together, not summed.

Source: http://pathofexile.gamepedia.com/Stat#Flat.2C_additive_and_multiplicative_stats

Example:
76% increased attack speed (from tree)
10% more attack speed (from DW)
93% more attack speed (L19 Multistrike)

Current: (1 + 0.76) * (1 + 1.03) = 3.5728
Correct: (1 + 0.76) * (1 + 0.10) * (1 + 0.93) = 3.73648

Relevant source file: Compute.cs, Lines 627-647

I'm not sure if this is globally miscalculated in the app for other types. I have not checked.

**Comment by jrobinson3k1** [comment]
I'm working on a PR, but I'm not very familiar with the source code yet and don't primarily code in C#, so it'll probably be very rough around the edges.

**Comment by EmmittJ** [comment]
Should be a pretty simple change. You add 1 to the value and multiply then
together. Currently they are summed, so you would just need to change the
one line. (Two in this case because less is also calculated wrongly)
