### ISSUE TITLE
[Bug] in the total attribute stash : Life regen

### ISSUE THREAD

**Issue by Elgin675** [EmmittJ/PoESkillTree#383]
Hello :) !

Thank's for this fantastic tool :) !
There is a bug in my **total attribute** stash : the life regen is "blocked" at 9.9 Life Regenered per second.

Strange bug ^^ !

![join](https://cloud.githubusercontent.com/assets/22501336/18918758/17919332-859c-11e6-9e61-c37b2cfb6c81.png)

Another thing : it is possible to place a jewell in the skill tree ?
Thank's ;) !

**Comment by EmmittJ** [comment]
There shouldn't be any reason this happens. Is it stuck at 9.9 as the top
end?

**Comment by EmmittJ** [comment]
OK, does any of your gear have life regen per second? This is a flat amount
and not the % from the tree

**Comment by Elgin675** [comment]
My bad, another time, you right :(... Sorry !

Maybe it is a stupid question, but why in the **total attribute** stash it is not the **total** life regen stat here :) ? Because as you can see, here it's only the Item Attributes display, not the total.

It's normal ?

Elgin

**Comment by EmmittJ** [comment]
It is the total `flat life regenerated per second`; this is currently only
an item mod. You might be looking for `#% of life regenerated per second`?
These two stats are different.

**Comment by Elgin675** [comment]
Ok i understand. But I maintain that the total life regeneration (in life / s) would be welcome;) : currently we have to do the math manually (total life x % life regen).

Yet in the **Character Sheet**, the total life / armour / EPDR / Evasion / Resists displayed is the **final real** value of character.
But the life regen in this sheet displayed only the flat regen :).

I think a synthesis with the final values - including the life regen - would be most helpful / logical, always in this **Character Sheet** of course :).
This is just my opinion :).

Thanks for reading me :).
Elgin

**Comment by EmmittJ** [comment]
I don't know all of what you have, tree/gear wise, but I am not at a
computer to check and see if life regen is being calculated. Do you have
any % life regen on your tree? And does the character sheet change if you
skill/unskill % life regen?

**Comment by Elgin675** [comment]
Sorry, I speak bad English, so maybe I do not explain properly :(.

I post a screenshot, maybe it's better :) :

![cap](https://cloud.githubusercontent.com/assets/22501336/18926722/450df70c-85b9-11e6-92e7-3f5c62bf3c24.png)

The passive skill tree is https://www.pathofexile.com/passive-skill-tree/AAAABAEBAAHnBLMFLQbGCZYLYQ48EuEUIBRNFHEWbxa7GJEaOBpVITQnLy3SNI426DkOOlI8BTwtPfxBP0MxR35M_1BHUeZVqVhjWfNfP2EhZU1mnmebaPJqAWvZcg9yqXTtdqx4enrve4x82X31ggeDX4PMhNmE74Y7h2qMz49gkFWRzpSHl3mXtJ7Fnz6iAKLqqSeplKyqrY2uPq9stC-3PrvtvJ-9Nr6nwAHAZsQVxPbGrsbYz37WWNl82sHfsuNq5FHqGO8O73zwH_JB8430g_ZI9zL3ufjr-tL8Sw==

So yes, I have % life regen in tree :). And no, the character sheet not change when I skill / unskill % life regen.

Thank's :).

**Comment by EmmittJ** [comment]
I understand, no worries. Alright, so % life regen isn't being used in the
character sheet. I will look into this. Thanks for the report :)

**Comment by Elgin675** [comment]
:) !

No, thank YOU :) !

PS : If it helps, here the few differences that do not match 100% (I correct the screenshot) :

![cap](https://cloud.githubusercontent.com/assets/22501336/18927373/e64dc690-85bb-11e6-9bb1-dfc9b704e83a.png)

That's it :) !

Elgin

**Comment by Elgin675** [comment]
PS : and here the gear :) :

![cap2](https://cloud.githubusercontent.com/assets/22501336/18927754/77a9072a-85bd-11e6-9c51-9aedf50d2189.png)![cap3](https://cloud.githubusercontent.com/assets/22501336/18927755/77ab2974-85bd-11e6-9e80-27589eede4d9.png)
![cap4](https://cloud.githubusercontent.com/assets/22501336/18927756/77ad86ce-85bd-11e6-95d8-495a9295e7cd.png)
