### ISSUE TITLE
[Bug] Total Maximum Endurance Charges

### ISSUE THREAD

**Issue by Elgin675** [EmmittJ/PoESkillTree#384]
Hello :) !

Another bug here :) : I have a Juggernaut character, with the "Unflinching" ascendancy node (+1 To Maximum Endurance Charges)

I have keep 3 anothers **"+1 To Maximum Endurance Charges"** (Endurance, Stamina, and Vigour), for a total of 7 Endurances Charges.

But the **Passive attributes** stash display **"+8 To Maximum Endurance Charges"**, insteed 7, as you can see :

![cap](https://cloud.githubusercontent.com/assets/22501336/18920684/6e54b59a-85a2-11e6-803c-68a296fc5602.png)
Physical Damage and resistances uses this stat too.

**Comment by brather1ng** [comment]
Can't reproduce this. Can you post your tree url?

You may have an item equipped that gives an extra endurance charge.

**Comment by EmmittJ** [comment]
Also, do you have Oak selected as your last bandit reward?

**Comment by Elgin675** [comment]
> You may have an item equipped that gives an extra endurance charge.
Nop ! I you guaranteed that.
Furthermore, I have send the passive attribute here :).

> Also, do you have Oak selected as your last bandit reward?
I'm a very stupid Man ! Really !!! I have not verified, because I thought I had chosen Kraityn !!!

Very sorry for that, I'm confused...
