### ISSUE TITLE
New (soft and little) bug in the Character Sheet :).

### ISSUE THREAD

**Issue by Elgin675** [EmmittJ/PoESkillTree#385]
Hello :) ! It's me again ;) !

Thank's for the new version ; the problem of **"Energy Shield Recharge per Second"** and **"Life Regeneration per Second"**, in the Character Sheet, are succesful solved :) !!!

But unfortunately, another bug is appeared : the **"Estimated Physical Damage reduction"** is wrong (it was OK yesterday, before the last update).

![cap](https://cloud.githubusercontent.com/assets/22501336/18962767/6e1d7bea-8672-11e6-92e9-eb9e8c1814e8.png)

I join the passive skill [**here**](https://www.pathofexile.com/passive-skill-tree/AAAABAEBAAHnBLMFLQbGCZYLYQ48EuEUIBRNFHEWbxa7GJEaOBpVITQnLy3SNI426DkOOlI8BTwtPfxBP0MxR35M_1BHUeZVqVhjWfNfP2EhZU1mnmebaPJqAWvZcg9yqXTtdqx4enrve4x82X31ggeDX4PMhNmE74Y7h2qMz49gkFWRzpSHl3mXtJ7Fnz6iAKLqqSeplKyqrY2uPq9stC-3PrvtvJ-9Nr6nwAHAZsQVxPbGrsbYz37WWNl82sHfsuNq5FHqGO8O73zwH_JB8430g_ZI9zL3ufjr-tL8Sw==), and the equipement :

![cap2](https://cloud.githubusercontent.com/assets/22501336/18962906/e95f2c5e-8672-11e6-9f97-bd73bcacb08a.png)![cap3](https://cloud.githubusercontent.com/assets/22501336/18962908/e965e95e-8672-11e6-906a-dbef7823edae.png)
![cap4](https://cloud.githubusercontent.com/assets/22501336/18962907/e95fea9a-8672-11e6-878b-3bdda4d0dfe7.png)

Thanks for reading ;) !

Elgin

**Comment by EmmittJ** [comment]
This one I won't be fixed. As a community there is a lot of information we just don't have. Basically we are missing average monster damage, so I updated the damage formula to the last one we were told. It got worse because the monster damage formula we has sucks.

**Comment by Elgin675** [comment]
I understand :).

Thank's for reading :).
