### ISSUE TITLE
Crash on "Check for Updates"

### ISSUE THREAD

**Issue by poeuser** [EmmittJ/PoESkillTree#388]
Updated from 2.3.0 installer to 2.4.0pre installer, everything seems to work fine. However, when clicking on `Help > Check for Updates`, it _instantly_ crashes.

[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/513462/debug.txt)

**Comment by brather1ng** [comment]
It can't handle non numerical versions (the "pre" part). You can't upgrade from/to such a release.

**Comment by EmmittJ** [comment]
I recall doing a pre-release like this before. Also, it seems like an odd
stipulation.

On Oct 6, 2016 4:16 AM, "brather1ng" <notifications@github.com> wrote:

It can't handle non numerical versions (the "pre" part). You can't upgrade
from/to such a release.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/EmmittJ/PoESkillTree/issues/388#issuecomment-251934029>,
or mute the thread

**Comment by EmmittJ** [comment]
> So pre-releases or release canditates should be tagged X.Y.Zpre1,
X.Y.Zpre2 or X.Y.Zrc1 and such (no underscores and dashes).

I have definitely done it before.

**Comment by l0g0sys** [comment]
yeah, but think there weren't automatic updates back then.

and centralized version number used everywhere.

**Comment by EmmittJ** [comment]
Hmm, the point of a pre-release would be to view the next version coming out, so how should that situation work? If I release 2.4.0pre the next version should be a release of 2.4.0, right?

**Comment by l0g0sys** [comment]
Yeah, but common version comparison methods doesn't work with 
non-standard version numbers :(

Guess, we should just abandon such version naming. Pre-release is 
determined by GitHub release flag anyway.

Even if we made own version comparison method for app, not sure it's 
possible to override it for installer.

**Comment by EmmittJ** [comment]
You can't have the same tag name, so a pre-release is really just another release with a flag that is basically useless.

**Comment by brather1ng** [comment]
These problems are not with the installer, they are because the Update functionality uses the built-in version comparision stuff (which wasn't a problem until now). Don't know if the installer has a problem with these.

**Comment by l0g0sys** [comment]
No, it's not.

What I'm saying is, that while we can write own method for PoESkillTree 
app, I'm not sure you can do it for installer, which also does version 
comparison of files being installed.

Actually it looks into file properties where only standard version can 
be used. So even 2.4.0pre will be written in DLLs/EXEs like 
2.4.0.(build) and non-prerelease would be written as 2.4.0.(build) 
again. Just build part would be higher.

I'm not sure the work and possible complications are worth for having 
cool looking version names just for pre-releases.

**Comment by EmmittJ** [comment]
It is pretty easy to change the tag names. I guess releases will have to
just be a bumped up version number.

**Comment by l0g0sys** [comment]
Yeah, problem solved, no work needed :)

Just Wiki about making releases should be updated, that standard version 
strings without non-numeric characters should be used.
