### ISSUE TITLE
Equipment Tab needs a way to move your view

### ISSUE THREAD

**Issue by mkaranta** [EmmittJ/PoESkillTree#389]
The Equipment slots are cut off and the only way to access them is to widen the program window.

A scrollbar or click and drag like the passive tree would work.

![equipment_move](https://cloud.githubusercontent.com/assets/4672503/19214425/9942e978-8d51-11e6-820e-9e67405dc51b.png)

**Comment by brather1ng** [comment]
You can hide "Attributes" and "Saved Builds" by clicking on them. That should give it enough space.

**Comment by mkaranta** [comment]
While this is a good workaround at the example resolution, the underlying issue is still there. 

Even with all the tabs closed you need a minimum of ~1200px width to see everything.
Since the stash has a scrollbar, you only need a minimum of ~650px height so that's less of an issue.
