### ISSUE TITLE
[ver 2.4.0pre] Attributes don't update properly when discarding changes to a build.

### ISSUE THREAD

**Issue by Tahj42** [EmmittJ/PoESkillTree#391]
I've been able to reproduce this fairly easily. Just load a saved build, reset, discard changes and the character stats still display the base stats instead of the saved build values.

**Comment by brather1ng** [comment]
This seems to have been unintentionally fixed. I can reproduce it with the last release but not with the development version.

If it is not fixed for you with the next release, just reopen this issue.
