### ISSUE TITLE
PoeSkillTree 2.4.1 running but not visible

### ISSUE THREAD

**Issue by xPhool** [EmmittJ/PoESkillTree#397]
So this is an issue that I didnt have with the 2.3 version. Everything seems to run normally, except for the fact that its invisible.
![crtl tab](https://cloud.githubusercontent.com/assets/23579145/20455370/8405a062-ae5a-11e6-8a59-98cf8968580f.JPG)

When I close it, I get an error which is displayed in the log
[main.txt](https://github.com/EmmittJ/PoESkillTree/files/601427/main.txt)

I did try a few standard things like: running as administrator and various compatibility modes.
I also removed and reinstalled it multiple times.

**Comment by brather1ng** [comment]
The crash is because PersistentData is never initialized, which is probably because the window is not loaded. So there must be some kind of hangup/endless loop at the start of the program.

That will be pretty hard to fix for us as I don't think we will be able to reproduce it. Does it happen with both the zip and the installer version?

**Comment by xPhool** [comment]
Yes. It does happen with both versions. It already happened in the beta version which I downloaded about three days ago.

I also forgot to add this 
[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/601731/debug.txt)

**Comment by xPhool** [comment]
Installed it with option "portable device" instead of standard and it seems to run perfectly fine now.

**Comment by EmmittJ** [comment]
https://www.reddit.com/r/pathofexile/comments/5dptmw/poeskilltree_241_new_saved_build_system_bug_fixes/da6ostj/

This person had the same error, but they were actually able to start the
program. I'm not sure what is different between the two errors.

**Comment by xPhool** [comment]
To me it doesn't seem like the error is connected to the fact that the window isn't showing up, since he didn't have this problem.
I had the same Issue with the builds. None of them were showing up, which I assumed was normal since I installed it to another folder and kept the old version. I just copied the build-links to the new one and saved them.

**Comment by EmmittJ** [comment]
Ah, I see. Yeah, the builds was what I got out of debug.txt. Glad your
issue was sort of fixed. I'm still not sure why the window wouldn't
appear.

**Comment by xPhool** [comment]
What's the difference between the standard and the portable version anyway?

**Comment by EmmittJ** [comment]
Portable isn't installed. It is self contained in the folder. Standard is
like any other windows program and data is stored in AppData
