### ISSUE TITLE
[Crash] Data\PseudoAttributes is not empty.

### ISSUE THREAD

**Issue by ibarmin** [EmmittJ/PoESkillTree#398]
[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/601498/debug.txt)
Crash happens on startup, tree is visible on the background
Data\PseudoAttributes has no files in it

**Comment by MLanghof** [comment]
The correct message is "make sure that ...\Data\PseudoAttributes is not empty". It's crashing *because* it's empty.

**Comment by brather1ng** [comment]
How did you install the program? The installer and the zip contain these, so they should be copied to the correct directory.

You can manually copy the files from the portable release (https://github.com/EmmittJ/PoESkillTree/releases/download/2.4.1/PoESkillTree-AtlasofWorlds-2.4.1.zip) to that directory and it should work again.

**Comment by ibarmin** [comment]
@brather1ng
i clicked on exe file from download page Emmit linked on reddit.
i suppose, i'll reinstall

@MLanghof
well, it was either current title or 200+ symbols one with full pathing.
and i already said folder was empty

**Comment by brather1ng** [comment]
Weird, if reinstalling doesn't help, what I've written above should:

> You can manually copy the files from the portable release (https://github.com/EmmittJ/PoESkillTree/releases/download/2.4.1/PoESkillTree-AtlasofWorlds-2.4.1.zip) to that directory and it should work again.

**Comment by ibarmin** [comment]
i did fix this with simple reinstall (without deleting anything)

**Comment by brather1ng** [comment]
Ok, closing this then, as I have no idea how to even start searching for the bug.
