### ISSUE TITLE
Strange saving/loading behaviour

### ISSUE THREAD

**Issue by 852Foofer** [EmmittJ/PoESkillTree#400]
I didn't use PoeSkillTree for a while but now that I do use it again I find the build saving/loading behaviour extremely strange and unintuitive. For some reason the program seems to automatically save changes. Sometimes I create a build and then re-iterate it entirely. When I want to go back to the original version, I used to be able to just 'load' the previously saved version. Now it won't let me. The changes I made are automatically saved. I have to start a new build for each iteration.

I hope you get what I am saying. It's really not that easy to explain. But something definitely feels way off!

**Comment by EmmittJ** [comment]
The program doesn't auto save any changes. Can you give me steps to reproduce the program auto-saving?

**Comment by SpaceOgre** [comment]
The program now keeps a dirty state of the current build, that is it marks if you change anything. This is shown with an asterisk (*).  If you want to you can discard all the changes done, but on mobile atm so I can't post a screenshot.

**Comment by 852Foofer** [comment]
Thanks for the heads up. It's exactly like SpaceOgre said.
I used to create a build, save, then change a few points around and if I didn't like it I would just hit 'load build' again so that the previously saved version would come back up. This doesn't work anymore. Instead you have to rightclick the build, then hit 'Discard changes' - which is incredibly unintuitive and awkward to use if you ask me. 

Probably related to this issue: I can no longer delete ALL the builds. It gives me an 'The currently opened build can not be deleted.' error when I try to delete the last one. 

I guess it all boils down to the fact that there's no longer a 'neutral mode' where you can freely allocate points and save when you're finished. Instead you now have to always work inside a currently open build. I used to be able to just launch the program and start allocating points, then hit save and name the build. Now I have to first create a build (name and 'save' it) and then allocate points.

It doesn't seem like much but for me it is incredibly disruptive when trying to come up with builds.
I am sorry if my explanations are lacking. Engrish hard.

**Comment by brather1ng** [comment]
This now basically works like every other program that uses with files, so I don't really see where it would be unintuitive. The problem probably is that this system work worse for experimentation (and much better for storage and organization) than what we had before. Maybe we can change it to only require naming on save, but that's about as much as we can do while keeping it file based.

**Comment by SpaceOgre** [comment]
Yeah I think it would be good to be able to start a new build without having to name it first, just like you can start writing a new Word document without first naming it/saving it.

**Comment by 852Foofer** [comment]
> file based

Ah yes! That's exactly what it feels like. It is indeed way better for storage and organization. I just don't use the program for that. I barely store anything :P It's all experimentation for me, so perhaps that's why it feels unintuitive for me. Thanks for clearifying. Issue can be closed I assume

**Comment by EmmittJ** [comment]
I also think people like to reopen already open builds, so we might be able
to something like that? It would be like closing a file without saving and
reopening it.

**Comment by brather1ng** [comment]
Isn't that exactly what "discard changes" does?

**Comment by EmmittJ** [comment]
Yes, but I don't think people like it being hidden behind the right click
menu

**Comment by brather1ng** [comment]
Discarding could get a menu entry and keyboard shortcut (for the current build). Making it another button under the build list would be too much clutter imo.

**Comment by EmmittJ** [comment]
If the a build is double clicked and has changes to discard then prompt to
discard changes

**Comment by brather1ng** [comment]
I don't really like that idea. It wouldn't save much time as opposed to a keyboard shortcut or the context menu entry and would require different double click behaviours for the current build (ask for discarding changes) and other builds (load it). Asking to discard when loading other builds would be annyoing, imo.

I think this is mainly just an issue of people being used to the weird behaviour we had for a long time. It should be fine after a bit of getting used to it.

**Comment by 852Foofer** [comment]
I 100% agree with EmmittJ, if my opinion counts at all.
Personally I don't use any key shortcuts in any program other than ctrl c/v and ctrl z. I also don't know of anyone who really does use a lot of shortcuts either. Perhaps its a thing tech afine people love but I think for the general public, shortcuts really are not a thing. The dropdown menu-option is absolutely weird if you ask me. It took me hours to figure out it was a thing. And even now I rarely use it. It feels so weird! 
I would totally prefere a discard prompt to the current solution.

**Comment by EmmittJ** [comment]
Sorry, I don't think I made my statement too clear. This prompt would only appear if you are trying to load the current build over again. It would just prompt the user to discard changes. I don't think hotkeys are really used by the average user. 

```
if current_build && build has changes:
    prompt for discard
else
    do current stuff
```

**Comment by brather1ng** [comment]
Implemented both the naming on first save and not on new build creation, and the double click discarding,
