### ISSUE TITLE
Importing a build from fullscreen URL causes crash

### ISSUE THREAD

**Issue by gitdash** [EmmittJ/PoESkillTree#401]
Stack indicates that it's a NRE in the serializer:
`Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at POESKillTree.Model.Serialization.PersistentDataDeserializerCurrent.<ImportBuildAsync>d__7.MoveNext() in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Model\Serialization\PersistentDataDeserializerCurrent.cs:line 125`

For example, this non-fullscreen link loads correctly: https://www.pathofexile.com/passive-skill-tree/AAAABAMAAAN1BAcRDxEtFLAWbxbzF1QabBqBHwIkqiTYJjwqjSycL502xTbYNuk6WEWdSRtMLVF0UilTUlPUVcZV4FhaWHdfBGSdakNrF3yDf8aCHoPbg_eFMoVtiEKNgo6-j_qRK5LBkyeVIJrgna6fAaKjppmnCKyYvOrAVMHFwfPR5NWB2CTfsONq6-7r9ewY7FXxbPId

And the fullscreen variant causes the program to crash: https://www.pathofexile.com/fullscreen-passive-skill-tree/AAAABAMAAQN1BAcRDxEtFLAWbxbzF1QabBqBHwIkqiTYJjwqjSycL502xTbYNuk6WEWdSRtMLVF0UilTUlPUVcZV4FhaWHdfBGSdakNrF3yDf8aCHoPbg_eFMoVtiEKNgo6-j_qRK5LBkyeVIJrgna6fAaKjppmnCKyYvOrAVMHFwfPR5NWB2CTfsONq6-7r9ewY7FXxbPId

**Comment by EmmittJ** [comment]
I don't have a problem with either of those links

**Comment by EmmittJ** [comment]
Looks like it is only sometimes a problem (mainly on new builds)

`SkillTree.cs` line `1412` is the problem if someone gets to it before me @brather1ng

**Comment by EmmittJ** [comment]
Actually all three of those methods don't work properly

**Comment by SpaceOgre** [comment]
It seems that PropertyChanged fires for the BuildViewModel before the one for CurrentBuild.

**Comment by brather1ng** [comment]
@SpaceOgre's fix makes sense. Everything assumes that the TreeUrl is already normalized and the tree text box should be the only place where other urls can be entered. So setting the url by normalizing it first (`LoadBuildFromUrlAsync()`) seems to be the proper way to me. (except the `_skipLoadOnCurrentBuildTreeChange` changes, as setting this to `true` causes the tree to not be actually loaded by the SkillTree stuff)
