### ISSUE TITLE
Usability has gown down in newer versions (imo)

### ISSUE THREAD

**Issue by mmacdermaid** [EmmittJ/PoESkillTree#405]
Two major problems.

When you click on the reset button it resets the saved version of the build I was working on.  Previously this would keep whatever you have saved set in stone, and not modify what you are working on.

Pasting new skill trees overwrites the current saved build I have selected.  Previously this automatically pasted in a new sandbox tree.  

People obviously share trees constantly and it's usual for me to pop open skill tree planner, click reset, paste build, and see what they are working with.  The current functionality seems to completely ruin this efficient workflow.  I have to click new top level build (deal with the slowly loading UI.  The old UI without transitions was so much snappier), create a name for something when I don't even know what it might be, paste a URL into that and work with that.

If I have a saved build I want to it stay saved.  For the love of god please change it back, or make it an option to have old functionality as this completely ruins the skill tree planner experience for me and others (I asked around).

**Comment by EmmittJ** [comment]
Your second has been fixed, but it has not been released yet. We have added
a split button, so you can choose how to load a new tree (current build or
new build).

Builds are now like files (have been for a release or so). This means if
you want a new tree then you will have to make one (ctrl+n or File->New
Build). Reset actually hasn't changed functionality at all. It has always
done the same thing. You can also discard changes from a build if you don't
want to save it.

**Comment by mmacdermaid** [comment]
>Reset actually hasn't changed functionality at all. It has always
done the same thing.

Clicking reset did not reset a saved builds tree.  It would just clear your current working tree.  Right now it does the former.
 
> This means if
you want a new tree then you will have to make one (ctrl+n or File->New
Build). 

I understand how you are operating it currently, I just think the ramification of treating it like this kills old, and usable functionality.  

Why not have a base file for the sandbox like temp.build.  That way, everyone plays in their own sandbox just like the old version and if I want to save what I was working on, it copies it to a new build file just renamed.  That keeps all the old functionality working like it was, and you can use the file system you guys have implemented.

**Comment by EmmittJ** [comment]
Your final point there is something that can be done with the current
system, so I don't really understand why we would need to do this in the
program. Save a new build (temp) and use it as you would the tree before.
You can then use the "Save as" function to save the current tree to a new
build. You have the functionality of the old system with the new build
system functionality.

**Comment by SpaceOgre** [comment]
Maybe it is something like this: In Word (for instance) when you klick "New" you get a temp document (Document1) and you can start writing straight away and when/if you choose to save you are asked for a place and name to store it. Or if you want to discard it. Atm we require a new name straight away, which is more in line with how Visual Studio (or other coding IDEs work). I think most people are more comfortable with the first approach since this is how most editors work that people use on a daily basis: Word, Notepad, PowerPoint etc

**Comment by brather1ng** [comment]
> Clicking reset did not reset a saved builds tree. It would just clear your current working tree. Right now it does the former. To clear a saved builds tree in the old version you would have to save a blank tree on top of it, or delete the build

It doesn't clear a saved builds tree. It's just that the currently opened build is exactly the one from the build list, not a copy like before. You can revert the build to its saved state via right click -> discard changes. With the next release double clicking the current build will also allow reverting.

Next release will probably also allow creating new unnamed builds, like @SpaceOgre mentioned.

**Comment by mmacdermaid** [comment]
I think @SpaceOgre has a point with his description.

@EmmittJ 
>Your final point there is something that can be done with the current
system, so I don't really understand why we would need to do this in the
program.
 
This can be accomplished, but if I'm changing from a saved selected build to a new build the work flow is now:

Scroll up and/or find sandbox saved build.
Double Click it.
Reset it.
Go.

Instead of just 
Reset.
Go.

It seems like an arbitrary difference but imo the second was so superior.

@brather1ng 
>It doesn't clear a saved builds tree.
 
If I double click a build to load one.  If I click reset, it stages the reset to that the tree for that saved build.  You can discard the changes and go back, but why would anyone ever want to reset a tree that is saved?  That's essentially equal to deleting a saved tree.  Which, if I wanted to do that, I would just delete the tree.  ¯\_(ツ)_/¯

>With the next release double clicking the current build will also allow reverting.

This will probably help the issue.

**Comment by brather1ng** [comment]
What @SpaceOgre mentioned is now implemented, too. I can't think of anything else we can do to increase usability.

With the next PoE release being in just over a week, you'll probably not have to wait long for a new release containing these improvements.
