### ISSUE TITLE
Constantly Crashing on loading Trees

### ISSUE THREAD

**Issue by cirf** [EmmittJ/PoESkillTree#406]
Version: 2.4.1
OS: Windows 10

happens very often on many different times

one example:
tried to load an passive tree from characters page:
https://www.pathofexile.com/fullscreen-passive-skill-tree/AAAABAMCAQN1BAcI9A18DlwRUBXXFy8YXRhqGmwbJRzcHRQdTyL0JLAk2Cj6KhMsvzLRNbk6WDwFPO89X0VHRX5GUkbXS65Ms05tUilSU1XGVdZV4FZIVmNXyVgHWFpYd1jlWitca15dXwRj_WZUZp5o8mpDavpremwLbRlxhXIPeC965nyDfOV_xoCkgpuD24RIhW2GrohAjHaPGo9GkPqRK5MnlG-XlZf0mjuboZwyna6f36Evo_KlxKcIpyunlKyYrfG3MbiTvorAVMBmwcXDbci_0B_R_dQH1YHYJNlb3I3fbd-K6QLr7uwY73zv6_fB99f60vxM

Error message:
The error time: 11/24/2016 1:20 PM
Exception: System.FormatException: Die Eingabe ist keine gültige Base-64-Zeichenfolge, da sie ein Nicht-Base-64-Zeichen, mehr als zwei Leerstellen oder in den Leerstellen ein Zeichen enthält, das ungültig ist. 
   bei System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   bei System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   bei System.Convert.FromBase64String(String s)
   bei POESKillTree.SkillTreeFiles.SkillTree.DecodeUrl(String url, HashSet`1& skillednodes, Int32& chartype, Int32& asctype) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\SkillTreeFiles\SkillTree.cs:Zeile 1156.
   bei POESKillTree.SkillTreeFiles.SkillTree.PointsUsed(String treeUrl) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\SkillTreeFiles\SkillTree.cs:Zeile 1412.
   bei POESKillTree.ViewModels.Builds.BuildViewModel.UpdateTreeDependingProperties() in C:\GitHub\PoESkillTree_Source\WPFSkillTree\ViewModels\Builds\BuildViewModel.cs:Zeile 138.
   bei POESKillTree.ViewModels.Builds.BuildViewModel.<.ctor>b__26_0(Object sender, PropertyChangedEventArgs args) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\ViewModels\Builds\BuildViewModel.cs:Zeile 102.
   bei System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   bei POESKillTree.Utils.Notifier.OnPropertyChanged(String propertyName) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Utils\Notifier.cs:Zeile 58.
   bei POESKillTree.Utils.Notifier.SetProperty[T](T& backingStore, T value, Action onChanged, Action`1 onChanging, String propertyName) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Utils\Notifier.cs:Zeile 38.
   bei POESKillTree.Views.MainWindow.btnLoadBuild_Click(Object sender, RoutedEventArgs e) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Views\MainWindow.xaml.cs:Zeile 1850.
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   bei System.Windows.Controls.Primitives.ButtonBase.OnClick()
   bei System.Windows.Controls.Button.OnClick()
   bei System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   bei System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   bei System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   bei System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   bei System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by SpaceOgre** [comment]
Hi,

this is fixed but not released yet. See #401 

What you can do atm is to replace _fullscreen-passive-skill-tree_ with _passive-skill-tree_ and it should work.
