### ISSUE TITLE
Fully qualified path being saved instead of relative path

### ISSUE THREAD

**Issue by trackpete** [EmmittJ/PoESkillTree#410]
In the latest version it's now using fully qualified paths instead of relative paths for the build folder. So, for example, I unpack the poeskilltree into a google drive folder which is mounted on `X:\Google Drive` on a computer at home but `C:\Google Drive` on a different computer. When I try to load up poeskilltree on the other computer, it crashes and throws out:

```Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'X:\Google Drive\poe\PoESkillTree\Builds'.```

This is saved in the `PersistentData.xml` file under `<Options><BuildsSavePath>`

If I change it to just `<BuildsSavePath>Builds</BuildsSavePath>` it works to load things up and doesn't get overwritten later, so it seems like this is a valid fix - I guess it only set that with the full path when I first saved a build on a new install.

**Comment by brather1ng** [comment]
On portable installations it should use relative paths as default value and when changing it through the settings. I'll look into it.

**Comment by jkluch** [comment]
I can confirm the issue @trackpete is having.  His fix worked for me.
