### ISSUE TITLE
Advanced tree generator can't find conforming tree if Phase Acrobatics node is tagged

### ISSUE THREAD

**Issue by EnderWiggin** [EmmittJ/PoESkillTree#411]
'Skill tagged nodes' action does work fine. But advanced tree generator can't build tree if Phase Acrobatics node is tagged.

**Comment by brather1ng** [comment]
It requires you to tag *all* keystones you want to have skilled. So, in this case you need to tag Acrobatics, too. This is done so it doesn't take nodes gated by keystones (e.g. the life behing Blodd Magic).

There is one case, Phase Acrobatics, were it doesn't really fit, as a keystone is gated by another one. But I don't think it's worth implementing an exception for this case. You just need to know that all keystones need to be tagged.

**Comment by EnderWiggin** [comment]
well, life behind blood magic is easily blocked by cross-tagging blood magic. In any case, maybe this error message needs to be a little bit more descriptive.

**Comment by brather1ng** [comment]
You'd have to cross-tag blood magic for most life builds then, instead of check-tagging it for the few blood magic builds.

> In any case, maybe this error message needs to be a little bit more descriptive.

I agree.
