### ISSUE TITLE
Frequent crashing when monitor resolution switches from 1080p to 4k

### ISSUE THREAD

**Issue by RMBraun** [EmmittJ/PoESkillTree#412]
Not sure if this is just an issue with my computer but thought I'd report it just in case. 

The application seems to crash whenever I switch from 1080p resolution to 4k. 
I've also been having random crashing when changing the application window size on my 4k monitor (or zooming in and out).

If my monitor is set to 4k resolution and I then open the application, it runs fines (until I change the resolution).

I do have application size scaling enabled when running 4k resolution.

**Comment by brather1ng** [comment]
Is there some kind of error message when it crashes?

If it shows "The program crashed. A stack trace can be found at: [...]", the contents of the mentioned file could be helpful to us. If not, I don't think we can do much to fix it.
