### ISSUE TITLE
Wording 'Weave the Arcane'

### ISSUE THREAD

**Issue by Dagda47** [EmmittJ/PoESkillTree#418]
The Trickster ascendancy node 'Weave the Arcane' differs from the 2.5 patch notes:

> Weave the Arcane now also reduces damage taken by 8% if you have spent a total of 200 mana recently.

Therefore

> 8% reduced Damage Taken for 4 seconds after spending 200 Mana

 has to be changed in:

>8% reduced Damage Taken if you have spent a total of 200 Mana recently

**Comment by brather1ng** [comment]
The skill tree data comes directly from GGG. We have no influence on it.

**Comment by EmmittJ** [comment]
The keyword recently means 4 seconds.
