### ISSUE TITLE
How to Use "New Top Level Build"

### ISSUE THREAD

**Issue by Smeagol001** [EmmittJ/PoESkillTree#419]
hi,
first nice program you made there 

I seem to not figure out how to use "New Top Level Build" when i press the button i allways get a empty witch build....
a quick explanation  about the feature would be cool :)
cheers smeagol001

**Comment by SpaceOgre** [comment]
This is what it does, it creates a new (empty) build in the top level (root) of the build structure.
If you are not using any folders it is there is no difference from using create new build.
