### ISSUE TITLE
Two Requests

### ISSUE THREAD

**Issue by EmmittJ** [EmmittJ/PoESkillTree#42]
Two questions/requests:

1) Your item attribute -> Character attributes is pretty sweet. How easy is it for you to incorporate a "what if" item replacement setup? I.e. I'd enter the specific stats for an item and see what the total result and the delta would be (would make theorycrafting and shopping a LOT easier).

2) Is it easy for you to incorporate auras in your offensive stats sections? Would require a on/off check as well as a mana reserve check.

http://www.reddit.com/r/pathofexile/comments/2m3iki/release_201_offline_skilltree_planner_bug_fixes/cm1f40l

What do you guys think?

**Comment by Ttxman** [comment]
I have parsed complete list of all item affixes(from web) and paired it with items types on which they appeared. (parsed from forums ~ 370k magic & rare items per week on torment... )
I can offer the list and some code to whoever would be implementing the item editor...

I will not put it whole on github, if someone want a forum crawler, then he can write his own :)

I am using it to identify mods on items, but it is not entirely completed yet...
![decraftor](https://cloud.githubusercontent.com/assets/2779184/5668491/432cd0ae-9770-11e4-857d-02ac9f116959.png)

**Comment by EmmittJ** [comment]
Closing this as it hasn't been talked about or acted upon in a year
