### ISSUE TITLE
program reverts to previous version after reboot

### ISSUE THREAD

**Issue by efraimip** [EmmittJ/PoESkillTree#421]
this is a bug.

i had poe skill tree from the previous version (for 2.3) and when i run the in-app "update" it does all of that just fine, updates the app, and works all fine.

however when i then close the app and restart my computer, and then start poe skill tree app again ---> it starts up version 2.3 and not the updated version for 2.5

ive done this now 3 times, and repeated it.
it does not keep the update.
perhaps its keeping the previous app in memory?

i am trying now to download the full install and physically replacing it by deleting the old version and installing the new version. that should fix it - but auto update is not working.

**Comment by l0g0sys** [comment]
It's not actually possible to update 2.3 version to 2.5. There is 
warning about it, when you do update, that new version will be 
installend along side old version. It won't remove old version so you 
still can access and work with old builds.

Thus after you updated to new 2.5 version, you have to launch new 2.5 
version from Start menu, or remove old and add new version to your 
pinned task list, or add new shortcut to desktop pointing to new 
version. Depending on sure how are you trying to launch it.
