### ISSUE TITLE
PseudoAttributes subfolder not populated after fresh install

### ISSUE THREAD

**Issue by JohnDNoodle** [EmmittJ/PoESkillTree#422]
I tried to update via the ingame updating system, that gave an error. So i decided to uninstall and reeinstall the aplication.

When trying to start the program, an error kept coming up and the aplication was unable to run.
the debuglog gave following information 

> The error time: 12/7/2016 7:24 PM
> Exception: POESKillTree.TreeGenerator.Model.PseudoAttributes.PseudoAttributeDataInvalidException: No Pseudo Attributes loaded. Make sure C:\Users\JohnD_2\AppData\Roaming\PoESkillTree - Atlas of Worlds\Data\PseudoAttributes is not empty.
>    at POESKillTree.TreeGenerator.Model.PseudoAttributes.PseudoAttributeLoader.LoadPseudoAttributes(XmlPseudoAttributes xmlPseudoAttributes) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\TreeGenerator\Model\PseudoAttributes\PseudoAttributeLoader.cs:line 74
>    at POESKillTree.TreeGenerator.ViewModels.AdvancedTabViewModel.ReloadPseudoAttributes() in C:\GitHub\PoESkillTree_Source\WPFSkillTree\TreeGenerator\ViewModels\AdvancedTabViewModel.cs:line 656
>    at POESKillTree.TreeGenerator.ViewModels.AdvancedTabViewModel..ctor(SkillTree tree, IDialogCoordinator dialogCoordinator, Object dialogContext, Action`1 runCallback) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\TreeGenerator\ViewModels\AdvancedTabViewModel.cs:line 600
>    at POESKillTree.TreeGenerator.ViewModels.SettingsViewModel..ctor(SkillTree tree, ISettingsDialogCoordinator dialogCoordinator) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\TreeGenerator\ViewModels\SettingsViewModel.cs:line 53
>    at POESKillTree.TreeGenerator.ViewModels.TreeGeneratorInteraction.<set_SkillTree>b__16_0() in C:\GitHub\PoESkillTree_Source\WPFSkillTree\TreeGenerator\ViewModels\TreeGeneratorInteraction.cs:line 38
>    at POESKillTree.Utils.Notifier.SetProperty[T](T& backingStore, T value, Action onChanged, Action`1 onChanging, String propertyName) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Utils\Notifier.cs:line 37
>    at POESKillTree.TreeGenerator.ViewModels.TreeGeneratorInteraction.set_SkillTree(SkillTree value) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\TreeGenerator\ViewModels\TreeGeneratorInteraction.cs:line 35
>    at POESKillTree.TreeGenerator.ViewModels.TreeGeneratorInteraction..ctor(ISettingsDialogCoordinator dialogCoordinator, IPersistentData persistentData, SkillTree skillTree) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\TreeGenerator\ViewModels\TreeGeneratorInteraction.cs:line 51
>    at POESKillTree.Views.MainWindow.<Window_Loaded>d__81.MoveNext() in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Views\MainWindow.xaml.cs:line 547
> 

I checked the "AppData/Roaming" folder for the aplication and the PseudoAttributes subfolder was empty.

Maybe the installation routine forgot to populate the subfolder with the appropriate xml-files, it seems like it wants to load from a local "C/Github/PoeSkillTree_Source"-folder that doesnt exist on the local machine.

I manually copied the files from [PseudoAttributes in Github-Repository](https://github.com/EmmittJ/PoESkillTree/tree/master/WPFSKillTree/Data/PseudoAttributes) and now the aplication seems to work fine.

**Comment by EmmittJ** [comment]
Duplicate
