### ISSUE TITLE
Pseudo Attributes Empty - what to download?

### ISSUE THREAD

**Issue by daAresinger** [EmmittJ/PoESkillTree#426]
So the planner keeps crashing when I start the programm.

The stacktrace tells me to check the PseudoAttributes folder. It turns out to be empty, which it apparently shouldn't be. What do I need to download to be able to fix this?

[Sorry didn't feel like creating a Pastebin acc for this.](https://drive.google.com/open?id=0By037qa7xxEwNXhrSkY5c0dhSzA)

**Comment by brather1ng** [comment]
This appears frequently, so I wrote a wiki page: [Program crash: "No Pseudo Attributes loaded."](https://github.com/EmmittJ/PoESkillTree/wiki/Program-crash:-%22No-Pseudo-Attributes-loaded.%22)

Is that the only empty data directory (do `Data/Equipment` and `Data/ItemDb` contain XML files)?

**Comment by daAresinger** [comment]
yes those two are empty aswell.
Thanks for the help
