### ISSUE TITLE
poeplanner url gives "index outside bounds of array"

### ISSUE THREAD

**Issue by inspire22** [EmmittJ/PoESkillTree#427]
http://poeplanner.com/AAQAAPcTEAB534rpAkuuGyXZW20ZEVA1uacrHU-X9FJTPV-XlUyz0B_v6yBuUDARD6yY99eESFxrw23i9wFvi3oi9GwLkyd_xsHF7Bgsv4_60NBfakcG2-e0xcM6KjhcQFS9Fe2Wi9W5h8unm3WezxXYdrk-rGYs4X3j8uFjQ2wI8YrviPk3189Jsb6KoS8RlpAbcFaaE9vUieDmWJMfSRPK07QM6roNfBXXhq5WYw5IXfIqC3BSoqMPxDt8uMrw1UlROw32_Kc0YqxsjJ2qES_rY7VI1EKEb3X9Fr8PqySLNj1W9dtul9COihpI9Ch88JEHu_wVfn6hadgAAAAAAA==

Thanks for a great program, I use it all the time!

**Comment by EmmittJ** [comment]
PoE Builder generates URL's that are not compatible with our program. They
contain extra data that cannot be used.

**Comment by inspire22** [comment]
Aah.  For some reason the release page mentions "Added PoEPlanner support".  Can't we just discard the extra info?  I just want to see the tree...

**Comment by EmmittJ** [comment]
That was some time ago when the URL was generated correctly.

**Comment by inspire22** [comment]
Thanks!  Any tips how to "clean" a poebuilder url in any way to get it back to a regular url?  I couldn't find any sort of output on their site, or a way for one of the other sites to import from poebuilder unfortunately.

**Comment by brather1ng** [comment]
Click on the "Share" button in the bar at the bottom and take the pathofexile.com link. That one should work.
