### ISSUE TITLE
Crash when Open

### ISSUE THREAD

**Issue by JulioPradera** [EmmittJ/PoESkillTree#430]
I'm downloading the PoESkillTree for the first time on this new computer.
I've tried installing different versions, both portable and normal, but the PoESkillTree always stops responding a few seconds after opening.
The log file has only one line:

2017-01-15 13:05:59,764 [ 1] INFO  PersistentDataDeserializerCurrent - Build folder file C:\Users\\[MY USER]\AppData\Roaming\PoESkillTree - Atlas of Worlds\Builds\\.buildfolder does not exist. Contained builds will be ordered arbitrarily.

Has anyone ever came across this problem and know how to solve it?

**Comment by brather1ng** [comment]
This doesn't seem to be a known problem. If it stops responding when showing the progress dialog, can you screenshot the program window when it stops responding?

**Comment by JulioPradera** [comment]
@brather1ng All I have to do is simply open the program so that it stops working.
I can not do anything else.

![image](https://cloud.githubusercontent.com/assets/6794347/21966001/ab5f669a-db49-11e6-9fa9-154c868e7dc3.png)
The alert is written:
"PoESkillTree has stopped working
A problem caused the program to stop working properly. Windows will close the program and notify you if a solution is available."

**Comment by brather1ng** [comment]
Hm, I don't think there's much we can do from our side. Do you happen to have Raptr or PlaysTV installed? There were similiar bugs for people that had those (see #366).

**Comment by JulioPradera** [comment]
@brather1ng Solved problem.
I just closed the Raptr and the PoESkillTree came back working. Like magic.
Thank you so much.
