### ISSUE TITLE
Option to Auto-Collapse Build Folders on Load

### ISSUE THREAD

**Issue by BlazesRus** [EmmittJ/PoESkillTree#434]
Any idea which files would need to be edited to allow it have option to collapse build folders on program start instead of opening every build folder?

**Comment by brather1ng** [comment]
I don't think we need this option. You can collapse them yourself. That information is already stored so when you start the program again, it will collapse what you collapsed before. This is not saved often enough on the release version, but I fixed that (it is now saved on close).

**Comment by BlazesRus** [comment]
Thanks
