### ISSUE TITLE
"Ghost" of dragged items is off

### ISSUE THREAD

**Issue by MLanghof** [EmmittJ/PoESkillTree#437]
This is quite likely a result of using a higher DPI display (Surface 3):
https://i.imgur.com/FU3eSNL.png

My task bar is further on the left, so the coordinates of the dragged item "ghost" are apparently scaled by the same factor I have set for scaling UI elements (180% in this case).

**Comment by brather1ng** [comment]
Hm, can't reproduce it. Tried changing UI scaling on first/second/both monitors, having the program window on first/second monitor and fullscreen/windowed.

**Comment by MLanghof** [comment]
I just tried changing my [display settings](https://i.imgur.com/FeRZFag.png) from 180% scaling to 100% scaling, which eliminated the issue. Switching back to 180% brought it back, so it's definitely the cause.

Did you log out between the changes (it prompted me to and wouldn't apply them without it)?

**Comment by brather1ng** [comment]
Yeah, did not log out. Seems like it applied to everything but PoESkillTree (I got no prompt though). I can reproduce it now.

**Comment by MLanghof** [comment]
Whee!
