### ISSUE TITLE
Rewrite Readme

### ISSUE THREAD

**Issue by SpaceOgre** [EmmittJ/PoESkillTree#438]
The readme is really outdated and should be rewritten and screenshots updated.

**Comment by brather1ng** [comment]
I've copied the current version to a wiki page (with some updating by me): https://github.com/EmmittJ/PoESkillTree/wiki/Readme-draft

This way we can easily work together on updating it and can just copy it back when we are done.

**Comment by SpaceOgre** [comment]
Great

**Comment by EmmittJ** [comment]
Yeah, I have noticed it has slowly started to make no sense. It is still
written as if this is a QoL update to the old planner.

**Comment by brather1ng** [comment]
On the same note, `Help -> View Help` could also use an update.

**Comment by brather1ng** [comment]
I have added some screenshots to the draft. Looks good to me now. If anyone thinks of something worth including as screenshot, just add it (you can clone the wiki repo and add images there).

**Comment by EmmittJ** [comment]
This is very good looking! In terms of screenshots, we can add gems and such as they are released.

**Comment by brather1ng** [comment]
I did add gems to the feature list previously already, added a screenshot for that now. In the future it's probably best to add them as they are released, yeah.
