### ISSUE TITLE
program crashes on startup

### ISSUE THREAD

**Issue by drunkangel** [EmmittJ/PoESkillTree#439]
the skilltree crashes before it finishes loading on startup. [debug.txt](https://github.com/EmmittJ/PoESkillTree/files/812413/debug.txt)

**Comment by Chohonski** [comment]
Having the same issue, with a different crash error. 
[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/812479/debug.txt)

**Comment by Gnawbie** [comment]
same
[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/814334/debug.txt)

**Comment by EmmittJ** [comment]
@Gnawbie https://github.com/EmmittJ/PoESkillTree/wiki/Program-crash:-
"No-Pseudo-Attributes-loaded."


I will have to look into the others

**Comment by brather1ng** [comment]
@Chohonski same issue as what Emmitt mentioned: https://github.com/EmmittJ/PoESkillTree/wiki/Program-crash:-%22No-Pseudo-Attributes-loaded.%22

**Comment by brather1ng** [comment]
@drunkangel I think I found the bug. You seem to have nodes check or cross tagged that don't exist anymore. We'll fix this, but for the program to run again before the next release, do the following:

1. Go to your build save folder. With default settings this is `C:\Users\UserName\AppData\Roaming\PoESkillTree - Atlas of Worlds\Builds`.
2. Open the build you had last selected in some text editor (e.g. right click -> Open With -> Editor)
3. Remove the contents of the tags `CheckedNodeIds` and `CrossedNodeIds`. If you don't know XML, post the files here and I'll fix them for you.
4. If you don't know which build you had last selected or if this might affect multiple builds, repeat steps 2-3 for all your build files.
