### ISSUE TITLE
Storm Weaver Cluster

### ISSUE THREAD

**Issue by gilgame** [EmmittJ/PoESkillTree#448]
There is an issue in the Storm Weaver cluster. It looks like it skips over nodes when you click on other nodes in the cluster. I'm not sure how to explain it, but here's how to reproduce it:

Having the Intelligence node outside the cluster, hover over Storm Weaver. The path will appear to cross through Cold and Lightning Damage, and Cold Damage. Click on Storm Weaver and the Cold Damage node will not light up. Now click on the Lightning Damage node and the path between it and Storm Weaver will not light up.

Version 2.6.0.

**Comment by brather1ng** [comment]
This is a problem with the data from GGG, see #442
