### ISSUE TITLE
crash on initialization

### ISSUE THREAD

**Issue by forestasog** [EmmittJ/PoESkillTree#453]
idk what this debug.txt is saying

http://pastebin.com/GeUJr5VM

**Comment by brather1ng** [comment]
Looks like a skill tree asset image is corrupted. 

Try deleting the folder `Data/Assets/` in the same directory as debug.txt. The assets should be redownloaded the next time you start the program.

**Comment by forestasog** [comment]
actually i figured it out, i had to run as admin
