### ISSUE TITLE
Weird path in Storm Weaver's cluster

### ISSUE THREAD

**Issue by Vankesidi** [EmmittJ/PoESkillTree#455]
If I'm going to Storm Weaver node by the "lightning damage" node, they seems not being connected.
![weirdpath](https://cloud.githubusercontent.com/assets/26617765/24234232/2ad5e826-0fa8-11e7-9478-6bc57537d3bc.jpg)

**Comment by EmmittJ** [comment]
Tools -> Redownload Skill Tree Assets 

This was a bug with the data that was provided to us. This should be fixed with live data.
