### ISSUE TITLE
Affix crafting information from the GGPK

### ISSUE THREAD

**Issue by brather1ng** [EmmittJ/PoESkillTree#465]
Our current Affix information is from exilemods.com. Biggest issue with that is that it's outdated, so I want to get the information directly from the GGPK (through the files I already exported in [RePoE](https://github.com/brather1ng/RePoE/tree/master/data)).

Since the GGPK's mod information is based on tags, I'll take the opportunity to replace our ItemGroup and ItemType enums by GGPK based information with ItemClass (based on ItemClasses.dat) and Tags (based on Tags.dat). This will hopefully make a lot of conversions between enums and other enums or game information much easier (e.g. it already made the ItemBaseLoader 1/3 shorter). And it should be helpful later on for the computation rewriting.

This is the last thing I want to do before starting with #463, so I thought I'd let you know.

Edit: I'll also switch over to translating mod/stat ids on-the-fly while crafting instead of using pre-translated strings. I'll need to implement translation anyway and this'll fix items with changing translations depending on the value, like Ventor's Gamble.

**Comment by erickribeiro-dev** [comment]
@brather1ng will that allow the us to choose[Vaal mods ](http://pathofexile.gamepedia.com/List_of_item_corrupted_implicit_modifiers)on the items?
