### ISSUE TITLE
character sheet still broken

### ISSUE THREAD

**Issue by asdf337** [EmmittJ/PoESkillTree#467]
Is there a fix for this u can add for us? Thanks
![poeskilltree_2017-06-04_13-20-21](https://cloud.githubusercontent.com/assets/29175192/26761064/e949840c-4928-11e7-9b0a-72c48edd4841.png)

**Comment by asdf337** [comment]
Changing resolution seems to fix it, it only seems to fix it when u change to a lower resolution, please add support for 1280x800, it works fine in 1024. didnt work in 1600 and a few others. no idea why, will u be able to look into this? thank u! Great program

**Comment by EmmittJ** [comment]
Hmm, I can't seem to reproduce this on any resolution. @MLanghof do you think this might be related to the issue you were dealing with?

**Comment by MLanghof** [comment]
It is the same symptom but I cannot reproduce it on my system after the fix we were told. I somehow doubt that distributing [stripped down test versions](https://github.com/MLanghof/ExpanderBugRedux/releases) with random changes would be an effective use of time though.

**Comment by erickribeiro-dev** [comment]
I'm having the same problem, but my character sheet (Offense ONLY) is blank. I waited for the update that was released today to see if it would be fixed, before writing in here.

![untitled](https://user-images.githubusercontent.com/18595345/26921422-5e961766-4c12-11e7-9a67-e6bf3b11e072.png)

**Comment by MLanghof** [comment]
That is normal behavior. We didn't get around to integrating a fully fledge offense calculator yet (but we're working on it), so that tab is empty. It's not displaying incorrectly though.

**Comment by brather1ng** [comment]
I got rid of the negative padding and styled the header to have a positive margin. I hope that helps as the cut-off problem shouldn't be able to occur now (no negative padding/margin to be cut-off). Hopefully it doesn't introduce new weirdness.

@asdf337 Can you try out the exe from https://www.dropbox.com/s/fgifux5q9tzs99h/PoESkillTree-467.zip (its the same code as currently on the 467 branch I just pushed)
