### ISSUE TITLE
Some parts of the tree are outside of the screen

### ISSUE THREAD

**Issue by asdf337** [EmmittJ/PoESkillTree#468]
The scion tree and the top part of the wand tree section is outside of the screen. Fixable? Thanks!
![1](https://cloud.githubusercontent.com/assets/29175192/26835108/b74c062c-4ad7-11e7-895d-3e7747ce2ec6.png)

**Comment by EmmittJ** [comment]
What resolution are you running at?

**Comment by asdf337** [comment]
1024x640.

**Comment by MLanghof** [comment]
This can be reproduced by resizing the skill tree window on other resolutions. The bounds calculations seem to be off, I'll take a look.

**Comment by EmmittJ** [comment]
Yeah, I believe the skill tree area is bound in height and width (in some way) to the window height and width.

**Comment by MLanghof** [comment]
It's directly correlated with the space available inside the zoom border (or the tab), see #469.

**Comment by EmmittJ** [comment]
Ah, I had thought that ClipToBounds should have made that not happen, but thanks!

**Comment by asdf337** [comment]
Im not sure what u guys are talking about, but I hope u can figure it out! Good luck! Great program :)

**Comment by EmmittJ** [comment]
It isn't something we can really fix since we don't know what the issue is.

**Comment by asdf337** [comment]
Oh, u guys have a hard time finding the error in the program that causes this?

**Comment by EmmittJ** [comment]
Yeah, basically we don't have an idea what is causing your issue.

**Comment by MLanghof** [comment]
To be clear, this was fixed in the latest release and should no longer happen!

We don't know the "proper"/best way to fix this problem, but we managed to figure something out that works just fine.

**Comment by asdf337** [comment]
I see, thank u for ur work :)

**Comment by asdf337** [comment]
And what have u managed to figure out that works just fine? Thanks

**Comment by asdf337** [comment]
Yes, Thanks! Will this be fixed in the next release? I assume u will fix the new tree for the new patch right? However the character sheet is still an issue, looks like this as of now:
![123](https://user-images.githubusercontent.com/29175192/26943118-c68fae46-4c84-11e7-8dcd-8773b0627f4f.jpg)

**Comment by brather1ng** [comment]
It will be in the next release, yes. "Character Sheet" clipping into the buttons is not really worth fixing imo. It's only an issue on very low resolutions and it's still useable for you.

PS: you are commenting in the wrong issue
