### ISSUE TITLE
Can't import Stash tabs.

### ISSUE THREAD

**Issue by emeraldleo1982** [EmmittJ/PoESkillTree#474]
I click Open Browser after inputting the field information, and it opens a page that just says "false".

If I try to click load stash contents in the skillplanner it says "Unexpected character encountered while parsing value: h. Path ", line 0, position 0."

**Comment by brather1ng** [comment]
That means either authentication failed or the information you put into the fields were incorrect.

Are you logged into your Path of Exile account in the browser the page is opened in?

Did you select a league?

Is your account name written correctly (case is important)?

**Comment by emeraldleo1982** [comment]
I've double and triple checked League and account name, and tried account name with and without @<blank>.com attached, made sure I'm logged into pathofexile.com. Still getting the same issue.

This is from fresh install using latest release client .exe

**Comment by emeraldleo1982** [comment]
Found the issue, the account name needed to be used in the field = the account named shown on the pathofexile.com website in the top left "Logged in as ...", whereas I thought the account name needed is the login i use to get into the game. Issue closed.
