### ISSUE TITLE
Build scripts not working with Visual Studio 2017

### ISSUE THREAD

**Issue by brather1ng** [EmmittJ/PoESkillTree#476]
Our current build scripts don't work with VS 2017 as `vsvars32.bat` [no longer exists](https://stackoverflow.com/questions/42805662/vsvars32-bat-in-visual-studio-2017). 

I talked with @EmmittJ about it and he got it working again with VS 2017, but the new used file doesn't exist on older versions. So we have two option: complicate the build scripts by adding if-cases checking for the installed VS version, or require that everyone uses VS 2017.

If everyone is already using VS 2017, requiring that would be the easier solution.

We could then also use C# 7 features. Those [should work with .NET 4.5](https://stackoverflow.com/a/42488315), meaning the program would still run everywhere it currently does.

C# 7 features: https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7 (mainly true language support for tuples and a bunch of really nice syntactic sugar)

**Comment by MLanghof** [comment]
Are we talking about the "build the installer etc." scripts or the "compile and run the program"?

**Comment by brather1ng** [comment]
The "build the installer" ones and in extension also "compile and run in *release* mode" as that triggers build-locale.bat.

**Comment by MLanghof** [comment]
So in other words, running the debug version would still be possible in earlier VS versions (as in, that build script won't need changing)?

**Comment by brather1ng** [comment]
Yes, at least I assume so as it currently works with VS 2017 so it wouldn't need to be changed. 

I don't think it would work if we upgrade to C# 7 (at least not without issues), but that is a different discussion.

**Comment by EmmittJ** [comment]
As far as I am aware, running the debugger is the same. The major
difference is the build & release scripts being useless in VS2017 without
modification.

If there happens to be features that can't be compiled, would you be
willing to upgrade to VS2017?

**Comment by MLanghof** [comment]
I currently am installing VS2017, turns out syntactic sugar makes for a pretty good bait.

We definitely need to put the info out there for other contributors though.

**Comment by brather1ng** [comment]
If you got VS 2017 up and running and are fine with using it, I guess that means everyone currently active here now uses VS 2017.

> We definitely need to put the info out there for other contributors though. I just looked and we don't even have a "How to contribute" readme section/wiki page...

Yeah, some kind of general information, stating things like the Visual Studio, .Net and C# version we use, should definitely be somewhere. I'd say a small section in the readme would be enough.

For information on the contributing itself, GitHub supports linking a file (contributing.md) in the issue/pull request creating pages. (see https://help.github.com/articles/setting-guidelines-for-repository-contributors/)

(further discussion on this should probably be done in a new issue)
