### ISSUE TITLE
Bandit rewards

### ISSUE THREAD

**Issue by Lashrath** [EmmittJ/PoESkillTree#477]
Hi Bandit rewards have changed in 3.0 - so the skill-point-stat - charge trio is no longer applicable. (probably)

**Comment by EmmittJ** [comment]
This is something we will wait on until we get all the data. Skill points
from quests also will need to be updated if the total changes

**Comment by brather1ng** [comment]
Bandits are updated now. Does anyone know whether the number of skill points from quests changed?

**Comment by EmmittJ** [comment]
You get 2 from no bandits, but I am not sure if the total changed
