### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by pmcthor777** [EmmittJ/PoESkillTree#482]
Program keeps crashing on startup, cannot do anything. Tried both installer and zip.
[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/1106001/debug.txt)

**Comment by brather1ng** [comment]
A solution can be found on the wiki: https://github.com/EmmittJ/PoESkillTree/wiki/Program-crash:-%22No-Pseudo-Attributes-loaded.%22

**Comment by pmcthor777** [comment]
Now it will load the program, but as soon as there's any interaction with it, it crashes again

![image](https://user-images.githubusercontent.com/20137399/27598890-d0866dae-5b1b-11e7-8fde-28e04e080cba.png)

**Comment by brather1ng** [comment]
Did you by any chance delete something in the program's AppData folder before opening this issue (`C:\Users\PMC\AppData\Roaming\PoESkillTree - The Fall of Oriath\`)?

Do you have Raptr or PlaysTV installed? They are known to crash PoESkillTree.

**Comment by pmcthor777** [comment]
Nope, did not delete anything. I tried from scratch and still the same thing. Don't have Raptr or PlaysTV installed.

**Comment by brather1ng** [comment]
Assuming the same thing happens with the zip version, can you please run that and post the `logs/main.log` file (located in the same folder as the PoESkillTree.exe)?

This is not a crash that comes from the code itself, or else you would have gotten the same type of error as when it directed you to the debug.txt. So there's not really much we can do to try to find the bug.

**Comment by pmcthor777** [comment]
Here's the file

[main.log.txt](https://github.com/EmmittJ/PoESkillTree/files/1106460/main.log.txt)

**Comment by brather1ng** [comment]
Hm, nothing in there that indicates what the cause is. Well, I have absolutely no idea what may cause the issue, sorry.

**Comment by pmcthor777** [comment]
Found the cause! It's RivaTuner Statistics Server v6.5.0. Upgrading to v7.0.0 beta resolved the crashing :)
