### ISSUE TITLE
Passives Not Up To Date with POE v3.0

### ISSUE THREAD

**Issue by novastomr1** [EmmittJ/PoESkillTree#491]
When using the skill tree for my build, I have noticed several of the passive nodes have changed position and have different stats in Path of Exile v3.0 Fall of Oriath when compared to PoESkillTree.

**Comment by brather1ng** [comment]
You can get the live sill tree data through Tools -> Redownload Live Skill Tree Data.

But we should do a release over the next days that contains all the new data.
