### ISSUE TITLE
Missing keystone

### ISSUE THREAD

**Issue by BananaNation** [EmmittJ/PoESkillTree#492]
At the bottom of the tree, near the Slayer start, the Crimson Dance notable is missing http://puu.sh/x9XWT/84e941673e.jpg  - PoESkillTree

http://puu.sh/x9Y36/8df7ff69e6.jpg - In-game tree

Some node clusters have different placement too, but that could have been done intentionally to save space.

**Comment by MLanghof** [comment]
Are you using the latest version?

Also, try pressing "Redownload Live Skill Tree Data" in the Tools menu.
