### ISSUE TITLE
Feature Request: Tree comparison

### ISSUE THREAD

**Issue by impacienco** [EmmittJ/PoESkillTree#70]
Not sure how easy this is to code (and let me know if you prefer that I leave requests on the forums/reddit instead of here).

It would be great to be able to select two trees/builds and get a one-click comparison that would show the net differences between the builds (e.g. +20% elemental damage, -40 dex).

**Comment by Ttxman** [comment]
Actually implementing basic tree comparison was easy...
I'm sorry i had probably duplicated (or conflicted with) some of BlueManiacs code, but nothing was happening and i really need to make a new build :)

**Comment by EmmittJ** [comment]
Alright, well it's no problem really. That's what happens in a project that
is open source. People develope things ;)

Version switching won't be implemented into the app. It's just too much to
keep working at a time. We can try and be retroactive but there are too
many trees to worry about, and people would expect it to work 100%
