### ISSUE TITLE
Optional selections

### ISSUE THREAD

**Issue by riku-ilola** [EmmittJ/PoESkillTree#73]
Hey,

I've been drafting a few builds using the calculator and had an idea involving non-essential nodes for certain builds. The idea is that some builds have essential nodes that are a must-have, but they also have some nodes that are more valuable for certain playstyles and depend completely on preference. If you could somehow save a build that saved the info about the optional nodes in them and link/give it to friends or share with anyone, it could be a very useful feature.

I'm not exactly sure if it would be possible to save a secondary string of values after the official tree link so that people could import that into your calculator (and probably your calculator only, until poebuilder and rest pick up on it). The secondary string would perhaps include all optional nodes that have a different route highlighting to express their optionality and could be used to highlight good options for a build, that an user should consider taking.

This could all be written in text in the build guide as well, but I know most people skip straight into build, links and gear and ignore everyting else in build threads. Would just make the info more steadily available.

If I were to extend this thought even further, I could imagine having a base build with additional optional routes that your calculator could switch between, eg..
- FB IB build, RT, some life, etc..
  - SC route with mostly damage, some more life
  - HC route with MoM/IR and a lot of life etc
  - HC2 route with a lot of block and evasion/dodge with Ondars/etc.

Naturally any of this shouldn't break the core functionality so that you could still import/export normal builds if you chose to, but have an extra tool at your hands. Say you wanted to write a guide and need 3 build links for beginners, for experienced and for HC and even then miss out on some nodes that might be worth checking out for anyone reading your guide.

You're doing good work, keep it up. :)

**Comment by EmmittJ** [comment]
I am going to say that this is basically #14 and will close this to clean up the issues here.
