### ISSUE TITLE
"Skill highlighted nodes" is (too) greedy

### ISSUE THREAD

**Issue by MLanghof** [EmmittJ/PoESkillTree#98]
The current algorithm just greedily finds the closest target node and connects to it, then repeats. This way, it will never introduce Steiner points and will generally fail to find an optimal solution.

Example: I highlighted "Coldhearted Calculation" and "Void Barrier" (e.g. with regex "Void Barrier|Coldhearted") and have an empty Shadow tree. If I click on "Skill highlighted nodes", the current algorithm will first grab Coldhearted Calculation (7 points to grab vs 9 for void barrier) and then Void Barrier, resulting in [this tree](http://www.pathofexile.com/passive-skill-tree/AAAAAgYBRXwsRjy9UEKiLg5IXfLjhDY9bWzndNsaEHu-Og==) with 14 points.
[This tree](http://www.pathofexile.com/passive-skill-tree/AAAAAgYBDkhd8uOENj1tbOd02xoQe746D6uzDiHAsNg=) uses one point less though.

The problem of connecting a set of target nodes within a tree (with minimal point investment) is known as the [Steiner Tree problem](http://en.wikipedia.org/wiki/Steiner_tree_problem). It is NP-hard, so it will be quite difficult to devise an algorithm that finds the optimum reliably and within reasonable time for this kind of app.
I'm working on something for this, but I just wanted to create this issue so others who wonder if the current algorithm is optimal can learn about it. And possibly also to let others know someone is working on it.

**Comment by EmmittJ** [comment]
Thanks, I was actually looking into it, but I am not very familiar with
algorithms. It would be great if you could fix it up :)

**Comment by EmmittJ** [comment]
Hey MLanghof,
Just checking in to see how you are doing with the algorithm changes. If you need any help go ahead and let me know.
Thank you,
Emmitt

**Comment by MLanghof** [comment]
I'm just quite buy with real life stuff atm. I got around to discussing my ideas with a friend and refined some stuff mentally, but I still have to code it. The coming weekend will likely see me getting on this.

**Comment by EmmittJ** [comment]
Alright, thank you! Just wanted to make sure you were still here. I was
also discussing this problem with a friend, and going over the algorithm
you chose looks to be one of the better ways to do things. Just one
question: how well does Steiner's scale with hundreds of nodes? I haven't
done too much digging into it, but I didn't see a run time analysis on the
wiki page.

**Comment by MLanghof** [comment]
There is no run time analysis of "Steiner" because the general problem is NP-hard (so it would scale exponentially if P != NP). Since approximation algorithms aren't guaranteed to find the best solution, estimating a run time is dependent on when you consider stuff "done".

I'll elaborate my idea at another point, but suffice to say that it greatly reduces the search space and should thus scale pretty well. One of the good things here is how the input size is bounded/known (although not exactly small) so the algorithm can be adapted to that.

**Comment by MLanghof** [comment]
Freaking dammit. I just managed to wipe out all my work thus far.
Note to self: Trying to fix filename conflicts by first excluding the files from the project and then deleting the containing folder in visual studio (on an SSD) does indeed, as the warning suggests, erase everything in that folder permanently.

I'm hesitant to commit multiple completely WIP files, so I don't even have a git backup. Ironically, the files are still listed in the .csproj, the only place I didn't want them to be.

Well, luckily a big part of the work thus far was figuring out data structures and gathering resources (like how to implement something like a java TreeMap in C#, which is unreasonably convoluted).

While I'm already rewriting stuff, I might as well ask: Are there any style guidelines you guys are trying to follow (like private members as `_memberName` and similar)? I'm trying to adapt to what I see so far, but it doesn't feel quite coherent.

**Comment by EmmittJ** [comment]
We don't exactly follow a style guide, since some of the project was done
before we picked it up. Basically as long as you are consistent in your
work, it should be pretty simple to follow with what you are doing

**Comment by EmmittJ** [comment]
Also, sorry to hear about your code loss :/

**Comment by MLanghof** [comment]
...I have no idea how it happened, but the files are back. Like nothing ever happened. I had immediately checked the folder in explorer after realizing my mistake, but they were gone. And now after a VS restart they're back. I didn't even touch git, so I have absolutely zero clue where they came from. I'm just glad I don't have to rewrite all those preliminary thoughts that I noted down.

Lesson learned.

**Comment by MLanghof** [comment]
I would like to use this code: [High Speed priority queue for C#](https://bitbucket.org/BlueRaja/high-speed-priority-queue-for-c/wiki/Home)

It's MIT license, I'm not sure where/whether to credit the original author though (and include the license copy?). Speaking of which, does this project even have a license yet?

**Comment by EmmittJ** [comment]
Currently it doesn't have a license type, because honestly I had forgotten about it. Adding a license type is no big deal, since it is an open source project we can just throw it under a MIT license. I can make that official later; I am currently in class.

**Comment by MLanghof** [comment]
Just as a progress-update, I've got almost all the code down now, finishing the link between the app and my optimizer tomorrow. Then comes the debugging (which might be sort of nightmarish since I didn't test anything yet. Shame on me, I know).

Unit test are cool, I know, but how do you properly unit-test a (somewhat) non-deterministic optimizer (without making any slight change to the algorithm immediately fail the test)? I can seed it, but any code modification can still change the behavior unpredictably...

**Comment by l0g0sys** [comment]
Check my unit tests in UnitTests project.
In your case, testing method indirectly using SkillTree should be 
sufficient.
Something like this:
     Tree.Load("some-tree-url");
     Tree.SelectNode(someNodeToSelect);
     Assert.AreEqual("expected-tree-url", Tree.Url); // If only 1 path 
is optimal and should be selected.
     Assert.IsTrue("expected-tree-url-1" == Tree.Url || 
"expected-tree-url-2" == Tree.Url); // If two path satisfies optimal 
selection.

     Tree.Load("some-different-tree-url");
     ...

**Comment by MLanghof** [comment]
Well, the issue is that this is an optimization algorithm (a non-deterministic one at that). I cannot guarantee that it _always_ finds the best path, it only has a good chance to. Yes, I can test for a case with a fixed random seed that I know makes it succeed, but then it can still change/fail due to innocent code changes.

I guess such a unit test would likely still have use with "easy" examples to make sure the interaction with the tree doesn't break (e.g. skills random nodes), but it's not much of a help in validating the algorithm itself.

**Comment by l0g0sys** [comment]
Yep. In the end interaction with tree is more important to us than 
algorithm itself. Write few cases and that's it.
In futre if someone spots wrong behaviour. You write test for that 
specific case and fix algorithm to make that case pass along with all 
earlier tests.
So purpose of tests is more like to ensure that fixing specific case 
won't break previous correct behaviour on other cases.

**Comment by l0g0sys** [comment]
One more thing came to my mind. Actually there is way to test internals 
for class without "invading" its algorithms. Don't remember exact term, 
but it was stub method or something like that (look it up on MSDN). You 
write own method in unit test which will be injected into tested class 
during test.
Example:
class FindNodes { // tested class
     FindNextNode() { // does something }
     FindNode() { // main API method, calls FindNextNode() during its 
execution numerous times }
}
and you write own method FakeFindNextNode which will replace original 
method in FindNodes class, inside of which you will invoke original 
method but also can record some stuff in unit test class, like number of 
calls. So you can then measure also "how many calls of FindNextNode" it 
took for test case and then you can write some Assert that number of 
calls should be less than X. Just to ensure that algorithm didn't go too 
much astray :)

**Comment by MLanghof** [comment]
Well, I wouldn't have believed it, but writing unit test improves my actual code. Sometimes it just gives that nudge to extract things into separate classes.

Currently debugging and testing.

**Comment by EmmittJ** [comment]
We can help you with testing if you would like to push your code to your repo :)

**Comment by MLanghof** [comment]
Current state is now in my repo. It's nowhere near working correctly, but it runs and interacts with the skill tree. It's still very WIP.

I tried to keep explaining things in comments, but some of them may not be up to speed. I'd be impressed if you can figure out what's going on in the code though :)

**Comment by EmmittJ** [comment]
Not sure it was pushed. Code logic is always fun to figure out! I was talking with my algorithms instructor the other day and she had actually written a paper on Steiner's. Basically she told me that it's going to be a pain in the ass, and from what it sounds like...it has been.

**Comment by MLanghof** [comment]
Oh right, you need to look in the steiner branch. Here: b5d638819bb2537b9cf63ed5105980e43190df32

**Comment by EmmittJ** [comment]
![Oh boy] (http://i.imgur.com/AdKSkzl.jpg)

Oh buddy, sort of works xD

**Comment by MLanghof** [comment]
Ikr?
You can clearly see though that the result is not a tree, so the problem is not in the algorithm but in the implementation. I suspect the MST algorithm might be at fault, but it looks quite correct. I'd try and first verify the functions it uses in unit tests, but I don't think I'll have time for it today.

(Unrelated:) Rough first profiling also shows that the program spends close to all the time of the solving in MinimalSpanningTree.Span().

**Comment by EmmittJ** [comment]
Yep, that's what happens when the path to nodes can run through hundreds of ends. This is kind of why the current skill highlight all works how it does. Pretty easy to grab a path to a node and move on but solving every path to every node and taking the smallest can be a bit rough.

**Comment by MLanghof** [comment]
Well I'm not doing this because I'm looking for a "pretty easy" way :P

**Comment by MLanghof** [comment]
Right, I think I know why things go so wrong in there. The HeapPriorityQueue code inherits from IEnumerable, but doesn't actually work properly with Linq (like I was attempting [here](https://github.com/MLanghof/PoESkillTree/blob/steiner/WPFSKillTree/SkillTreeFiles/SteinerTrees/MinimalSpanningTree.cs#L58)).
That screwed over the entire MST algorithm, so the output is garbage.

**Comment by EmmittJ** [comment]
Alright, sounds good! Not sure why it wouldn't work properly with Linq, but it filtering would make sense for the garbage that is coming out.

**Comment by MLanghof** [comment]
Aaand finally I got to the heart of what appears to be a promotion issue that completely screwed over my distance cashing. The MSTs now actually are MSTs, so that's a huge success :D

**Comment by MLanghof** [comment]
Ok, done!

Please play around with it and test it with whatever builds you can come up with to see if it finds the optimal path!
The only debug feature I left in was that it highlights the used steiner nodes of the optimal solution (abuses attribute highlights, right-click a random attribute to get rid of it).

I'll only make a pull request once I'm convinced that everything works (and once I have time).

Please tell me what you think!

**Comment by EmmittJ** [comment]
So, how hard do you want me to test this thing? 
![...not fun] (http://i.imgur.com/0jxnzk7.png)

Because that may not be fun...

**Comment by EmmittJ** [comment]
![6hours] (http://i.imgur.com/24miV8l.png)

6 Hours and it did it xD

**Comment by MLanghof** [comment]
Haha :D
Btw, you could've greatly reduced population size or iteration count if you test such "trivial" examples for correctness. It didn't calculate _anything_ productive in those 6 hours, every single solution tried was identical.

**Comment by EmmittJ** [comment]
Currently it seems to work pretty damn well, although extremely slow (which makes sense). I would say you could go a little longer than 5 seconds busy, that isn't very many iterations at all, 15-20 seconds would suffice.

**Comment by MLanghof** [comment]
Did you test with various population sizes and iteration counts? I admit those are not the easiest to find, but in my tests (which were, to be fair, on pretty good hardware), 200 iterations with 60 population size took way less than 5 seconds and generally found the optimum within the first generation (for random "realistic" trees).
As an example, it takes 3.5 seconds to find the best solution for the "all keystones" build (which is 91 nodes according to my results (that is, highlighting precisely only the keystones, not stuff behind it)) with those settings. However, the best solutions if already found in iteration 3 of 200.

**Comment by EmmittJ** [comment]
I would agree with 50 iterations, maybe even less. Most trees that I have tested are under 20, but every once in a while they will break over 20. 50 seems to be the best mark. As for population not sure, will have to do a bit more testing

**Comment by MLanghof** [comment]
So, I've progressed this further (believe it or not, the algorithm was quite faulty before). A few more unit tests, a lot of bugfixing, lots of testing and tweaking for optimal convergence speed (and reliability).

Could I maybe get the help of some UI-capable person in making a window that would inform the user of the progress of the calculation?

I'd like to have the following in there, updated constantly while the optimization is going:
-Current generation and end generation (so you get % progress).
-Best solution node count (maybe even a way to show the current best solution in the tree?).
-Ways to interrupt the calculation. Maybe even to resume it (for example if you're not satisfied with the output).

The actual algorithm would run in a separate thread to not block the UI. Yes, I'm aware of the difficulties threading can bring with it (especially communicating between threads).

**Comment by EmmittJ** [comment]
I wish I could help with the UI, but my skills are fairly subpar when it comes to the UI. @SpaceOrge is pretty good with them. As for threading...have fun. It isn't going to be fun to cross communicate like you said (although they don't have to communicate much).

**Comment by MLanghof** [comment]
Well, I've began writing a small UI to my liking, but I simply cannot figure out how to properly add a new window to the project. From what I can tell, there is (naturally) auto-generated code in the background that is not properly generated when copying an existing window, and that derives from the wrong class (Window instead of MetroWindow) when creating a new window to the solution via Add (and manually changing the base class in the .xaml.cs file interferes with the auto-generated stuff).

Should I shoot @SpaceOgre a PM?

**Comment by EmmittJ** [comment]
Oh whoops, yeah that was my bad for the misspelling. Go ahead and shoot him a PM and see if he can't help you out. In the meantime look into how LoadingWindow.xaml works (I think that is somewhat of what you want).

**Comment by MLanghof** [comment]
...nevermind, apparently Git removed its PM feature. Hm. Here's hoping this will reach him.

**Comment by MLanghof** [comment]
Nevermind! It's working now. Maybe I had a typo in the window class name somewhere.

**Comment by SpaceOgre** [comment]
Just saw this now, good that you got it to work :)
If you have any other questions about the UI please ask here and I will try to answer, I'm no WPF UI master but I know some things.

This reminds me that I have a menu feature to add that I promised like 2months ago...

**Comment by MLanghof** [comment]
Ok, I feel like I'm closing in on being done. I have a nice little UI window now that keeps the user updated, I'm currently abusing the "compare trees" visual for showing what the algorithm's current best solution is (really happy with that) and the convergence speed is nice.

I decided to combine the genetic algorithm (multiple individuals that exchange dna (= solution) fragments, weaker individuals are purged every iteration) with a simulated annealing for the mutation (accepting a mutation to a worse state becomes less likely with the progressively decreasing "temperature").
Usual ~100 point trees take a slight while (depending on your hardware), but the results so far seem great (I'll make sure to get a test build up soon so you guys can challenge it with your trees).

I still have to do some cleaning up and stuff, but I think the bulk is done. Although I already have plans...

**Comment by MLanghof** [comment]
Oh and something else, I'd really like to document my code and the ideas behind it somewhere, so other people can wrap their head around it. I don't feel like this issue thread is particularly suited for that though. Should I be writing all my elaborations in some place as a big comment section in the code or should I make a wiki page (or something else)?

**Comment by SpaceOgre** [comment]
Nice work!

I think that Steiner.cs is the place for a more comprehensive explanation, then it will be in place as long as you have the code.

**Comment by MLanghof** [comment]
Btw, do not try and highlight hundreds of nodes. The runtime _is_ polynomial, but something like n^5. Actually, let me see:
-Building 1 MST: O(n²) (times log(n) or something from the queue) with n = number of nodes.
-Every generation does that m (population count) times.
-I do k iterations.
I generally have m = k = amount of potential steiner nodes (works reasonably well). n depends on how many and where you highlighted your target nodes, but is on the same order of magnitude.
So I guess you could call it a runtime of O(n^4).
Makes me realize though that my MST algorithm (which definitely is the bottleneck) could be faster.

Oh, and if you're pushing it, you also have the pathfinding (which caches results so every node-pair only needs 1 calculation) racking up CPU time with having to find O(n²) paths. And it doesn't use heuristics (just floodfill), so the runtime of that is O(l²) with l being the path length. I think.

**Comment by SpaceOgre** [comment]
Been trying 20 or so cases and so far it works really well! Excellent work.

A small thing with the graphics: 
![image](https://cloud.githubusercontent.com/assets/381657/6998064/7f330e26-dbd4-11e4-8206-46973890217a.png)

If you have nodes selected the pre-showing does not connect to those. And a small improvement suggestion: Add a do not skill button to the window in case the result is not what the user wanted.

**Comment by MLanghof** [comment]
I fixed the first thing you mentioned (the highlight now includes the already skilled nodes).

I'm unsure if I agree with the second thing. In short, there's the undo functionality. If the user should judge the result before accepting, that would require him to be able to move around and interact with the main tree, which the ShowDialog prevents. Even if it didn't figuring out (and implementing) what the user can and can't do during/at the end of an optimization run seems... not worth the effort. I mean, anybody is free to have a go at it, but undo handles it well enough imo.

Good thing you mentioned the owner thing, I was wondering why that was happening. I'm actually not quite sure how to do it though, since I'm showing the dialog from inside the SkillTree, not directly from MainWindow. Does the tree know anything about its owning window (well I guess that makes little sense)? Or how else should I do it?

I'll sync up with the main repo and look into a pull request.

**Comment by SpaceOgre** [comment]
Totally agree with the undo part, it slipped my mind when I wrote that but first thing more or less when I woke up: why did I write that? We have undo.

Not completely sure about the owner thing, it might just work since main is the one calling the method in the skilltree. If nothing else we can probably solve it by passing an owner parameter in the method call. I can look at it after the merge if you want.

**Comment by EmmittJ** [comment]
If you would like to merge it go ahead. I am not at a computer right now.

**Comment by SpaceOgre** [comment]
Fixed #104
