### ISSUE TITLE
Changing the colors used in Tree Comparison functionality

### ISSUE THREAD

**Issue by PaulNations** [EmmittJ/PoESkillTree#99]
I really like the new tree comparison functionality,than you, thank you, THANK YOU!

Would it be possible to change the colors of the differences?  Currently the colors of the save tree and the proposed tree are so similar that it's hard to locate them in a busy tree.

Thank you again for one of my favoritest programs on GitHub.

**Comment by EmmittJ** [comment]
Do you have a suggestion for a different color?

**Comment by PaulNations** [comment]
Perhaps some complementary colors.  Maybe something lIke having the saved tree in blue and the entered tree in yellow and the intersecting nodes be green?  Maybe offer a right click to customize the link colors.

**Comment by SpaceOgre** [comment]
Tested some different color combinations and are quite happy with this one:
![image](https://cloud.githubusercontent.com/assets/381657/7029087/fed2efa2-dd5a-11e4-8486-000760b1465c.png)
Changes: From Lime to RoyalBlue, and from Yellow to DarkKhaki

What do you guys say?

**Comment by EmmittJ** [comment]
That looks great! I really like that

**Comment by PaulNations** [comment]
That looks really nice. Thank you!
